### ISSUE TITLE
LDAP Authentication: Unknown user

### ISSUE THREAD

**Issue by weiluntong** [tomav/docker-mailserver#1003]
## Context

I am having troubles getting my mailserver setup with OpenLDAP. When trying to login, I get this in the logs:
`Jul 12 06:44:11 mail dovecot: auth: ldap(weilun.tong@fancydomain.tld,172.22.0.2,<xYPdsMdwcousFgAC>): unknown user (SHA1 of given password: 2bd931)`

I've tried running `testsaslauthd -u "weilun.tong" -r fancydomain.tld -p "password"` and the results were successful, it returned `0: OK "Success."`

My docker-compose.yml looks like this:
```
version: "3"

services:
  rainloop:
    image: hardware/rainloop:latest
    restart: always
    volumes:
      - /srv/mailserver/client/rainloop:/var/www/rainloop/data
    networks:
      - myNetwork

  mail:
    image: tvial/docker-mailserver:latest
    restart: always
    hostname: mail
    domainname: fancydomain.tld
    container_name: mail
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - /srv/mailserver/server/data/mail/data:/var/mail
      - /srv/mailserver/server/data/mail/state:/var/mail-state
      - /srv/mailserver/server/config/:/tmp/docker-mailserver/
      - /etc/letsencrypt:/etc/letsencrypt:ro
    environment:
      - ENABLE_SPAMASSASSIN=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=1
      - SSL_TYPE=manual
      - SSL_CERT_PATH=/etc/letsencrypt/live/mail.fancydomain.tld/fullchain.pem
      - SSL_KEY_PATH=/etc/letsencrypt/live/mail.fancydomain.tld/privkey.pem

      # >>> SASL Authentication
      - ENABLE_SASLAUTHD=1
      - SASLAUTHD_LDAP_SERVER=openldap
      - SASLAUTHD_LDAP_PROTO=
      - SASLAUTHD_LDAP_BIND_DN=cn=admin,dc=fancydomain,dc=tld
      - SASLAUTHD_LDAP_PASSWORD=password
      - SASLAUTHD_LDAP_SEARCH_BASE=dc=fancydomain,dc=tld
      - SASLAUTHD_LDAP_FILTER=(&(uid=%U)(objectClass=person))
      - SASLAUTHD_MECHANISMS=ldap
      # <<< SASL Authentication

      # >>> Postfix Ldap Integration
      - ENABLE_LDAP=1
      - LDAP_SERVER_HOST=openldap
      - LDAP_SEARCH_BASE=dc=fancydomain,dc=tld
      - LDAP_BIND_DN=cn=admin,dc=fancydomain,dc=tld
      - LDAP_BIND_PW=password
      - LDAP_QUERY_FILTER_USER=(&(objectClass=user)(mail=%s))
      - LDAP_QUERY_FILTER_GROUP=(&(objectclass=group)(mail=%s))
      - LDAP_QUERY_FILTER_ALIAS=(&(objectClass=user)(otherMailbox=%s))
      - LDAP_QUERY_FILTER_DOMAIN=(&(|(mail=*@%s)(mailalias=*@%s)(mailGroupMember=*@%s))(mailEnabled=TRUE))
      # <<< Postfix Ldap Integration

      # >>> Kopano Integration
      - ENABLE_POSTFIX_VIRTUAL_TRANSPORT=1
      - POSTFIX_DAGENT=lmtp:kopano:2003
      # <<< Kopano Integration

    cap_add:
      - NET_ADMIN
    networks:
      - myNetwork
networks:
  myNetwork:
    external: true
```
I'm not sure where to go from here to test and look for an issue. Any help troubleshooting is greatly appreciated.
