### ISSUE TITLE
Not All Emails are being Received (IMAP)

### ISSUE THREAD

**Issue by HeadBanging** [tomav/docker-mailserver#1020]
Emails come through occasionally, but not consistently.  Often (mostly) email isn't received.

## Expected Behavior
All email should be received since spam assassin is disabled 

## Actual Behavior
Few emails get through.

## Steps to Reproduce
Configuration is as follows:

```
version: '2'
services:
  mail:
    image: tvial/docker-mailserver:latest
    hostname: mail
    domainname: <mywebserver>.com
    container_name: mail-server
    ports:
    - "25:25"
    - "143:143"
    - "465:465"
    - "587:587"
    - "993:993"
    - "110:110"
    - "995:995"
    volumes:
    - maildata:/var/mail
    - mailstate:/var/mail-state
    - ./config/:/tmp/docker-mailserver/
    - ./letsencrypt/etc/letsencrypt/:/etc/letsencrypt/
    environment:
    - PERMIT_DOCKER=network
    - ENABLE_CLAMAV=0
    - ENABLE_POP3=0
    - ENABLE_FAIL2BAN=0
    - ENABLE_SPAMASSASSIN=0
    - ENABLE_FETCHMAIL=0
    - ENABLE_POSTGREY=0
    - ONE_DIR=1
    - DMS_DEBUG=0
    - SSL_TYPE=
    cap_add:
    - NET_ADMIN
    - SYS_PTRACE
    restart: always
volumes:
  maildata:
    driver: local
  mailstate:
    driver: local

```

## Your Environment
Virtual Machine in Rackspace. 1GB RAM, 20GB Storage, 1CPU
