### ISSUE TITLE
Letsencrypt "Connection refused" after changing `domainname`.

### ISSUE THREAD

**Issue by vedtam** [tomav/docker-mailserver#1040]
Hi,

I was using docker-mailserver for months without issues (thanks!), but now I needed to modify my old domain name, so went into `docker-compose.yml` and replaced the old domain name with the new one, stopped than restarted the container using: "docker-compose up -d mail".

But now, I'm unable to generate new letsencrypt certificates using the bellow snippet (running it from the ~/mailserver/letsencrypt folder):

`docker run --rm -ti -v $PWD/log/:/var/log/letsencrypt/ -v $PWD/etc/:/etc/letsencrypt/ -p 443:443 deliverous/certbot certonly --standalone -d mail.webx***.com`

letsencrypt throws the following:

```
...
Saving debug log to /var/log/letsencrypt/letsencrypt.log
Plugins selected: Authenticator standalone, Installer None
Obtaining a new certificate
Performing the following challenges:
http-01 challenge for mail.webx***.com
Waiting for verification...
Cleaning up challenges
Failed authorization procedure. mail.webxpert.click (http-01): urn:acme:error:connection :: The server could not connect to the client to verify the domain :: Fetching http://mail.webx***.com/.well-known/acme-challenge/PHEMinEfz9nY88gXzaQnmY5FJM6RvlKdOlA4HckdNI4: Connection refused

IMPORTANT NOTES:
 - The following errors were reported by the server:

   Domain: mail.webx***.com
   Type:   connection
   Detail: Fetching
   http://mail.webx***.com/.well-known/acme-challenge/5hx234EUXkXxkv7bgJgUunJI-G1q3miDRjvOBzE_JEc:
   Connection refused
```
- The A record exists for `mail.webx***.com`
- I can send/receive test emails but without certificates

I have tackled with this all day but I can't figure out what the issue is. Is there maybe some other configuration or cache I need to delete/update?

I would really, really appreciate some help,
Thanks!

My config:

```
version: '2'

services:
  mail:
    image: tvial/docker-mailserver:latest
    hostname: mail
    domainname: webx***.com
    container_name: mail
    ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
    volumes:
    - maildata:/var/mail
    - mailstate:/var/mail-state
    - ./config/:/tmp/docker-mailserver/
    - /home/ec2-user/mailserver/letsencrypt/etc/:/etc/letsencrypt/
    environment:
    - ENABLE_SPAMASSASSIN=1
    - ENABLE_CLAMAV=1
    - ENABLE_FAIL2BAN=1
    - ENABLE_POSTGREY=1
    - ONE_DIR=1
    - DMS_DEBUG=1
    - SSL_TYPE=letsencrypt
    cap_add:
    - NET_ADMIN

volumes:
  maildata:
    driver: local
  mailstate:
    driver: local
```
