### ISSUE TITLE
[FIXED] mailserver dont restart after pod removal  -> Upgrade Kubernetes Manifest on WIKI

### ISSUE THREAD

**Issue by ekozan** [tomav/docker-mailserver#1053]
I got my server working since yesterday 

and i try many crash scenario but ... :) it's fail when i delete my pod on K8S  

Any idéa  ? ( mail-state coruption ? ) 

LOGS
``` 
#
#
# ENV
#
#

HOSTNAME=mailserver-58c77d5bdc-7zrgc.mailserver.mail.svc.cluster.local
KUBERNETES_PORT_443_TCP_PORT=443
KUBERNETES_PORT=tcp://10.96.0.1:443
MAILSERVER_SERVICE_PORT_IMAP_SECURE=993
KUBERNETES_SERVICE_PORT=443
KUBERNETES_SERVICE_HOST=10.96.0.1
DMS_DEBUG=1
MAILSERVER_SERVICE_PORT=25
MAILSERVER_PORT_993_TCP_ADDR=10.97.166.174
MAILSERVER_PORT_25_TCP_PORT=25
MAILSERVER_PORT_25_TCP_PROTO=tcp
MAILSERVER_SERVICE_PORT_SMTP_AUTH=587
MAILSERVER_PORT_993_TCP=tcp://10.97.166.174:993
ENABLE_CLAMAV=1
MAILSERVER_PORT_587_TCP_PROTO=tcp
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ENABLE_SPAMASSASSIN=1
PWD=/
MAILSERVER_SERVICE_PORT_SMTP=25
MAILSERVER_SERVICE_HOST=10.97.166.174
SHLVL=1
MAILSERVER_PORT_587_TCP=tcp://10.97.166.174:587
HOME=/root
MAILSERVER_PORT=tcp://10.97.166.174:25
KUBERNETES_PORT_443_TCP_PROTO=tcp
KUBERNETES_SERVICE_PORT_HTTPS=443
ONE_DIR=1
MAILSERVER_PORT_587_TCP_PORT=587
MAILSERVER_PORT_993_TCP_PORT=993
MAILSERVER_PORT_25_TCP_ADDR=10.97.166.174
MAILSERVER_PORT_993_TCP_PROTO=tcp
ENABLE_POSTGREY=1
MAILSERVER_PORT_587_TCP_ADDR=10.97.166.174
KUBERNETES_PORT_443_TCP_ADDR=10.96.0.1
MAILSERVER_PORT_25_TCP=tcp://10.97.166.174:25
KUBERNETES_PORT_443_TCP=tcp://10.96.0.1:443
_=/usr/bin/printenv

#
#
# docker-mailserver
#
#

Initializing setup
  Registering check,setup,fix,misc and start-daemons functions
  * _check_environment_variables() registered
  * _check_hostname() registered
  * _setup_default_vars() registered
  * _setup_dovecot() registered
  * _setup_dovecot_local_user() registered
  * _setup_dkim() registered
  * _setup_ssl() registered
  * _setup_docker_permit() registered
  * _setup_mailname() registered
  * _setup_amavis() registered
  * _setup_postfix_override_configuration() registered
  * _setup_postfix_sasl_password() registered
  * _setup_security_stack() registered
  * _setup_postfix_aliases() registered
  * _setup_postfix_vhost() registered
  * _fix_var_mail_permissions() registered
  * _misc_save_states() registered
  * _start_daemons_cron() registered
  * _start_daemons_rsyslog() registered
  * _start_daemons_dovecot() registered
  * _start_daemons_opendkim() registered
  * _start_daemons_opendmarc() registered
  * _start_daemons_postfix() registered
  * _start_daemons_clamav() registered
  * _start_daemons_amavis() registered
Checking configuration
  Check that there are no conflicts with env variables [_check_environment_variables]
  Check that hostname/domainname is provided or overidden (no default docker hostname/kubernetes) [_check_hostname]
  * Domain has been set to mailserver.mail.svc.cluster.local
  * Hostname has been set to mailserver-58c77d5bdc-7zrgc.mailserver.mail.svc.cluster.local
Configuring mail server
  Setting up default variables [_setup_default_vars]
  * Set ENABLE_LDAP=0
  * Set ENABLE_FETCHMAIL=0
  * Set OVERRIDE_HOSTNAME=
  * Set ENABLE_MANAGESIEVE=0
  * Set DMS_DEBUG=1
  * Set VIRUSMAILS_DELETE_DELAY=7
  * Set ENABLE_POP3=0
  * Set ENABLE_SASLAUTHD=0
  * Set ENABLE_CLAMAV=1
  * Set SMTP_ONLY=0
  * Set ENABLE_FAIL2BAN=0
  * Set ENABLE_SPAMASSASSIN=1
  Setting up Dovecot
  Setting up Dovecot Local User
  * Checking file line endings
sed: cannot rename /tmp/docker-mailserver/seddzvLfb: Device or resource busy
  * Regenerating postfix user list
sed: cannot rename /tmp/docker-mailserver/seduxhljb: Device or resource busy
  * user 'mail' for domain 'eko.ovh' with password '********'
  * user 'contact' for domain 'eko.ovh' with password '********'
  * user 'no-reply' for domain 'eko.ovh' with password '********'
  Setting up DKIM
  * DKIM keys added for: eko.ovh-mail.key
  * Changing permissions on /etc/opendkim
  Setting up SSL
  Setting up PERMIT_DOCKER Option
  * Adding container ip in my networks
  Setting up Mailname
  * Creating /etc/mailname
  Setting up Amavis
  * Applying hostname to /etc/amavis/conf.d/05-node_id
  Setting up Postfix Override configuration
  * No extra postfix settings loaded because optional '/tmp/docker-mailserver/postfix-main.cf' not provided.
  Setting up Postfix SASL Password
  * Warning: 'SASL_PASSWD' is not provided. /etc/postfix/sasl_passwd not created.
  Setting up Security Stack
  * Enabling and configuring spamassassin
  * Enabling clamav
  Setting up Postfix Aliases
  Setting up Postfix vhost
  Fixing /var/mail permissions
  * Permissions in /var/mail look OK
Starting Misc
  * Consolidating all state onto /var/mail-state
  *   Destination /var/mail-state/spool-postfix exists, linking /var/spool/postfix to it
  *   Destination /var/mail-state/lib-postfix exists, linking /var/lib/postfix to it
  *   Destination /var/mail-state/lib-amavis exists, linking /var/lib/amavis to it
  *   Destination /var/mail-state/lib-clamav exists, linking /var/lib/clamav to it
  *   Destination /var/mail-state/lib-spamassasin exists, linking /var/lib/spamassasin to it
  *   Destination /var/mail-state/lib-fail2ban exists, linking /var/lib/fail2ban to it
Starting mail server
  Starting cron  [ OK ]
  Starting rsyslog  [ OK ]
  Starting dovecot services  [ OK ]
  Starting opendkim  [ OK ]
  Starting opendmarc  [ OK ]
  Starting postfixfalse
  *  [ FAILED ]
Error: Please fix your configuration. Exiting...
```

K8S config 
```
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: mailserver.config
  namespace: mail
  labels:
    app: mailserver
data:
  postfix-accounts.cf: |
    mail@null.null|*
    contact@null.null|*
    no-reply@null.null|*
  postfix-virtual.cf: |
    dmarc-reports@null.null contact@null.null

  SigningTable: |
    *@null.null mail._domainkey.null.null

  KeyTable: |
    mail._domainkey.null.null null.null:mail:/etc/opendkim/keys/null.null-mail.key

  TrustedHosts: |
    127.0.0.1
    localhost
      
---

kind: Secret
apiVersion: v1
metadata:
  name: mailserver.opendkim.keys
  namespace: mail
  labels:
    app: mailserver
type: Opaque
data:
  null.ovh-mail.key: '*'

---

kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: mailserver
  namespace: mail
  labels:
    app: mailserver
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mailserver
    spec:
      nodeSelector:
        has/mail-server: 'true'
      subdomain: mailserver
      containers:
        - name: mailserver
          image: tvial/docker-mailserver:2.1
          ports:
            - name: smtp
              containerPort: 25
              hostPort: 25
            - name: smtp-auth
              containerPort: 587
              hostPort: 587
            - name: imap-secure
              containerPort: 993
              hostPort: 993
          env:
            - name: ONE_DIR
              value: '1'            
            - name: ENABLE_SPAMASSASSIN
              value: '1'            
            - name: ENABLE_CLAMAV
              value: '1'
            - name: ENABLE_POSTGREY
              value: '1'
          volumeMounts:
            - name: config
              subPath: postfix-accounts.cf
              mountPath: /tmp/docker-mailserver/postfix-accounts.cf
              readOnly: true
            - name: config
              subPath: postfix-virtual.cf
              mountPath: /tmp/docker-mailserver/postfix-virtual.cf
              readOnly: true
            - name: config
              subPath: SigningTable
              mountPath: /tmp/docker-mailserver/opendkim/SigningTable
              readOnly: true
            - name: config
              subPath: KeyTable
              mountPath: /tmp/docker-mailserver/opendkim/KeyTable
              readOnly: true
            - name: config
              subPath: TrustedHosts
              mountPath: /tmp/docker-mailserver/opendkim/TrustedHosts
              readOnly: true
            - name: opendkim-keys
              mountPath: /tmp/docker-mailserver/opendkim/keys
              readOnly: true
            - name: data
              mountPath: /var/mail
            - name: state
              mountPath: /var/mail-state
      volumes:
        - name: config
          configMap:
            name: mailserver.config
        - name: opendkim-keys
          secret:
            secretName: mailserver.opendkim.keys
        - name: data
          persistentVolumeClaim:
            claimName: mail-data
        - name: state
          persistentVolumeClaim:
            claimName: mail-state
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mail-data
  namespace: mail
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: local-nfs
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mail-state
  namespace: mail
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: local-nfs

```
