### ISSUE TITLE
Why SYS_PTRACE capabilty ?

### ISSUE THREAD

**Issue by adlp** [tomav/docker-mailserver#1057]
I don't want to give too much capability ! :)

## Context
While reading the docker-compose.yml, I see the need of some capability, NET_ADMIN and SYS_PTRACE.
Ok for NET_ADMIN (needed for fail2ban) But why SYS_PTRACE ?

## Expected Behavior
A container with not too much capability :)

## Possible Fix
Only Documentation, and maybe an explanation of each capability ?

Thanks !

**Comment by johansmitsnl** [comment]
@adlp it was added in this commit: https://github.com/tomav/docker-mailserver/commit/420e7741a16b1de617611f95aca73a1088214e59

**Comment by jirislav** [comment]
> @adlp it was added in this commit: [420e774](https://github.com/tomav/docker-mailserver/commit/420e7741a16b1de617611f95aca73a1088214e59)

I've browsed through the commit and I've found **no reason** to allow the docker to have **PTRACE** capability. It was probably added because of testing.

The vulnerability exploited by `SYS_PTRACE` is the ability to skip the seccomp check as noted in [this paper](https://www.nccgroup.trust/globalassets/our-research/us/whitepapers/2016/june/container_whitepaper.pdf) (See the *ptrace(2) hole* section):

> The seccomp check will not be run again after the tracer is notified.  (This means that seccomp-based sandboxes MUST NOT allow use of ptrace, even of other sandboxed processes, without extreme care; ptracers can use this mechanism to escape.)

### IMO this is great security issue and the SYS_PTRACE should be disabled.

**Comment by adlp** [comment]
@jirislav, yes it's exactly my opinion, but I haven't take the time to come back with a full test.
In one week I will be able to test it not before :/
Thanks a lot, I feel less crazy now :)

**Comment by jirislav** [comment]
> @jirislav, yes it's exactly my opinion, but I haven't take the time to come back with a full test.
> In one week I will be able to test it not before :/

I'm already testing this on my production mailserver and I see no drawbacks yet.

Btw I wonder if you wanted to take a look at more hardened `docker-compose.yml` I've come up with and successfully tested on production environment. (Inspired by [CIS Docker Benchmark](https://blogs.tunelko.com/wp-content/uploads/2017/08/CIS_Docker_1.13.0_Benchmark_v1.0.0.pdf))
```yml
version: '2.1'
services:
  mail:
    image: tvial/docker-mailserver:stable
    # There is too many subsystems bundled ... also dynamically configuring using sed, bash, etc ...
    # So we can't run this container in read-only mode :/
    read_only: false
    mem_limit: 600m
    # Use 50% CPU at most
    cpu_shares: 512
    # 50 PIDs is normal ..
    pids_limit: 200
    ports:
    - "25:25"
    - "143:143"
    - "465:465"
    - "587:587"
    - "993:993"
    - "4190:4190"
    volumes:
    - maildata:/var/mail
    - mailstate:/var/mail-state
    - ./startup-config/:/tmp/docker-mailserver/
    # Can't mount this because it would overlay already configured image contents
    #- ./postfix:/etc/postfix
    #- ./dovecot:/etc/dovecot
#    cap_add:
    # NET_ADMIN required only because of iptables for Fail2Ban within the container.
    # As long as I use only one instance of Fail2Ban (from the host, this may be disabled.)
    # - NET_ADMIN
    # The seccomp check will not be run again after the tracer is notified. 
    # (This means that seccomp-based sandboxes MUST NOT allow use of ptrace, even of other sandboxed processes, without extreme care; ptracers can use this mechanism to escape.)
    # - SYS_PTRACE
    cap_drop:
    # Finally, the setfcap capability allows you to set file capabilities on a file system.
    # Might be needed for doing installs during builds, but in production it should probably be dropped.
    - SETFCAP
    # Let’s look at the man page description: “Add any capability from the calling thread’s bounding set to its inheritable set; drop capabilities from the bounding set (via prctl(2) PR_CAPBSET_DROP); 
    # make changes to the securebits flags.”
    #
    # In layman’s terms, a process with this capability can change its current capability set within its bounding set. 
    # Meaning a process could drop capabilities or add capabilities if it did not currently have them, but limited by the bounding set capabilities.
    - SETPCAP
    # This allows your processes to create device nodes. 
    # Containers are usually provided all of the device nodes they need in /dev, the creation of device nodes is controlled by the device node cgroup, 
    # but I really think this should be dropped by default. Almost no containers ever do this, and even fewer containers should do this.
    - MKNOD
    # If you have this one, you can write a message to kernel auditing log. 
    # Few processes attempt to write to the audit log (login programs, su, sudo) and processes inside of the container are probably not trusted. 
    # The audit subsystem is not currently namespace aware, so this should be dropped by default.
    - AUDIT_WRITE
    restart: always
volumes:
  maildata:
    driver: local
  mailstate:
    driver: local
```

**Comment by jirislav** [comment]
How would you like the `docker-compose.yml` to look in the PR? What about this?
```yml
version: '2.1'
services:
  mail:
    image: tvial/docker-mailserver:stable
    mem_limit: 600m
    # Uncomment to restrict the CPU usage by the mailserver up to 50%
    #cpu_shares: 512
    pids_limit: 200
    ports:
    - "25:25"
    - "143:143"
    - "465:465"
    - "587:587"
    - "993:993"
    - "4190:4190"
    volumes:
    - maildata:/var/mail
    - mailstate:/var/mail-state
    - ./startup-config/:/tmp/docker-mailserver/
    cap_add:
    # NET_ADMIN required only because of iptables for Fail2Ban within the container.
    # If you already use Fail2Ban on your host, consider adding rules for logs of this container and removing this capability
    - NET_ADMIN
    cap_drop:
    # Finally, the setfcap capability allows you to set file capabilities on a file system.
    # Might be needed for doing installs during builds, but in production it should probably be dropped.
    - SETFCAP
    # Let’s look at the man page description: “Add any capability from the calling thread’s bounding set to its inheritable set; drop capabilities from the bounding set (via prctl(2) PR_CAPBSET_DROP); 
    # make changes to the securebits flags.”
    #
    # In layman’s terms, a process with this capability can change its current capability set within its bounding set. 
    # Meaning a process could drop capabilities or add capabilities if it did not currently have them, but limited by the bounding set capabilities.
    - SETPCAP
    # This allows your processes to create device nodes. 
    # Containers are usually provided all of the device nodes they need in /dev, the creation of device nodes is controlled by the device node cgroup, 
    # but I really think this should be dropped by default. Almost no containers ever do this, and even fewer containers should do this.
    - MKNOD
    # If you have this one, you can write a message to kernel auditing log. 
    # Few processes attempt to write to the audit log (login programs, su, sudo) and processes inside of the container are probably not trusted. 
    # The audit subsystem is not currently namespace aware, so this should be dropped by default.
    - AUDIT_WRITE
    restart: always
volumes:
  maildata:
    driver: local
  mailstate:
    driver: local
```
