### ISSUE TITLE
Gmail only 550-5.7.1 this message does not have authentication information or fails to pass authentication checks

### ISSUE THREAD

**Issue by voordev** [tomav/docker-mailserver#1137]
## Context
Mailserver with SPF records added, with SPF config added.
Works fine on all domains except gmail.com => mails get returned with Gmail only 550-5.7.1 this message does not have authentication information or fails to pass authentication checks

## Expected Behavior
Mail should get delivered to gmail account.

## Actual Behavior
Gmail only 550-5.7.1 this message does not have authentication information or fails to pass authentication checks

## Steps to Reproduce
```
version: '2'
services:
  mail:
    image: tvial/docker-mailserver:latest
    hostname: mail
    domainname: domain.ltd
    container_name: mail
    ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
    volumes:
      - ./mail/data/mail:/var/mail
      - ./mail/data/mail-state:/var/mail-state
      - ./mail/config/:/tmp/docker-mailserver/
      - /server/letsencrypt/etc:/etc/letsencrypt/live
      - /server/mailserver/var/mail:/var/mail
      - ./config/postfix-policyd-spf.conf:/etc/postfix-policyd-spf-python/policyd-spf.conf
    environment:
    - ENABLE_SPAMASSASSIN=1
    - ENABLE_CLAMAV=0
    - ENABLE_FAIL2BAN=1
    - ENABLE_POSTGREY=1
    - ONE_DIR=1
    - DMS_DEBUG=0
    #- DMS_DEBUG=1
    #- ENABLE_CLAMAV=1
    #- ONE_DIR=${ONE_DIR}
    #- ENABLE_POP3=${ENABLE_POP3}
    #- ENABLE_FAIL2BAN=${ENABLE_FAIL2BAN}
    #- ENABLE_MANAGESIEVE=${ENABLE_MANAGESIEVE}
    #- OVERRIDE_HOSTNAME=${OVERRIDE_HOSTNAME}
    #- POSTMASTER_ADDRESS=${POSTMASTER_ADDRESS}
    #- POSTSCREEN_ACTION=${POSTSCREEN_ACTION}
    #- REPORT_RECIPIENT=${REPORT_RECIPIENT}
    #- REPORT_SENDER=${REPORT_SENDER}
    #- REPORT_INTERVAL=${REPORT_INTERVAL}
    #- SMTP_ONLY=${SMTP_ONLY}
    - SSL_TYPE=letsencrypt
    - TLS_LEVEL=intermediate
    #- SPOOF_PROTECTION=${SPOOF_PROTECTION}
    #- ENABLE_SRS=${ENABLE_SRS}
    #- PERMIT_DOCKER=${PERMIT_DOCKER}
    #- VIRUSMAILS_DELETE_DELAY=${VIRUSMAILS_DELETE_DELAY}
    #- ENABLE_POSTFIX_VIRTUAL_TRANSPORT=${ENABLE_POSTFIX_VIRTUAL_TRANSPORT}
    #- POSTFIX_DAGENT=${POSTFIX_DAGENT}
    #- POSTFIX_MAILBOX_SIZE_LIMIT=${POSTFIX_MAILBOX_SIZE_LIMIT}
    #- POSTFIX_MESSAGE_SIZE_LIMIT=${POSTFIX_MESSAGE_SIZE_LIMIT}
    #- ENABLE_SPAMASSASSIN=${ENABLE_SPAMASSASSIN}
    #- SA_TAG=${SA_TAG}
    #- SA_TAG2=${SA_TAG2}
    #- SA_KILL=${SA_KILL}
    #- SA_SPAM_SUBJECT=${SA_SPAM_SUBJECT}
    #- ENABLE_FETCHMAIL=${ENABLE_FETCHMAIL}
    #- FETCHMAIL_POLL=${FETCHMAIL_POLL}
    #- ENABLE_LDAP=${ENABLE_LDAP}
    #- LDAP_START_TLS=${LDAP_START_TLS}
    #- LDAP_SERVER_HOST=${LDAP_SERVER_HOST}
    #- LDAP_SEARCH_BASE=${LDAP_SEARCH_BASE}
    #- LDAP_BIND_DN=${LDAP_BIND_DN}
    #- LDAP_BIND_PW=${LDAP_BIND_PW}
    #- LDAP_QUERY_FILTER_USER=${LDAP_QUERY_FILTER_USER}
    #- LDAP_QUERY_FILTER_GROUP=${LDAP_QUERY_FILTER_GROUP}
    #- LDAP_QUERY_FILTER_ALIAS=${LDAP_QUERY_FILTER_ALIAS}
    #- LDAP_QUERY_FILTER_DOMAIN=${LDAP_QUERY_FILTER_DOMAIN}
    #- DOVECOT_TLS=${DOVECOT_TLS}
    #- DOVECOT_USER_FILTER=${DOVECOT_USER_FILTER}
    #- DOVECOT_PASS_FILTER=${DOVECOT_PASS_FILTER}
    #- ENABLE_POSTGREY=${ENABLE_POSTGREY}
    #- POSTGREY_DELAY=${POSTGREY_DELAY}
    #- POSTGREY_MAX_AGE=${POSTGREY_MAX_AGE}
    #- POSTGREY_AUTO_WHITELIST_CLIENTS=${POSTGREY_AUTO_WHITELIST_CLIENTS}
    #- POSTGREY_TEXT=${POSTGREY_TEXT}
    #- ENABLE_SASLAUTHD=${ENABLE_SASLAUTHD}
    #- SASLAUTHD_MECHANISMS=${SASLAUTHD_MECHANISMS}
    #- SASLAUTHD_MECH_OPTIONS=${SASLAUTHD_MECH_OPTIONS}
    #- SASLAUTHD_LDAP_SERVER=${SASLAUTHD_LDAP_SERVER}
    #- SASLAUTHD_LDAP_SSL=${SASLAUTHD_LDAP_SSL}
    #- SASLAUTHD_LDAP_BIND_DN=${SASLAUTHD_LDAP_BIND_DN}
    #- SASLAUTHD_LDAP_PASSWORD=${SASLAUTHD_LDAP_PASSWORD}
    #- SASLAUTHD_LDAP_SEARCH_BASE=${SASLAUTHD_LDAP_SEARCH_BASE}
    #- SASLAUTHD_LDAP_FILTER=${SASLAUTHD_LDAP_FILTER}
    #- SASLAUTHD_LDAP_START_TLS=${SASLAUTHD_LDAP_START_TLS}
    #- SASLAUTHD_LDAP_TLS_CHECK_PEER=${SASLAUTHD_LDAP_TLS_CHECK_PEER}
    #- SASL_PASSWD=${SASL_PASSWD}
    #- SRS_EXCLUDE_DOMAINS=${SRS_EXCLUDE_DOMAINS}
    #- SRS_SECRET=${SRS_SECRET}
    #- DEFAULT_RELAY_HOST=${DEFAULT_RELAY_HOST}
    #- RELAY_HOST=${RELAY_HOST}
    #- RELAY_PORT=${RELAY_PORT}
    #- RELAY_USER=${RELAY_USER}
    #- RELAY_PASSWORD=${RELAY_PASSWORD}
    cap_add:
    - NET_ADMIN
    - SYS_PTRACE
    restart: always
volumes:
  maildata:
    driver: local
  mailstate:
    driver: local
```

postfix-policyd-spf.conf
```
debugLevel = 1
#0(only errors)-4(complete data received)
skip_addresses = 127.0.0.0/8,::ffff:127.0.0.0/104,::1
# Preferably use IP-Addresses for whitelist lookups:
Whitelist = 192.168.0.0/31,192.168.1.0/30
# Domain_Whitelist = mx1.mybackupmx.com,mx2.mybackupmx.com

```

DOMAIN SPF records tested online:
```
v=spf1 ip4:<my_ip> ~all
```

How to resolve this?
