### ISSUE TITLE
LE SSL working with IMAP, but not SMTP

### ISSUE THREAD

**Issue by mgansler** [tomav/docker-mailserver#117]
I'm a bit confused right now, because the container is using the correct certificate for IMAP, but the self signed one for SMPT:

```
$ docker exec mail_mail_1 openssl s_client -connect 0.0.0.0:143 -starttls imap -CApath /etc/ssl/certs/
---
Certificate chain
 0 s:/CN=mail.MYDOMAIN.de
   i:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
 1 s:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
   i:/O=Digital Signature Trust Co./CN=DST Root CA X3
---
```

```
$ docker exec mail_mail_1 openssl s_client -connect 0.0.0.0:25 -starttls smtp
---
Certificate chain
 0 s:/CN=f5ee59d47428
   i:/CN=f5ee59d47428
---
```

My docker-compose looks like this:
```
mail:
  image: tvial/docker-mailserver
  hostname: mail
  domainname: MYDOMAIN.de
  cap_add:
    - NET_ADMIN
  environment:
    - DMS_SSL=letsencrypt
  ports:
  - "25:25"
  - "143:143"
  - "587:587"
  - "993:993"
  volumes:
  - ./spamassassin:/tmp/spamassassin/
  - ./postfix:/tmp/postfix/
  - ./mail:/var/mail
  - /etc/letsencrypt:/etc/letsencrypt
```

What did I miss?
