### ISSUE TITLE
Kubernetes with PROXY does not save E-Mail

### ISSUE THREAD

**Issue by mishushakov** [tomav/docker-mailserver#1192]
## Context
Hi,
i'm running docker-mailserver on Kubernetes. It's been pretty awesome and very easy to set up. Huge thanks for all of that!

However, after enabling the PROXY protocol on my LoadBalancer, i encountered an issue and i could no longer receive E-Mails:

`Blocked MTA-Blocked {TempFailedOpenRelay}`

`Temporary MTA failure on relaying, From MTA() during fwd-connect (Negative greeting at (eval 134) line 479.): id=0090301 (in reply to end of DATA command))`

## Steps to Reproduce

1. Create new user and alias
2. Configure Proxy protocol according to the Wiki: https://github.com/tomav/docker-mailserver/wiki/Using-in-Kubernetes#proxy-port-to-service-via-proxy-protocol
3. Send E-Mail to the alias
4. See the issue with your own eyes

## Your Environment
DigitalOcean Kubernetes + LoadBalancer with PROXY Protocol Enabled
The PROXY protocol is enabled in mail-server configuration, like described in the Documentation and works properly (does forward original IPs)
User with alias

Thank you!

**Comment by flanfly** [comment]
Hey,

I had the same problem. As far as I understand it amavis puts processed mail back into the postfix queue by sending it to the postfix smtpd using plain SMTP. We configured to daemon to expect proxy protocol connections only so this fails. I fixed that by leaving out the global `smptd_upstream_proxy_protocol = haproxy` and enable it only for the submission service by adding `submission/inet/smtpd_upstream_proxy_protocol=haproxy` to `postfix-master.cf`.

**Comment by mishushakov** [comment]
Hello @flanfly,
thanks for your response. So, yes it seems like it is trying to forward the mail using SMTP protocol, but the postfix expects PROXY.

`submission/inet/smtpd_upstream_proxy_protocol=haproxy`

Do you have an example how it could look in yaml? Like this?

```yaml
kind: ConfigMap
apiVersion: v1
metadata:
  name: mailserver.config
  labels:
    app: mailserver
data:
  postfix-master: |
    submission/inet/smtpd_upstream_proxy_protocol=haproxy
  postfix-main: |
    postscreen_upstream_proxy_protocol = haproxy
```

Would this be enough to get working? Thank you.
