### ISSUE TITLE
imap mail access

### ISSUE THREAD

**Issue by awb99** [tomav/docker-mailserver#125]
I have a container running;  and smtp sending works, but getting data via imap does not work. There are no folders displayed at  all. I just added the accounts.cf file .

My computer is: backoffice.newstrading.org[104.222.96.51]:
This is the log I get via  docker logs mymail_mail_1
http://pastebin.com/QXN3pwVW

I believe it misses all the imap log entries.

```
cat docker-compose.yml 

maildata:
  image: ubuntu
  volumes:
    - /var/mail
  command: /bin/true

mail:
  #restart: always
  #build: ./docker-mailserver
  image: tvial/docker-mailserver
  hostname: backoffice
  domainname: newstrading.org
  volumes_from:
   - maildata
  ports:
  - "25:25"
  - "143:143"
  - "587:587"
  - "993:993"
  volumes:
  - ./spamassassin:/tmp/spamassassin/
  - ./postfix:/tmp/postfix/
  environment:
  - ENABLE_POP3=1
```
