### ISSUE TITLE
Unable to receive mails

### ISSUE THREAD

**Issue by PfefferT** [tomav/docker-mailserver#1278]
Hello I have configured and installed docker-mailserver the last days. I am now able to send valid e-mails to gmail and other mail services. 
My problem now is that I cannot receive any. 
Neither local mails from postmaster@subdomain.domain.com to info@subdomain.domain.com nor from my gmail account to postmaster@subdomain.domain.com. 
I have disabled spamassassin, fail2ban, postgrey and clamav to ensure that no security mechanism is catching my mails.

I have not registered any aliases, because I don't need them at the moment.

here is my docker-compose.yml:

```
version: '2'

services:
  mail:
    image: tvial/docker-mailserver:latest
    hostname: subdomain
    domainname: domain.com
    container_name: mailserver
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
      - "465:465"
    volumes:
      - ./data:/var/mail
      - ./state:/var/mail-state
      - /var/log/mail:/var/log/mail
      - ./config/:/tmp/docker-mailserver/
      - /etc/letsencrypt:/etc/letsencrypt
    environment:
      - ENABLE_SPAMASSASSIN=0
      - ENABLE_CLAMAV=0
      - ENABLE_FAIL2BAN=0
      - ENABLE_POSTGREY=0
      - ONE_DIR=1
      - DMS_DEBUG=1
      - PERMIT_DOCKER=connected-networks
      - SPOOF_PROTECTION=1
      - SSL_TYPE=letsencrypt
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
volumes:
  maildata:
    driver: local
  mailstate:
    driver: local
  maillogs:
    driver: local
```

What could be the problem here ?

Thx for the help :-)
