### ISSUE TITLE
user table not recognized?

### ISSUE THREAD

**Issue by pfaffman** [tomav/docker-mailserver#1282]
I cranked up the container with Ansible like this:

```
- name: create mail container
  docker_container:
    name: mail
    image: tvial/docker-mailserver:latest
    restart_policy: unless-stopped
    domainname: mydomain.com
    ports:
      - "110:110"
      - "143:143"
      - "25:25"
      - "587:587"
      - "993:993"
      - "995:995"
      - '465:465'
    volumes:
      - "{{data_dir}}/mail:/var/mail"
      - "{{data_dir}}/mail-state:/var/mail-state"
      - "{{data_dir}}/maillogs:/var/log/mail"
      - "{{data_dir}}/config:/tmp/docker-mailserver"
    networks:
      - name: monitoring
      - name: web
    env:
      # password ignored after first run
      OVERRIDE_HOSTNAME: "{{mail_domainname}}"
      DMS_DEBUG: "1"
      ENABLE_SPAMASSASSIN: "1"
      ENABLE_CLAMAV: "1"
      ENABLE_FAIL2BAN: "1"
      ENABLE_POSTGREY: "1"
      ONE_DIR: "1"
      DMS_DEBUG: "0"
      ENABLE_LDAP: "0"
      POSTMASTER_ADDRESS: "postmaster@mydomain.com"
      ENABLE_POSTFIX_VIRTUAL_TRANSPORT: "1"
      POSTFIX_DAGENT: "lmtp:unix:private/dovecot-lmtp"
      POSTFIX_MESSAGE_SIZE_LIMIT: "100000000"
```
and added a user with `./setup`. I see that the user is in `config/postfix-accounts.cf`
```
config/postfix-accounts.cf:pfaffman@mydomain.com|{SHA512-CRYPT}$6$udwiiPuq8cTt....../wnS97QF7VIJtQAiOVLyS0

## Context
<!--- Provide a more detailed introduction to the issue itself -->
<!--- How has this issue affected you? What were you trying to accomplish? -->

Mail to that user bounces with 
```
Oct  3 19:19:33 7efd65b2728b postfix/smtpd[6226]: NOQUEUE: reject: RCPT from mail-wr1-f54.google.com[209.85.221.54]: 550 5.1.1 <jay@mydomain.com>: Recipient address rejected: User unknown in local recipient table; from=<jay@sendingdomain.com> to=<jay@mydomain.com> proto=ESMTP helo=<mail-wr1-f54.google.com>

```

## Expected Behavior
<!--- Tell us what should happen -->

Mail could get delivered

## Your Environment
<!--- Include as many relevant details about the environment you experienced the issue in -->
* Amount of RAM available: 16GB
* Mailserver version used: latest
* Docker version used: 19.03.2
* Environment settings relevant to the config:
* Any relevant stack traces ("Full trace" preferred):

<!--- Please remember to format code using triple backticks (`)
	  so that it is neatly formatted when the issue is posted. -->


<!---
## Possible answers to you issue
* ClamAV keeps restarting:
  https://github.com/tomav/docker-mailserver#requirements

* Email seen as spam:
  https://github.com/tomav/docker-mailserver/wiki/Configure-SPF
  https://github.com/tomav/docker-mailserver/wiki/Configure-DKIM

* Creating new domains and accounts
  https://github.com/tomav/docker-mailserver/wiki/Configure-Accounts

* Use a relay mail server
  https://github.com/tomav/docker-mailserver/wiki/Configure-AWS-SES
  The variable name can be used for other email servers.

* FAQ and tips
  https://github.com/tomav/docker-mailserver/wiki/FAQ-and-Tips

* And the WIKI
  https://github.com/tomav/docker-mailserver/wiki

* Open issues
  https://github.com/tomav/docker-mailserver/issues
-->
