### ISSUE TITLE
Error: The directory named as part of the path /var/log/supervisor/supervisord.log does not exist.

### ISSUE THREAD

**Issue by Yajo** [tomav/docker-mailserver#1352]
## Context

Just starting the server.

## Expected Behavior

Boot.

## Actual Behavior

Doesn't boot. Logs this repeatedly:

```
Error: The directory named as part of the path /var/log/supervisor/supervisord.log does not exist.
For help, use /usr/bin/supervisord -h
```

## Possible Fix

Add `-v maillogssupervisor:/var/log/supervisor:z` to `docker container run` command. Well, this is a workaround; the fix should be doing `mkdir -p /var/log/supervisor` in the entrypoint.

## Steps to Reproduce

1. Start server.

## Your Environment

* Amount of RAM available: 64GiB
* Mailserver version used: v6.1.0-204-gf69d30f
* Docker version used: 18.09.6
* Environment settings relevant to the config: 

```yaml
# docker-compose.yml, with only interesting things
  smtp:
    cap_add:
    - SYS_PTRACE
    domainname: eurosas.net
    environment:
      DEFAULT_RELAY_HOST: '[smtp.gmail.com]:587'
      DMS_DEBUG: 0
      ENABLE_SRS: 1
      ONE_DIR: 1
      PERMIT_DOCKER: connected-networks
      POSTFIX_MESSAGE_SIZE_LIMIT: 52428800
      RELAY_HOST: smtp.gmail.com
      RELAY_PASSWORD: *********
      RELAY_PORT: '587'
      RELAY_USER: **********
      SMTP_ONLY: 1
      SRS_DOMAINNAME: **********
      SRS_EXCLUDE_DOMAINS: **********
      SRS_SENDER_CLASSES: envelope_sender,header_sender
    image: tvial/docker-mailserver:latest
    networks:
      default:
        aliases:
        - smtplocal
    restart: unless-stopped
    stop_grace_period: 1m
    volumes:
    - mailconfig:/tmp/docker-mailserver:z
    - maillogs:/var/log/mail:z
    - maildata:/var/mail:z
    - mailstate:/var/mail-state:z
```

* Any relevant stack traces ("Full trace" preferred):
See above.
