### ISSUE TITLE
ClamAV gets Permission Denied on fresh install

### ISSUE THREAD

**Issue by Oznup** [tomav/docker-mailserver#1353]
## Context 
Hello, I have made a fresh install of this wonderful docker mailserver on a Kubernetes cluster, everything was fine until I turn on ClamAV. (ENABLE_CLAMAV=1).

## Expected Behavior
ClamAV should be able to analyze the emails without permission problems

## Actual Behavior
When I send an e-mail, I can see the following lines in the logs :
> Jan  3 14:41:15 mailserver-98d4ff8b5-7mdbf amavis[2074]: (02074-01) (!)run_av (ClamAV-clamd) FAILED - unexpected , output="/var/lib/amavis/tmp/amavis-20200103T144115-02074-u7EETtwj/parts: lstat() failed: Permission denied. ERROR\n"
> Jan  3 14:41:15 mailserver-98d4ff8b5-7mdbf amavis[2074]: (02074-01) (!)ClamAV-clamd av-scanner FAILED: CODE(0x555f4a97ab00) unexpected , output="/var/lib/amavis/tmp/amavis-20200103T144115-02074-u7EETtwj/parts: lstat() failed: Permission denied. ERROR\n" at (eval 97) line 905.
> Jan  3 14:41:15 mailserver-98d4ff8b5-7mdbf amavis[2074]: (02074-01) (!)WARN: all primary virus scanners failed, considering backups

And when I do ls -al /var/lib/amavis/tmp/, I get this :
> drwxr-x--- 4 amavis amavis 4096 Jan  3 13:57 .
> drwxrwx--- 8 amavis amavis 4096 Jan  3 14:02 ..
> drwxr-x--- 3 amavis amavis 4096 Jan  3 13:54 amavis-20200103T135427-03471-hZa4ayDp
> drwxr-x--- 3 amavis amavis 4096 Jan  3 13:56 amavis-20200103T135654-03470-3AUK9KTg

The clamav user is in the amavis group, and vice versa (this is the solution suggested by all the posts I've read until now), and I don't know why it doesn't work, excepted that the folders in the /var/lib/amavis/tmp/ repository are in 750 instead of 770 ?

I've tried with an external volume and inside the container, the issue is the same.
It's really close to this issue : https://github.com/tomav/docker-mailserver/issues/1308, but I didn't find any fix in it although it's closed.
Can someone help me ?

## Steps to Reproduce
1. Install it
2. Send a mail from an user to himself, for example

## Your Environment
* Amount of RAM available: 8 GB
* Mailserver version used: latest
* Docker version used: Embedded in K3s 1.16

**Comment by erik-wramner** [comment]
https://www.moshe-schmidt.de/linux/clamav-permission-denied-how-to-fix-it covers several alternatives, including permission 770. However, I have 750 just like you and I don't get those errors. I don't have AllowSupplementaryGroups at all and I haven't touched the groups. It is probably related to Kubernetes in some way, the question is how.

**Comment by Oznup** [comment]
Thanks for your answer.
I have already tried the fixes in this page, but it has not been enough to get rid of it.
Then I've tried something else, and indeed it came from my configuration.
I **deleted** the image and pull it again without mapping external volumes, it worked.
I **restarted** it with my **configuration** in **external volumes**, the problem **came back**.
I restarted it **without mapping the /var/mail-state** folder, the problem is **gone**.
I cleaned the **mail-state mapped folder** and restarted the app, the problem **came back**.
I don't know why it matters whether the **/var/mail-state** is mapped or not...

**Comment by erik-wramner** [comment]
How have you defined `ONE_DIR`? With `ONE_DIR=0` the amavis state directory is `/var/lib/amavis`, with 1 it is `/var/mail-state/lib-amavis` and `/var/lib/amavis` is just a soft link to `/var/mail-state/lib-amavis` in the mapped folder.

**Comment by erik-wramner** [comment]
@Oznup? Do you want to close the issue, or shall we investigate more? In the latter case, how are you using `ONE_DIR`?

**Comment by Oznup** [comment]
Hello, sorry for my late answer,
I user ONE_DIR and it's et to 1. Do I have to change it to 0 ?

**Comment by erik-wramner** [comment]
No, it is fine. Just wanted to know your config. I think (not surprising) the problem is with the mounted volume. With `ONE_DIR` the mail state is kept in the mounted volume and `/var/lib/amavis` is just a soft-link. That means any permission issues with Kubernetes mounted volumes can hit you. That makes it a bit hard to reproduce, I'll try to think of something.

**Comment by aendeavor** [comment]
This issue was closed due to one or more of the following reasons:

1. Age
2. Contributor inactivity
3. The issue seems to be resolved

If you think this happened by accident, or feel like this issue was not actually resolved, please feel free to re-open it. If there is an issue you could resolve in the meantime, please open a PR based on the current master branch so we can review it.

**Comment by starfoxx82** [comment]
Hi, 
i have the same problem. I get:

> run_av (ClamAV-clamd) FAILED - unexpected , output="/var/lib/amavis/tmp/amavis-20201117T091752-00289-lTvNEEz7/parts: lstat() failed: Permission denied. ERROR\n"
> amavis[289]: (00289-01) (!)ClamAV-clamd av-scanner FAILED: CODE(0x55dda70f2a50) unexpected , output="/var/lib/amavis/tmp/amavis-20201117T091752-00289-lTvNEEz7/parts: lstat() failed: Permission denied. ERROR\n" at (eval 98) line 951.
> amavis[289]: (00289-01) (!)WARN: all primary virus scanners failed, considering backups

in my mail.log 

# Environment: 
A kubernetes Cluster with an NFS pv

## pv.yaml
```
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mail-storage
  labels:
    type: local
  namespace: mailserver
spec:
  storageClassName: manual
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: xxx.xxx.xxx.xxx
    path: "/srv/nfs/kubedata/smtp/mail-storage"
```

## pvc.yaml
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mail-storage-claim
  namespace: mailserver
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
```

## configmap.yaml

```
data:
  ONE_DIR: "1"
```




## deployment.yaml
```
          - name: data
            mountPath: /var/mail
            subPath: data
          - name: data
            mountPath: /var/mail-state
            subPath: state
          - name: data
            mountPath: /var/log/mail
            subPath: log

        - name: data
          persistentVolumeClaim:
            claimName: mail-storage-claim
```


## NFS

And when I do ls -aln /var/lib/amavis/tmp/, I get this :
> drwxrwx--- 4 112 114 4096 Nov 17 10:21 .
> drwxr-x--- 8 112 114 4096 Nov 17 10:19 ..
> drwxr-x--- 3 112 114 4096 Nov 17 10:20 amavis-20201117T092012-00283-H7KnOmih
> drwxr-x--- 3 112 114 4096 Nov 17 10:21 amavis-20201117T092102-00282-5WnlwIhO
