### ISSUE TITLE
Logs are full of changedetector (exit status 0; expected)

### ISSUE THREAD

**Issue by Yajo** [tomav/docker-mailserver#1359]
## Context

This is almost a duplicate of #747; but I'm opening a new one as asked in https://github.com/tomav/docker-mailserver/issues/747#issuecomment-570647490

## Expected Behavior

Logs shouldn't be crazy. :yum: 

I don't have a `/tmp/docker-mailserver/postfix-accounts.cf` file because I'm only using the image as a relay.

## Actual Behavior

Logs are crazy, exactly as in #747:

## Possible Fix

I had to use this workaround to make the loop disappear:

```bash
docker-compose exec smtp touch /tmp/docker-mailserver/postfix-accounts.cf
```

## Steps to Reproduce

1. `docker-compose up -d` in a new project.

<details><summary>Relevant parts of `docker-compose.yml`</summary>

```yaml
services:
  smtp:
    cap_add:
    - SYS_PTRACE
    domainname: example.net
    environment:
      DEFAULT_RELAY_HOST: '[smtp.gmail.com]:587'
      DMS_DEBUG: 0
      ENABLE_SRS: 1
      ONE_DIR: 1
      PERMIT_DOCKER: connected-networks
      POSTFIX_MESSAGE_SIZE_LIMIT: 52428800
      RELAY_HOST: smtp.gmail.com
      RELAY_PASSWORD: hidden
      RELAY_PORT: '587'
      RELAY_USER: hidden
      SMTP_ONLY: 1
      SRS_DOMAINNAME: example.net
      SRS_EXCLUDE_DOMAINS: example.net,example.com
      SRS_SENDER_CLASSES: envelope_sender,header_sender
    image: tvial/docker-mailserver:latest
    networks:
      default:
        aliases:
        - smtplocal
    restart: unless-stopped
    stop_grace_period: 1m
    volumes:
    - mailconfig:/tmp/docker-mailserver:z
    - maillogs:/var/log/mail:z
    - maillogssupervisord:/var/log/supervisor:z # Workaround for #1352
    - maildata:/var/mail:z
    - mailstate:/var/mail-state:z
version: '2.4'
volumes:
  mailconfig: {}
  maildata: {}
  maillogs: {}
  maillogssupervisord: {}
  mailstate: {}
```

</details>

## Your Environment

* Amount of RAM available: 64G.
* Mailserver version used: v6.1.0-204-gf69d30f
* Docker version used: Docker version 18.09.6, build 481bc77
* Environment settings relevant to the config: See relevant parts of `docker-compose.yml` above.
* Any relevant stack traces ("Full trace" preferred):

```
smtp_1    | 2020-01-03 13:47:08,709 INFO success: changedetector entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
smtp_1    | 2020-01-03 13:47:08,712 INFO exited: changedetector (exit status 0; expected)                                                     
smtp_1    | 2020-01-03 13:47:08,713 INFO spawned: 'changedetector' with pid 288                                                               
smtp_1    | 2020-01-03 13:47:08,716 INFO success: changedetector entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
smtp_1    | 2020-01-03 13:47:08,716 INFO exited: changedetector (exit status 0; expected)                                                     
smtp_1    | 2020-01-03 13:47:08,717 INFO spawned: 'changedetector' with pid 290                                                               
smtp_1    | 2020-01-03 13:47:08,720 INFO success: changedetector entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)                                                                                                                                                                                
smtp_1    | 2020-01-03 13:47:08,720 INFO exited: changedetector (exit status 0; expected)                                                     
smtp_1    | 2020-01-03 13:47:08,721 INFO spawned: 'changedetector' with pid 292                                                               

... etc
```

@Tecnativa TT21161
