### ISSUE TITLE
Multiple mail domains (RFE)

### ISSUE THREAD

**Issue by Thorsten1976** [tomav/docker-mailserver#1361]
Is it possible that multiple mail domains can be used (similar to mailcow).
In .env it is only possible to configure one hostname.

**Comment by erik-wramner** [comment]
That is quite common. You are confusing mail server with domain. A mail server runs on a host and can serve any number of domains. The DNS MX records for a domain point to hosts that handle e-mail for the domain. Those hosts do not need to belong to the domain.

In other words domain1.com and domain2.com can both have MX records pointing to mailhost.otherdomain.com. The fully qualified host name is mailhost.otherdomain.com and the domains are domain1.com and domain2.com with e-mail accounts like someone@domain1.com and someone.else@domain2.com.

**Comment by tomav** [comment]
@erik-wramner is correct, you're mixing FQDN and virtual domains.

**Comment by rafipiccolo** [comment]
Sorry for the noob question but could you please provide an example of a working docker compose allowing multiple domain emails ?
Eg email sent to theses adresses should be received by this docker image : test@example.fr and test@example.com and test@other.com...

I already linked all MX of those 3 domains to the host mail.example.com.

I found this compose in the documentation :
Should I replace domainname by two values like so ?
Domainname : example.fr,example.com
Or just use mail.example.com here ?

Do I need to edit manually files inside the container ?


```

version: '3.8'
services:
  mail:
    image: tvial/docker-mailserver:stable
    hostname: mail
    domainname: example.com
    volumes:
    - /etc/ssl/acme-v2.json:/etc/letsencrypt/acme.json:ro
    environment:
      SSL_TYPE: letsencrypt
      # SSL_DOMAIN: "*.example.com" 
  traefik:
    image: traefik:v2.2
    restart: always
    ports:
    - "80:80"
    - "443:443"
    command:
    - --providers.docker
    - --entrypoints.web.address=:80
    - --entrypoints.web.http.redirections.entryPoint.to=websecure
    - --entrypoints.web.http.redirections.entryPoint.scheme=https
    - --entrypoints.websecure.address=:443
    - --entrypoints.websecure.http.middlewares=hsts@docker
    - --entrypoints.websecure.http.tls.certResolver=le
    - --certificatesresolvers.le.acme.email=admin@example.net
    - --certificatesresolvers.le.acme.storage=/acme.json
    - --certificatesresolvers.le.acme.httpchallenge.entrypoint=web
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock:ro
    - /etc/ssl/acme-v2.json:/acme.json

  whoami:
    image: containous/whoami
    labels:
    - "traefik.http.routers.whoami.rule=Host(`mail.example.com`)"
```
