### ISSUE TITLE
user-patches.sh has an issue with kubernetes volumes?

### ISSUE THREAD

**Issue by remoe** [tomav/docker-mailserver#1383]
## Context
start-mailserver.sh try to change the file permissions here:
https://github.com/tomav/docker-mailserver/blob/2a6d8ca6fadcdd2d7a0f89e9d2080e12caa7a29b/target/start-mailserver.sh#L1514

this is not allowed with a readonly configmap

## Expected Behavior
The ```user-patches.sh``` script should run with a readonly mount

## Actual Behavior
The ```user-patches.sh``` script doesn't execute.

## Possible Fix
one can add the following to mailserver kubernetes container:
```yaml
        lifecycle:
          postStart:
            exec:
              command: ["/bin/sh", "-c", "cp /tmp/user-patches.sh /tmp/docker-mailserver;"]
        volumeMounts:
          - name: config
            subPath: user-patches.sh
            mountPath: /tmp/user-patches.sh
```

But this is a bit ugly. I think config files which will be changed later should be copy to a local folder?
