### ISSUE TITLE
fresh install: some vars in env files ignored 

### ISSUE THREAD

**Issue by hanscees** [tomav/docker-mailserver#1392]
## Context

I am freshly installing a new server. However, a few parts of the env-mailserver file I am trying to use seem to be ignored. sasl and tls and postmaster

This makes me wary on what other things are also wrong perhaps.

1- My tls configuration is not working. So I had to adjust by hand (see below).
2- I do not know if the sasl config breaks things. 
3- lot of errors since the postmaster address is not present in the config
 
## Expected Behavior

The mailserver should start with the appropriate variables as given in the env-mailserver.

## Actual Behavior

the postfix main.cf and master.cf doe not hold the right variables.

Here is the dir with the docker-compose.yml file:

```
root@mail [ ~/containers/base/tomavmail ]# ls -alll
-rw-r----- 1 root root  1279 Feb 10 22:18 docker-compose.yml
-rw-r----- 1 root root   445 Feb 10 14:52 .env
-rw-r----- 1 root root 15162 Feb 10 22:17 env-mailserver
-rwxr-x--x 1 root root  6433 Feb 10 14:50 setup.sh
```

Variables that are wrong for instance:

egrep "ssl|sasl" /var/lib/docker/volumes/tomavmail_etc/_data/postfix/main.cf

smtpd_tls_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem
smtpd_tls_key_file=/etc/ssl/private/ssl-cert-snakeoil.key

and also
# SASL
smtpd_sasl_auth_enable = yes
smtpd_sasl_path = /var/spool/postfix/private/auth
smtpd_sasl_type = dovecot

Below you can see how the variables in the env-mailserver file are different from those in main.cf

```
root@mail [ ~/containers/base/tomavmail ]# egrep -v "#" env-mailserver | egrep [A-Z]
OVERRIDE_HOSTNAME=
DMS_DEBUG=0
ONE_DIR=1
POSTMASTER_ADDRESS=root@hansbees.net
PERMIT_DOCKER=
TLS_LEVEL=
SPOOF_PROTECTION=1
ENABLE_SRS=0
ENABLE_POP3=1
ENABLE_CLAMAV=1
ENABLE_FAIL2BAN=1
ENABLE_MANAGESIEVE=
POSTSCREEN_ACTION=enforce
SMTP_ONLY=
SSL_TYPE=manual
VIRUSMAILS_DELETE_DELAY=
ENABLE_POSTFIX_VIRTUAL_TRANSPORT=
POSTFIX_DAGENT=
POSTFIX_MAILBOX_SIZE_LIMIT=
POSTFIX_MESSAGE_SIZE_LIMIT=60240000
REPORT_RECIPIENT=1
REPORT_SENDER=mailreport@hansbees.net
REPORT_INTERVAL=daily
ENABLE_SPAMASSASSIN=0
SA_TAG=2.0
SA_TAG2=6.31
SA_KILL=6.31
SA_SPAM_SUBJECT=***SPAM*****
ENABLE_FETCHMAIL=0
FETCHMAIL_POLL=300
ENABLE_LDAP=
LDAP_START_TLS=
LDAP_SERVER_HOST=
LDAP_SEARCH_BASE=
LDAP_BIND_DN=
LDAP_BIND_PW=
LDAP_QUERY_FILTER_USER=
LDAP_QUERY_FILTER_GROUP=
LDAP_QUERY_FILTER_ALIAS=
LDAP_QUERY_FILTER_DOMAIN=
DOVECOT_TLS=
DOVECOT_USER_FILTER=
DOVECOT_PASS_FILTER=
DOVECOT_MAILBOX_FORMAT=maildir
ENABLE_POSTGREY=1
POSTGREY_DELAY=300
POSTGREY_MAX_AGE=35
POSTGREY_TEXT=Delayed by postgrey
POSTGREY_AUTO_WHITELIST_CLIENTS=5
ENABLE_SASLAUTHD=0
and some more

```

## Steps to Reproduce

Perhaps this has to do with the volumes I have enabled, the variables in the yml file or some other logical error since some variables are in the yml file and others in the env-mailserver file? 

my yml file
```
version: '2'

services:
  mail:
    image: tvial/docker-mailserver:latest
    hostname: mail
    domainname: hansbees.net
    container_name: mail
    ports:
   #receiving email from other mailservers
    - "25:25"
     # SSL & TLS Client email submission (SMTP)
    - "465:465"
    - "587:587"
     # StartTLS & TLS/SSL IMAP client
    - "143:143"
    - "993:993"
     # POP3 & TLS/SSL POP3 client
    - "110:110"
    - "995:995"
     # Manage Sieve port
    - "4190:4190"
    volumes:
    - maildata:/var/mail
    - mailstate:/var/mail-state
    - Tconfig:/tmp/docker-mailserver/
    - etc:/etc
    - log:/var/log
    - ssl:/tmp/ssl:ro
    env_file:
    - .env
    - env-mailserver
    environment:
    - ENABLE_SPAMASSASSIN=1
    - ENABLE_CLAMAV=1
    - ENABLE_FAIL2BAN=1
    - ENABLE_POSTGREY=1
    - ONE_DIR=1
    - DMS_DEBUG=0
    - PFLOGSUMM_TRIGGER=daily_cron
    - LOGWATCH_INTERVAL=daily
    - LOGROTATE_INTERVAL=weekly
    - POSTMASTER_ADDRESS=root@hansbees.net
# If you need SSL connection, you can provide your own certificates
    - SSL_TYPE=manual
    - SSL_CERT_PATH=/tmp/ssl/fullchain.pem
    - SSL_KEY_PATH=/tmp/ssl/privkey.pem
    cap_add:
    - NET_ADMIN
    - SYS_PTRACE
    restart: always

volumes:
  maildata:
  mailstate:
  Tconfig:
  etc:
  log:
  ssl:


```

## Your Environment

* Amount of RAM available:
* Mailserver version used: latest
* Docker version used: Docker version 18.09.9, build 039a7df
* docker-compose: docker-compose version 1.25.3, build d4d1b42b
* Environment settings relevant to the config:
* Any relevant stack traces ("Full trace" preferred):
