### ISSUE TITLE
Can't start container after system upgrade due to permission error

### ISSUE THREAD

**Issue by oblitum** [tomav/docker-mailserver#1414]
## Context

Today I upgraded my host system (it's an Arch Linux on ARM64 RPi3), it upgraded the kernel (to 5.5.6) and other stuff, this generally has not been an issue at all, but today after that I couldn't start the docker-mailserver anymore, it exits with this error:

```
❯ sudo docker logs mail -f
Traceback (most recent call last):
  File "/usr/bin/supervisord", line 11, in <module>
    load_entry_point('supervisor==3.3.1', 'console_scripts', 'supervisord')()
  File "/usr/lib/python2.7/dist-packages/supervisor/supervisord.py", line 365, in main
    go(options)
  File "/usr/lib/python2.7/dist-packages/supervisor/supervisord.py", line 375, in go
    d.main()
  File "/usr/lib/python2.7/dist-packages/supervisor/supervisord.py", line 70, in main
    rlimit_messages = self.options.set_rlimits()
  File "/usr/lib/python2.7/dist-packages/supervisor/options.py", line 1372, in set_rlimits
    soft, hard = resource.getrlimit(res)
resource.error: (1, 'Operation not permitted')
```

I tried to add `- ALL`, `- SYS_RESOURCE`, etc to `cap_add` in `docker-compose.yml`, to check whether it was due to any new capability I needed to list, but it didn't help.

## Expected Behavior

The container to start.

## Actual Behavior

Container doesn't start due to permission error with `getrlimit` for `RLIMIT_NOFILE`.

## Steps to Reproduce

1. Have host system as Arch Linux on ARM
2. Upgrade
3. Run docker-mailserver built from master

## Your Environment

* Amount of RAM available: 1GB
* Mailserver version used: built from master
* Docker version used: 1:19.03.6-1
* Environment settings relevant to the config:
* Any relevant stack traces ("Full trace" preferred):

**Comment by oblitum** [comment]
Running the container with `privileged: true` avoids the issue. Should this be necessary now?

**Comment by erik-wramner** [comment]
Not always, but it might be necessary depending on your options. A quick search finds https://github.com/containers/libpod/issues/2123 with podman if you are using that.

I'm very much against running privileged (unless needed, for example by fail2ban) so if this needs changes I'm all for them. I'm running on a modern system without privileged though.

**Comment by oblitum** [comment]
I'm running docker.

**Comment by oblitum** [comment]
> Not always, but it might be necessary depending on your options

These are my settings:

```
version: "2"
services:
  mail:
    image: docker-mailserver:latest
    container_name: mail
    ports:
      - "25:25"
      - "465:465"
      - "587:587"
      - "143:143"
      - "993:993"
    volumes:
      - maildata:/var/mail
      - mailstate:/var/mail-state
      - maillogs:/var/log/mail
      - /etc/localtime:/etc/localtime:ro
      - /etc/letsencrypt/:/etc/letsencrypt/:ro
      - ./config/:/tmp/docker-mailserver/
    environment:
      - ONE_DIR=1
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=1
      - SPOOF_PROTECTION=1
      - SSL_TYPE=letsencrypt
      - ENABLE_SPAMASSASSIN=1
      - SA_SPAM_SUBJECT=[SPAM]
      - POSTFIX_MESSAGE_SIZE_LIMIT=51200000
      - OVERRIDE_HOSTNAME=mail.mydomain.com
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    dns:
      - "1.1.1.1"
      - "1.0.0.1"
    network_mode: "none"
    privileged: true
volumes:
  maildata:
    driver: local
  mailstate:
    driver: local
  maillogs:
    driver: local
```

I use `network_mode: "none"` because I set up a interface in the network namespace of the container for it alone, but I think this part is not relevant to the issue at hand.
