### ISSUE TITLE
Impossible to relay to port 465

### ISSUE THREAD

**Issue by Yajo** [tomav/docker-mailserver#1428]
## Context

I'm trying to use this container as a relay to other SMTP servers. Let's say Gmail. If I use port 465 to relay, it doesn't work.

## Expected Behavior

Although the recommendation seems to be port 587, port 465 should work too.

## Actual Behavior

Not working. 

## Possible Fix

Relay to `[smtp.gmail.com]:587` instead.

## Your Environment

* Amount of RAM available: 8G
* Mailserver version used: tvial/docker-mailserver@sha256:6791fac577bee0ede15bcea81dcafd40be153647a8859f562ac08dbe12c33e82
* Docker version used: 18.06.1-ce
* Environment settings relevant to the config:

  ```yaml
  DEFAULT_RELAY_HOST: '[smtp.gmail.com]:465'
  DMS_DEBUG: 0
  ENABLE_SRS: 1
  MAIL_RELAY_PASS: ****
  ONE_DIR: 1
  PERMIT_DOCKER: connected-networks
  POSTFIX_MESSAGE_SIZE_LIMIT: 52428800
  RELAY_HOST: smtp.gmail.com
  RELAY_PASSWORD: ****
  RELAY_PORT: '465'
  RELAY_USER: ****@example.com
  SMTP_ONLY: 1
  SRS_DOMAINNAME: example.com
  SRS_EXCLUDE_DOMAINS: example.com
  SRS_SENDER_CLASSES: envelope_sender,header_sender
  ```
* Any relevant stack traces ("Full trace" preferred):

  It prints a lot of logs like these:

  ```
  mar 13 10:59:32 server.example.net c50a483a8a8e[1077]: Mar 13 09:59:32 c50a483a8a8e postfix/smtp[3611]: SMTPS wrappermode (TCP port 465) requires setting "smtp_tls_wrappermode = yes", and "smtp_tls_security_level = encrypt" (or stronger)
  mar 13 10:59:42 server.example.net c50a483a8a8e[1077]: Mar 13 09:59:42 c50a483a8a8e postfix/smtp[3607]: 515E558039E: to=<someone@example.com>, relay=smtp.gmail.com[74.125.193.109]:465, delay=455, delays=445/0.01/10/0, dsn=4.4.2, status=deferred (lost connection with smtp.gmail.com[74.125.193.109] while receiving the initial server greeting)
  ```

@Tecnativa TT22925
