### ISSUE TITLE
Docker's default IPv6 setup breaks SPF checks

### ISSUE THREAD

**Issue by meiamsome** [tomav/docker-mailserver#1438]
## Context
When another mailserver attempts to send an email to the one set up with this docker compose set up over IPv6, the mail will be incorrectly processed by SPF protection.

## Expected Behavior
The SPF check is run against the originating IPv6 address

## Actual Behavior
The SPF check is run against the IPv4 gateway that docker is using to proxy the IPv6 connection (172.20.0.1 is the gateway):
```
Mar 28 08:18:20 mailserver postfix/smtpd[16668]: connect from unknown[172.20.0.1]
Mar 28 08:18:20 mailserver policyd-spf[16674]: 550 5.7.23 Message rejected due to: SPF fail - not authorized. Please see http://www.openspf.net/Why?s=mfrom;id=<email removed>>;ip=172.20.0.1;r=<UNKNOWN>
Mar 28 08:18:20 mailserver postfix/smtpd[16668]: NOQUEUE: reject: RCPT from unknown[172.20.0.1]: 550 5.7.23 <<email removed>>: Recipient address rejected: Message rejected due to: SPF fail - not authorized. Please see http://www.openspf.net/Why?s=mfrom;id=<email removed>;ip=172.20.0.1;r=<UNKNOWN>; from=<<email removed>> to=<<email removed>> proto=ESMTP helo=<<domain removed>>>
Mar 28 08:18:20 mailserver postfix/smtpd[16668]: disconnect from unknown[172.20.0.1] ehlo=1 mail=1 rcpt=0/1 data=0/1 rset=1 quit=1 commands=4/6
```

## Possible Fix
There is an upstream issue to implement the same IPv6 NAT rules as IPv4: https://github.com/moby/moby/issues/25407.
I don't think that this is fixable in docker-mailserver itself at this current time without going far outside of the scope of a mailserver. 

## Workaround
I have got SPF with IPv6 to work correctly using [robbertkl/docker-ipv6nat](https://github.com/robbertkl/docker-ipv6nat) which configures the ip6tables to do NAT like docker currently does for iptables, and with a small tweak to the `docker-compose.yml` (And a bump to version 2.1):
```yaml
networks:
  default:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: fd00:0123:4567::/48
          gateway: fd00:0123:4567::1
```
This returns the correct result:
```
Mar 28 11:11:44 mailserver postfix/smtpd[978]: connect from <domain removed>[<ipv6 address removed>]
Mar 28 11:11:44 mailserver policyd-spf[986]: prepend Received-SPF: Pass (mailfrom) identity=mailfrom; client-ip=<ipv6 address removed>; helo=<domain removed>; envelope-from=<email removed>; receiver=<UNKNOWN> 
```
## Steps to Reproduce
1. Configure docker-mailserver on a server with an IPv6 
2. Send an email from another server that will use IPv6 to connect to the original server and ensure SPF is configured.
3. SPF failure

## Discussion

Mostly I'm posting this issue here as a note that there doesn't seem to be any progress on the upstream issue, so perhaps a warning in the Readme, or similar, may be required because:
1. Launching this project on a server with IPv6 will  listen for IPv6 connections that won't work as docker will listen on both IPv4 & IPv6 when forwarding ports
2. It is possible to entirely miss this case as most mail servers use IPv4 and I only happened to notice this after another mail server I had configured manually reported an undelivered mail to me.

**Comment by erik-wramner** [comment]
I'm flagging this as a documentation issue until there is a solution in upstream.

**Comment by lukecyca** [comment]
I'm being bitten by this issue, so I've implemented the workaround. Here are my full changes. Does this look reasonable @meiamsome? I wanted to post the full diff here for others' benefit.

It seems to be working, and I can see connections from IPv6 addresses in my mail logs (both from MTAs and MUAs). Thanks for this workaround!

```diff
+++ b/serv/docker-compose.yml
@@ -1,4 +1,4 @@
-version: '2'
+version: '2.1'
 
@@ -32,6 +32,16 @@ services:
 
+  ipv6nat:
+    image: robbertkl/ipv6nat
+    restart: always
+    network_mode: "host"
+    cap_add:
+      - NET_ADMIN
+      - SYS_MODULE
+    volumes:
+      - /var/run/docker.sock:/var/run/docker.sock:ro
+      - /lib/modules:/lib/modules:ro

@@ -306,4 +316,13 @@ networks:

+  default:
+    driver: bridge
+    enable_ipv6: true
+    ipam:
+      driver: default
+      config:
+        - subnet: fd00:0123:4567::/48
+          gateway: fd00:0123:4567::1
```

**Comment by aendeavor** [comment]
Could this be added to the wiki @all?

**Comment by lukecyca** [comment]
Moved my instructions to a wiki page. This issue can be closed I think.

https://github.com/tomav/docker-mailserver/wiki/IPv6

**Comment by aendeavor** [comment]
Thank you very much @lukecyca !

**Comment by AlexanderSchoenfeld** [comment]
There seems to be an issue using this with the current docker-compose version 3.8:

> ERROR: The Compose file './docker-compose.yml' is invalid because:
> Unsupported config option for services.default: 'driver'

How to configure this for the new version?

**Comment by frugan-it** [comment]
Sorry for my ignorance..

I applied the workaround and it seems to work, but I just wanted to know if these values:

```
subnet: fd00:0123:4567::/48
gateway: fd00:0123:4567::1
```

can be left exactly as they are written, or if you need to adapt them according to the IPv6 of your host machine.

I left them exactly like that, and it all seems to work..

**Comment by frugan-it** [comment]
For anyone experiencing a similar problem (SPF fail with client-ip=fd00:123:4567::1), perhaps I have found the solution:

**docker-compose.yml**

```yaml
version: '3.9'

services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:10.4.0
    depends_on:
      - ipv6nat # <--
    ...

  ipv6nat:
    image: docker.io/robbertkl/ipv6nat:latest
    ...
```

@meiamsome @lukecyca @georglauterbach @AlexanderSchoenfeld @robin4002 @Bluejanis @thom-ek

**Comment by frugan-it** [comment]
@rkahle I confirm that the fix I posted has solved my problems.
Could you post your full `docker-compose.yml` file?

**Comment by rkahle** [comment]
> 

Thanks for the fast reply! Here is my `docker-compose.yml`:
```yaml
version: "3"

services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: ####
    domainname: ####
    env_file: ./mailserver/mailserver.env
    depends_on:
      - ipv6nat
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    environment:
      SSL_TYPE: letsencrypt
      SSL_DOMAIN: ####
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    volumes:
      - ####/dms/mail-data/:/var/mail/
      - ####/dms/mail-state/:/var/mail-state/
      - ####/dms/mail-logs/:/var/log/mail/
      - ####/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
      - ./acme.json:/etc/letsencrypt/acme.json:ro
    restart: "always"
    stop_grace_period: 1m

  ipv6nat:
    image: robbertkl/ipv6nat
    network_mode: "host"
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /lib/modules:/lib/modules:ro
    restart: "always"

networks:
  default:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: fd00:0123:4567::/48
          gateway: fd00:0123:4567::1
```

**Comment by frugan-it** [comment]
Do all connections with IPv6 resolve on `fd00:0123...`? Or only some?
That is, the output of this command:

```
docker exec -it mailserver setup debug show-mail-logs | grep "CONNECT from"
```

always reports `CONNECT from [fd00:...`? Or just a few times?
What is the output of this command?

```
docker exec -it mailserver setup debug show-mail-logs | grep "CONNECT from \[fd00"
```
As a **temporary fallback measure**, you might add in `docker-compose.yml:`:

```yml
services:
  mailserver:
    ...
    volumes:
      - ${PWD}/dms/config/postfix-policyd-spf.conf:/etc/postfix-policyd-spf-python/policyd-spf.conf
    ...
```
And then inside `postfix-policyd-spf.conf` something like that:

```
skip_addresses = 127.0.0.0/8,::ffff:127.0.0.0/104,::1,fd00:0123:4567::/48
Whitelist = fd00:0123:4567::/48
...
```
See first the contents of the file `/etc/postfix-policyd-spf-python/policyd-spf.conf` inside the container, to know what other directives to insert inside.

Obviously this does not solve the problem, but in the meantime it allows you to work until you understand the real reason..

**Comment by frugan-it** [comment]
Maybe it has nothing to do with it, but to remove any doubt (see [previous comment](https://github.com/docker-mailserver/docker-mailserver/issues/1438#issuecomment-979467324)), have you tried to change the values of `subnet` and `gateway`?
For example, I am using the ones listed here https://github.com/robbertkl/docker-ipv6nat:

```yml
config:
  - subnet: fd00:3984:3989::/64
    gateway: fd00:3984:3989::1
```

**Comment by cloud-erik** [comment]
Maybe a stupid questions, but why not use native IPv6 without nat of the host?

I mean first create own ipv6 network at host and than in compose:

```
services:
  mailserver:
....
    networks:
       ipv6:
         ipv6_address: my_fix_ipv6

networks:
  ipv6:
    external: true   
```
Than ipv6 traffic is routed as normal without nat. only the docker host has to have a route and must be set as gateway for the container subnet.
