### ISSUE TITLE
High Cpu caused by supervisord

### ISSUE THREAD

**Issue by NicMan37** [tomav/docker-mailserver#1516]
## Context

Linux 5.4.0-29-generic
Ubuntu 20.04 LTS
The mailserver is working fine, except for high cpu usage caused by supervisord
i've tried to set all stderr_logfile and stdout_logfile to NONE but nothing has changed
it usage about 15% of cpu on a xeon and this isn't good

## *How* do we replicate the issue?

I don't know how, this is a normal installation

## Actual Behavior

High Cpu usage by supervisord
## Expected behavior (i.e. solution)

Not use so much cpu

## Your Environment

* Amount of RAM available: 64GB
* Mailserver version used: tvial/docker-mailserver:latest
* Docker version used: Docker version 19.03.8, build afacb8b7f0
* Environment settings relevant to the config:
* Any relevant stack traces ("Full trace" preferred):

Dockerfile
```
FROM tvial/docker-mailserver:latest
RUN sed -i -r 's/stdout_logfile=.*/stdout_logfile=NONE/' /etc/supervisor/conf.d/supervisor-app.conf
RUN sed -i -r 's/stderr_logfile=.*/stderr_logfile=NONE/' /etc/supervisor/conf.d/supervisor-app.conf
```
docker-compose.yml

```
version: '3.3'
services:
  mail:
    #image: tvial/docker-mailserver:latest
    image: mailserver
    build: 
      context: /hangar/mail/
      dockerfile: Dockerfile
    hostname: ${HOSTNAME}
    domainname: ${DOMAINNAME}
    container_name: ${CONTAINER_NAME}
    restart: unless-stopped
    #network_mode: host
    ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
    volumes:
    - maildata:/var/mail
    - mailstate:/var/mail-state
    - maillogs:/var/log/mail
    - ./config/:/tmp/docker-mailserver/
    - /etc/localtime:/etc/localtime:ro
    env_file:
    - .env
    - env-mailserver
    cap_add:
    - NET_ADMIN
    - SYS_PTRACE
    restart: unless-stopped
volumes:
  maildata:
    driver: local
  mailstate:
    driver: local
  maillogs:
    driver: local
```
