### ISSUE TITLE
I can't send e-mail to a specific domain as postfix can't find any MX-entry

### ISSUE THREAD

**Issue by theoneandonly-vector** [tomav/docker-mailserver#1544]
I can't send e-mail to a specific domain as postfix can't find any MX-entry
I use dns: 1.1.1.1 in my docker-compose.override.yml.
I can find MX-records on docker-host using dig with 1.1.1.1 as DNS-Server, but postfix inside docker-mailserver can't.

Similar Issue:
https://github.com/tomav/docker-mailserver/issues/948

I added this to my local docker-compose.override.yml
```
mail:
   image: tvial/docker-mailserver:latest
   hostname: mail
   domainname: neutronix.ch
   volumes:
    - log:/var/log
   environment:
   - ENABLE_POSTGREY=0
   - SPAMASSASSIN_SPAM_TO_INBOX=1
   - SMTP_ONLY=1
   - POSTFIX_MAILBOX_SIZE_LIMIT=
   - POSTFIX_MESSAGE_SIZE_LIMIT=20971520
   dns: 1.1.1.1
```

   - ENABLE_POSTGREY=0
and
   - SPAMASSASSIN_SPAM_TO_INBOX=1
are working correctly. but I still can't resolve a domain from inside mail-docker:
```
(Host or domain name not found. Name service error for name=mobi.ch type=MX: Host not found, try again)
```

```
(delivery temporarily suspended: Host or domain name not found. Name service error for name=mobi.ch type=MX: Host not found, try again)
```

when I try to resolve it from outsid eth econtainer usign 1.1.1.1 it works:
```
dig mobi.ch MX

; <<>> DiG 9.16.1-Ubuntu <<>> mobi.ch MX
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 53228
;; flags: qr rd ra; QUERY: 1, ANSWER: 3, AUTHORITY: 0, ADDITIONAL: 1

;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: 65494
;; QUESTION SECTION:
;mobi.ch.                       IN      MX

;; ANSWER SECTION:
mobi.ch.                839     IN      MX      20 mail20.swisscom.com.
mobi.ch.                839     IN      MX      20 mail10.swisscom.com.
mobi.ch.                839     IN      MX      10 mail.swisscom.com.

;; Query time: 3 msec
;; SERVER: 127.0.0.53#53(127.0.0.53)
;; WHEN: Do Jun 18 09:05:57 CEST 2020
;; MSG SIZE  rcvd: 115
```
