### ISSUE TITLE
Connection timed out [IPV4 & 6]

### ISSUE THREAD

**Issue by rdearman** [tomav/docker-mailserver#1592]
I keep getting Connection timed out errors when attempting to send email. There is no firewall blocking from the host. I have used docker exec -it XXXXX bash and attempted to install telnet, but network failure. (no networking commands inside the container to test anything)
```
connect to aohs-co-uk0c.mail.protection.outlook.com[104.47.21.36]:25: Connection timed out
connect to alt2.aspmx.l.google.com[2607:f8b0:4024:c02::1b]:25: Cannot assign requested address
connect to aspmx.l.google.com[142.250.107.26]:25: Connection timed out
```

So I know the problem is with the network, but I have no idea how to fix it. 
```
ip address
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
61: eth0@if62: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether 02:42:ac:11:00:02 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.17.0.2/16 brd 172.17.255.255 scope global eth0
       valid_lft forever preferred_lft forever
```
 

docker inspect :
```
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "f368967d053f2157f07cd3e6bc5a4d04fcdbefa09358bfaa0641b1771ed8a3c9",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {
                "110/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "110"
                    }
                ],
                "143/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "143"
                    }
                ],
                "25/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "25"
                    }
                ],
                "4190/tcp": null,
                "465/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "465"
                    }
                ],
                "587/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "587"
                    }
                ],
                "993/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "993"
                    }
                ],
                "995/tcp": [
                    {
                        "HostIp": "0.0.0.0",
                        "HostPort": "995"
                    }
                ]
            },
            "SandboxKey": "/var/run/docker/netns/f368967d053f",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "731df4916097770bed24fca31eeb16013b3bbda50c4616953228b6d16d687b6b",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.2",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:11:00:02",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "50eda0926f193ab61ee474426445c52910c8008c5bdd34ee112d029934178f5c",
                    "EndpointID": "731df4916097770bed24fca31eeb16013b3bbda50c4616953228b6d16d687b6b",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:11:00:02",
                    "DriverOpts": null
                }
            }

```

Any assistance would be greatly appreciated. It gets inbound messages and connections, it is only outbound that fails.

````
version: '3.3'

services:
  mail:
    restart: always 
    image: tvial/docker-mailserver:latest
    hostname: mail
    domainname: audioenginering.com
    domainname: audioenginering.co.uk
    domainname: anki-tv.co.uk
    domainname: language-learners-association.org 
    domainname: autodidactic.info
    domainname: businesspodcasting.co.uk
    container_name: mail
    ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "465:465"
    - "993:993"
    - "110:110"
    - "995:995"
    expose:
    - "25"
    - "143"
    - "587"
    - "465"
    - "993"
    - "110"
    - "995"
    volumes:
    - maildata:/var/mail
    - mailstate:/var/mail-state
    - ./config/:/tmp/docker-mailserver/
    environment:
    - ENABLE_SPAMASSASSIN=1
    - ENABLE_CLAMAV=0
    - ENABLE_FAIL2BAN=0
    - ENABLE_POSTGREY=0
    - ONE_DIR=1
    - DMS_DEBUG=1
    - ENABLE_FETCHMAIL=0
    - SSL=yes
    - SSL_TYPE=letsencrypt
    - SA_SPAM_SUBJECT=***SPAM***
    cap_add:
    - NET_ADMIN
    network_mode: bridge


volumes:
  maildata:
    driver: local
  mailstate:
    driver: local
```
`
