### ISSUE TITLE
Complains environment variables are not set

### ISSUE THREAD

**Issue by x-Felix** [tomav/docker-mailserver#1598]
Modify configuration, such as letsencrypt folder and certs will cause .env not properly read by container. 

## Context
I am new user of this docker image. 
I tried to set SSL/TLS letsencrypt correctly and modify folder and certs couple times. Then I use docker-compose down and up to restart the container to make the change take effect. 
However, it warns me that host environment variables are not set, so use blank string. 
The warning happens when I run docker-compose down and up. I checked .env file and configuration is there. 

### *What* is affected by this bug?
Warning of environment variables are not set, so use blank string instead of hostname and domain name. 

### *When* does this occur?
When running docker-compose down and up after configuration change of mapped folder content, such as letsencrypt settings. 

## *How* do we replicate the issue?

1. Container is properly running
2. Modify content under letsencrypt folder or create file under config folder
3. Execute 'docker-compose down'
Warning appears. 

## Actual Behavior
Couple lines of warning messages. 
Have to touch .env file by adding a new line or removing couple space. Then restart container. Warning disappear. 

## Expected behavior (i.e. solution)
No warning

## Your Environment
* Amount of RAM available: 1G
* Mailserver version used: v7.0.0 latest
* Docker version used: Docker version 19.03.8, build afacb8b7f0
* Environment settings relevant to the config: Default from template with ENABLE_POP3=1 ENABLE_CLAMAV=0 ENABLE_FAIL2BAN=1 SSL_TYPE=letsencrypt
* Any relevant stack traces ("Full trace" preferred):

**Comment by erik-wramner** [comment]
Anyone else using letsencrypt who can reproduce this?

**Comment by aendeavor** [comment]
First, please have a look at #1587. Make sure you`re using `latest` for the moment.

Then, please elaborate on what you mean by

> Modify content under letsencrypt folder or create file under config folder

---

I'm using the mailserver with Docker Compose and Let'sEncrypt too. To acquire the certificate, I use _Traefik v2.2.8_ in Swarm mode. I just mount the `acme.json` to the correct place, see the [documentation](https://github.com/tomav/docker-mailserver/wiki/Configure-SSL#traefik) for that. 

This is my compose:

``` YAML
version: '3.8'

services:

  mail:
    image: tvial/docker-mailserver:latest
    hostname: ${HOSTNAME}
    domainname: ${DOMAINNAME}
    container_name: ${CONTAINER_NAME}
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    environment:
      SSL_TYPE: letsencrypt
      SSL_DOMAIN: "*.${DOMAINNAME}" 
    restart: always
    volumes:
      - ./volumes/data:/var/mail
      - ./volumes/state:/var/mail-state
      - ./volumes/logs:/var/log/mail
      - ./config/:/tmp/docker-mailserver/
      - ${PATH_TO_ACME}/acme.json:/etc/letsencrypt/acme.json:ro
    env_file:
      - .env
      - env-mailserver
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
```

Maybe, setting `SSL_TYPE` in the `environment block helps?

**Comment by x-Felix** [comment]
Just an update. This is not only specific to letsencrypt. 

See my session log below. 
`ubuntu@Test4:~/config$ ls
dovecot-quotas.cf  opendkim  postfix-accounts.cf  postfix-aliases.cf  postfix-virtual.cf  test.cf
ubuntu@Test4:~/config$ rm test.cf 
rm: remove write-protected regular empty file 'test.cf'? y
rm: cannot remove 'test.cf': Permission denied
ubuntu@Test4:~/config$ ls
dovecot-quotas.cf  opendkim  postfix-accounts.cf  postfix-aliases.cf  postfix-virtual.cf  test.cf
ubuntu@Test4:~/config$ sudo rm test.cf 
ubuntu@Test4:~/config$ ls
dovecot-quotas.cf  opendkim  postfix-accounts.cf  postfix-aliases.cf  postfix-virtual.cf
ubuntu@Test4:~/config$ docker-compose up -d mail
WARNING: The HOSTNAME variable is not set. Defaulting to a blank string.
WARNING: The DOMAINNAME variable is not set. Defaulting to a blank string.
WARNING: The CONTAINER_NAME variable is not set. Defaulting to a blank string.
ERROR: Couldn't connect to Docker daemon at http+docker://localhost - is it running?

If it's at a non-standard location, specify the URL with the DOCKER_HOST environment variable.
ubuntu@Test4:~/config$ ls -al
total 20
drwxr-xr-x  3 root   root   4096 Sep  6 10:36 .
drwxr-xr-x 11 ubuntu ubuntu 4096 Sep  3 09:14 ..
-rw-r--r--  1 root   root      0 Aug 26 17:00 dovecot-quotas.cf
drwxr-xr-x  3 root   root   4096 Aug 26 17:01 opendkim
-rw-r--r--  1 root   root    829 Aug 29 11:07 postfix-accounts.cf
-rw-r--r--  1 root   root      0 Aug 26 20:17 postfix-aliases.cf
-rw-r--r--  1 root   root    176 Aug 27 09:46 postfix-virtual.cf
ubuntu@Test4:~/config$ cd ,.
-bash: cd: ,.: No such file or directory
ubuntu@Test4:~/config$ cd ..
ubuntu@Test4:~$ ls
config  docker-compose.yml  env-mailserver  letsencrypt  setup.sh
ubuntu@Test4:~$ sudo nano env-mailserver 
ubuntu@Test4:~$ sudo nano .env 
ubuntu@Test4:~$ sudo docker-compose up -d mail
Creating network "ubuntu_default" with the default driver
Creating mail ... done
ubuntu@Test4:~$ `

What I did is to create an empty test.cf file under config folder, then stop docker, the warning appears. 
I removed the test.cf file, no use. I need to modify .env with some change. Then start the docker, it works again. 
Hope this info helps.

**Comment by aendeavor** [comment]
I don't mean to pry, but why would you want to do this in the first place? I mean editing a file manually. I believe `config/` to be a directors which is meant to be edited by `setup.sh`. So what's the reason?

**Comment by x-Felix** [comment]
@aendeavor 
I only recall I was trying to sort out folder mapping for letsencrypt certs. As I don’t want to expose http port, I use acme.sh to issue certificates. The directories are a bit different from wiki. I assumed that’s some file change under letsencrypt folder.
The session log I posted is a way to reproduce the warning. I didn’t actually write anything under config folder that caused the warning.

The docker error is due to permission. I didn’t sudo.
The warning message is the same. So I didn’t execute sudo again.

**Comment by aendeavor** [comment]
I understand. So you followed the wiki page for the Let'sEncrypt environment, i.e. [this page](https://github.com/tomav/docker-mailserver/wiki/Configure-SSL)?

You said

> I tried to set SSL/TLS letsencrypt correctly

Is there anything wrong with the automatic setup?

---

If the situation seems hopeless, you can try to use _Traefik_ as well. I could help you with this if you like.

**Comment by x-Felix** [comment]
No, I didn't exactly follow the wiki page you mentioned, but take it as reference. 
I use [acme.sh docker](https://acme.sh) which can issue letsencrypt cert by using DNS method not exposing http port to Internet. But acme.sh cert install structure is different than this wiki. 

```
ubuntu@Test4:~$ ls
config  docker-compose.yml  env-mailserver  letsencrypt  setup.sh
ubuntu@Test4:~$ cd letsencrypt/
ubuntu@Test4:~/letsencrypt$ ls
account.conf  ca  http.header  live  mail.mydomain.com
ubuntu@Test4:~/letsencrypt$ cd mail.mydomain.com/
ubuntu@Test4:~/letsencrypt/mail.mydomain.com$ ls
ca.cer         mail.mydomain.com.cer   mail.mydomain.com.csr       mail.mydomain.com.key
fullchain.cer  mail.mydomain.com.conf  mail.mydomain.com.csr.conf
```

I have to use rsync to install / convert acme.sh issued certs to pem format into /etc/letsencrypt/**live**/mail.mydomain.com/ .
That's why there's some file modification under letsencrypt folder. 

Right now, my setup is working fine after I touched .env file again after warning. 
I am reporting a potential bug here. Just curious why some other file change will cause .env not read properly while .env file is still there, no change. I have to make some change to .env file to let container read it again.

**Comment by x-Felix** [comment]
This is how I config acme.sh DNS mode to issue certificate with this mail server image. 

Create folder /home/ubuntu/letsencrypt/ and /home/ubuntu/letsencrypt/live
Create file /home/ubuntu/letsencrypt/account.conf with your Cloudflare API token and account id.
```
sudo docker run --rm  -itd  \
  -v /home/ubuntu/letsencrypt/:/acme.sh  \
  --net=host \
  --name=acme.sh \
  neilpang/acme.sh --issue --dns dns_cf -d mail.example.com daemon
```
Then copy issued certificate to correct folder this mailserver container can recognise.
```
sudo rsync -avh "/home/ubuntu/letsencrypt/mail.example.com/mail.example.com.cer" "/home/ubuntu/letsencrypt/live/mail.example.com/mail.example.com.pem"
sudo rsync -avh "/home/ubuntu/letsencrypt/mail.example.com/mail.example.com.key" "/home/ubuntu/letsencrypt/live/mail.example.com/privkey.pem"
sudo rsync -avh "/home/ubuntu/letsencrypt/mail.example.com/fullchain.cer" "/home/ubuntu/letsencrypt/live/mail.example.com/fullchain.pem"
```
My way may not best, but don't need http.

**Comment by aendeavor** [comment]
Sadly I'm not familiar with `neilpang/acme.sh`.

Two things:

1. Is there a actually a problem with this setup?
2. You are changing the MIME-tyoe of the files, i.e from `.cer` and `.key` to `.pem`. I only know `.pem` for the`SSL_TYPE` **`manual`**! Can you check this?

**Comment by x-Felix** [comment]
No problem with my setup. 
Just during the configuration I noticed the env lost warning. I solved it by making change to .env file to let container assumes there’s update of the env file so read it into memory.
I report the warning issue here to see if there’s some bug haven’t been noticed. Not big impact to my use.

**Comment by aendeavor** [comment]
Alright. First of all, thank you very mich for reporting this here. We really appreciate it!

Could you post your `.env` file please? Just alter the domain/hostname, don't change anything else.

**Comment by x-Felix** [comment]
```
ubuntu@Test4:~/letsencrypt/mail.mydomain.com$ sudo docker run --rm  -itd  \
>   -v /home/ubuntu/letsencrypt/:/acme.sh  \
>   --net=host \
>   --name=acme.sh \
>   neilpang/acme.sh --install-cert --dns dns_cf -d mail.ozbuy.top \
>   --cert-file      /home/ubuntu/letsencrypt/live/mail.mydomain.com/mail.mydomain.com.pem  \
>   --key-file       /home/ubuntu/letsencrypt/live/mail.mydomain.com/privkey.pem  \
>   --fullchain-file /home/ubuntu/letsencrypt/live/mail.mydomain.com/fullchain.pem \ daemon
6838a5b3c1948c8aee5d45920eaaf6b195ebbb5d933f2f0b845a743cb23382c7

ubuntu@Test4:~/letsencrypt/live/mail.ozbuy.top$ sudo docker-compose down
WARNING: The HOSTNAME variable is not set. Defaulting to a blank string.
WARNING: The DOMAINNAME variable is not set. Defaulting to a blank string.
WARNING: The CONTAINER_NAME variable is not set. Defaulting to a blank string.
Stopping mail ... done
Removing mail ... done
Removing network ubuntu_default

ubuntu@Test4:~$ sudo nano .env
ubuntu@Test4:~$ sudo docker-compose up -d mail
Creating network "ubuntu_default" with the default driver
Creating mail ... done
```

```
ubuntu@Test4:~$ cat .env 

# -----------------------------------------------------------------------------------------------------------------------------
# --------------------- General Settings --------------------------------------------------------------------------------------
# -----------------------------------------------------------------------------------------------------------------------------

HOSTNAME=mail
DOMAINNAME=mydomain.com
CONTAINER_NAME=mail
```

```
ubuntu@Test4:~$ cat docker-compose.yml 
version: '2'
services:
  mail:
    image: tvial/docker-mailserver:latest
    hostname: ${HOSTNAME}
    domainname: ${DOMAINNAME}
    container_name: ${CONTAINER_NAME}
    ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
    - "995:995"
    volumes:
    - maildata:/var/mail
    - mailstate:/var/mail-state
    - maillogs:/var/log/mail
    - ./config/:/tmp/docker-mailserver/
    - /home/ubuntu/letsencrypt/:/etc/letsencrypt/
    env_file:
    - .env
    - env-mailserver
    cap_add:
    - NET_ADMIN
    - SYS_PTRACE
    restart: always
volumes:
  maildata:
    driver: local
  mailstate:
    driver: local
  maillogs:
    driver: local
```

I reproduced the warning by using acme.sh to install cert in letsencrypt folder. 
Let me try SSL_TYPE=manual then. Just a question, why manual mode only has - SSL_CERT_PATH=/tmp/ssl/cert/public.crt
- SSL_KEY_PATH=/tmp/ssl/private/private.key in the wiki, no need to point fullchain file path?
