### ISSUE TITLE
Connection refused port 110 (POP3)

### ISSUE THREAD

**Issue by KyleDuPlessis** [tomav/docker-mailserver#1609]
Using [this](https://fabianlee.org/2019/10/23/docker-running-a-postfix-container-for-testing-mail-during-development/) guide, I have encountered a connection error when connecting on port 110 (for POP3).

After running:
`nc -vz 192.168.x.xxx 110`

Output:
`nc: connect to 192.168.x.xxx port 110 (tcp) failed: Connection refused`

The connection succeeds when running the above command respectively for IMAP on port 143 and SMTP on port 587.

I have enabled the POP3 service using ENABLE_POP3 = 1 in the .env file and included port 110 in docker-compose.yml. Firewall is disabled.

The desktop mail client installed on the host (Mozilla Thunderbird) fails to connect to the server using POP3 on port 110, it only successfully connects using IMAP on port 143 and SMTP on port 587 (as in the article linked above).

My docker-compose.yml:
```
version: '2'
services:
  mail:
    image: tvial/docker-mailserver:latest
    hostname: ${HOSTNAME}
    domainname: ${DOMAINNAME}
    container_name: ${CONTAINER_NAME}
    ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
    - "465:465"
    - "995:995"
    - "110:110"

    volumes:
    - maildata:/var/mail
    - mailstate:/var/mail-state
    - maillogs:/var/log/mail
    - ./config/:/tmp/docker-mailserver/
    env_file:
    - .env
    - env-mailserver
    cap_add:
    - NET_ADMIN
    - SYS_PTRACE
    restart: always
volumes:
  maildata:
    driver: local
  mailstate:
    driver: local
  maillogs:
    driver: local
```

My .env:
```
HOSTNAME=mail
DOMAINNAME=csir.com
CONTAINER_NAME=mail

ENABLE_POP3=1
ENABLE_CLAMAV=0
ENABLE_FAIL2BAN=1
SSL_TYPE=self-signed
ENABLE_SPAMASSASSIN=0
```

Any advice / assistance would be highly appreciated.

**Comment by aendeavor** [comment]
This seems odd, indeed. Here are a few steps I would try first.

0. This seems to be the strongest clue: The `ENABLE_IMAP=1` environment variable and the other below it **do not** beling in the `.env` file. In Compose, `.env` variables are expanded **in the `docker-compose.yml` file and not as environment variables in the container**, even though this is what you actually want. Other environment-variable-files are expanded in the conatainer. Please enable POP3 in the `env-mailserver` file.
1. Try updating the `docker-compose.yml`. Depending on the Compose version you have installed, for Docker Compose `1.26.x` you can use `version: '3.8'` in your compose file, if not, use `3.7`. Here, we're just making sure it's not something related to age. Furthermore, please indent your YAML files correctly. I used VS Code and Prettier to provide what I mean - I also updated the version:

``` YAML
version: '3.8'

services:
  mail:
    image: tvial/docker-mailserver:latest
    hostname: ${HOSTNAME}
    domainname: ${DOMAINNAME}
    container_name: ${CONTAINER_NAME}
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
      - "465:465"
      - "995:995"
      - "110:110"
    volumes:
      - maildata:/var/mail
      - mailstate:/var/mail-state
      - maillogs:/var/log/mail
      - ./config/:/tmp/docker-mailserver/
    env_file:
      - .env
      - env-mailserver
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    restart: always

volumes:
  maildata:
    driver: local
  mailstate:
    driver: local
  maillogs:
    driver: local
```

2. This could be odd, but try removing the blank line from your `.env` file. You never know...
