### ISSUE TITLE
Unable to send to / receive emails from the outside world

### ISSUE THREAD

**Issue by KyleDuPlessis** [tomav/docker-mailserver#1612]
## Subject

* [ ] I would like to contribute to the project (code, documentation, advocacy, integration, ...)
* [ ] I would like some help for integrating this container with another service (rainloop, PostFWD, ...)
* [ ] I would like to configure a not documented mail server use case
* [x] I would like some feedback concerning a use case
* [x] I have questions about TLS/SSL/STARTTLS/OpenSSL
* [ ] Other

## Description

Using [this](https://fabianlee.org/2019/10/23/docker-running-a-postfix-container-for-testing-mail-during-development/) guide, I have discovered that sending to / receiving emails from the outside world (e.g. xxx@gmail.com, xxx@yahoo.com email addresses) does not work. It reports back undelivered when sending an email to the outside world (e.g. xxx@gmail.com) using an email account which has been created / hosted on email server (e.g. kyle@csir.com and admin@csir.com). Similarly, emails sent from the outside world to kyle@csir.com / admin@csir.com does not appear in their respective inbox's as it should.

![Screenshot from 2020-09-18 09-17-35](https://user-images.githubusercontent.com/27058026/93593046-9e636e00-f9b3-11ea-8f0a-a5cbb597ea00.png)

Furthermore, using public IP (197.229.x.xxx) instead of the private IP (192.168.x.xxx) doesn't seem to solve the issue as well, as it now doesn't connect on port 110 (for POP3) and on port 587 (for SMTP). It connects successfully when using the private IP (192.168.x.xxx). Firewall is disabled.

I suspect this is due to having `SSL_TYPE=self-signed`, but I'm not too sure. Could someone please indicate what the problem is exactly / point me to resources that would help resolve this issue?

My docker-compose.yml:
```
version: '2'
services:
  mail:
    image: tvial/docker-mailserver:latest
    hostname: ${HOSTNAME}
    domainname: ${DOMAINNAME}
    container_name: ${CONTAINER_NAME}
    ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
    - "465:465"
    - "995:995"
    - "110:110"
    environment:
    - ENABLE_POP3=1
    - ENABLE_CLAMAV=0
    - ENABLE_FAIL2BAN=1
    - SSL_TYPE=self-signed
    - ENABLE_SPAMASSASSIN=0

    volumes:
    - maildata:/var/mail
    - mailstate:/var/mail-state
    - maillogs:/var/log/mail
    - ./config/:/tmp/docker-mailserver/
    env_file:
    - .env
    - env-mailserver
    cap_add:
    - NET_ADMIN
    - SYS_PTRACE
    restart: always
volumes:
  maildata:
    driver: local
  mailstate:
    driver: local
  maillogs:
    driver: local
```

My .env:
```
HOSTNAME=mail
DOMAINNAME=csir.com
CONTAINER_NAME=mail
```

Any advice / assistance would be highly appreciated.
