### ISSUE TITLE
Thunderbird simple client configuration needed

### ISSUE THREAD

**Issue by elcolie** [tomav/docker-mailserver#1617]
## Subject
`139` is my IP address
```
mail    | Sep 23 16:51:57 mail postfix/postscreen[3815]: CONNECT from [119.76.34.139]:22175 to [192.168.16.2]:25
mail    | Sep 23 16:51:57 mail postfix/postscreen[3815]: HANGUP after 0 from [119.76.34.139]:22175 in tests before SMTP handshake
mail    | Sep 23 16:51:57 mail postfix/postscreen[3815]: DISCONNECT [119.76.34.139]:22175
mail    | Sep 23 16:51:57 mail postfix/dnsblog[3820]: addr 119.76.34.139 listed by domain b.barracudacentral.org as 127.0.0.2
mail    | Sep 23 16:51:57 mail postfix/dnsblog[3819]: addr 119.76.34.139 listed by domain zen.spamhaus.org as 127.0.0.10
```

`docker-compose.yml`
```
version: '2'

services:
  mail:
    image: tvial/docker-mailserver:latest
    hostname: mail
    domainname: elcolie.com
    container_name: mail
    restart: always
    ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
    volumes:
    - maildata:/var/mail
    - mailstate:/var/mail-state
    - ./config/:/tmp/docker-mailserver/
    - /etc/letsencrypt=/etc/letsencrypt
    environment:
    - ENABLE_SPAMASSASSIN=1
    - ENABLE_CLAMAV=1
    - ENABLE_FAIL2BAN=1
    - ENABLE_POSTGREY=1
    - ENABLE_FETCHMAIL=0
    - ONE_DIR=1
    - DMS_DEBUG=0
    - SSL_TYPE=letsencrypt
    cap_add:
    - NET_ADMIN

volumes:
  maildata:
    driver: local
  mailstate:
    driver: local
```

I had tried [pepmadon](https://github.com/tomav/docker-mailserver/issues/862) setup in the picture, but does not work
I had tried [17Halbe](https://github.com/tomav/docker-mailserver/issues/862) regarding `fail2ban`. Also not work

## Description
Here is my setup
![image](https://user-images.githubusercontent.com/18206728/94044694-af1f4400-fdf8-11ea-879d-45f8c1427cf5.png)

## Question
What is the correct setup for `Thunderbird`?
