### ISSUE TITLE
Traefik: certificate not being used for imap

### ISSUE THREAD

**Issue by ToxicMushroom** [tomav/docker-mailserver#1642]
## Subject
* [x] I have questions about TLS/SSL/STARTTLS/OpenSSL

## Description
So I already had Traefik setup and giving me valid certs before trying this mail server. 
Everything seems to have been going right until I ran one of the TLS checkers `https://www.checktls.com/TestReceiver`
the domain I'm trying to get working is mail.melijn.com with email address admin@melijn.com and later some others.
I also tried these 2 commands:
`docker exec mail openssl s_client -connect 0.0.0.0:25 -starttls smtp -CApath /etc/ssl/certs/` (succeeds)
and
`docker exec mail openssl s_client -connect 0.0.0.0:143 -starttls imap -CApath /etc/ssl/certs/` (Code 18, self signed cert)

So yeah for SMTP it's picking up the certificate from the acme.json but IMAP it isn't I guess?
What did I miss or can I do to fix this.

**Comment by erik-wramner** [comment]
Interesting, sounds like a bug. Can you connect to port 993 (imap with TLS) as well, please? I don't expose port 143, but I do get the correct certificate on port 993. I don't use traefik though.

**Comment by aendeavor** [comment]
I'm using Traefik v2.3 which grabs a wildcard cert. This cert is mounted and works fine.

Please do the following:

1. Post your `docker-compose.yml` file here
2. Try _docker-mailserver_ with `:stable`
3. Post an anonymised version of your `acme.json`

**Comment by ToxicMushroom** [comment]
1. docker-compose.yml
```
version: '3.7'

services:
  mail:
    image: tvial/docker-mailserver:latest
    hostname: ${HOSTNAME}
    domainname: ${DOMAINNAME}
    container_name: ${CONTAINER_NAME}
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - maildata:/var/mail
      - mailstate:/var/mail-state
      - maillogs:/var/log/mail
      - ./config/:/tmp/docker-mailserver/
      - /opt/traefik/acme.json:/etc/letsencryot/acme.json:ro
    env_file:
      - .env
      - mail-server.env
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    restart: always

volumes:
  maildata:
  mailstate:
  maillogs:
```
2: I switched to stable like you suggested without much luck
3: acme.json
```
{
  "le": {
    "Account": {
      "Email": "merlijn@melijn.com",
      "Registration": {
        "body": {
          "status": "valid",
          "contact": [
            "mailto:merlijn@melijn.com"
          ]
        },
        "uri": "https://acme-v02.api.letsencrypt.org/acme/acct/number"
      },
      "PrivateKey": "",
      "KeyType": "4096"
    },
    "Certificates": [
      {
        "domain": {
          "main": "jikan.melijn.com"
        },
        "certificate": "",
        "key": "",
        "Store": "default"
      },
      {
        "domain": {
          "main": "traefik.melijn.com"
        },
        "certificate": "",
        "key": "",
        "Store": "default"
      },
      {
        "domain": {
          "main": "mail.melijn.com"
        },
        "certificate": "cert",
        "key": "key",
        "Store": "default"
      }
    ]
  }
}
```
