### ISSUE TITLE
All external messages to my mail server fail SPF check

### ISSUE THREAD

**Issue by przemub** [tomav/docker-mailserver#1696]
Now I see that the reason is most probably that it tries to verify against the host IP in the Docker network (172.23.0.1). I could set it into the host networking mode but since it is nowhere mentioned I guess the problem lays somewhere else.

### *What* is affected by this bug?

All external messages fail the SPF check with the following message:

`Nov 26 13:10:49 mail postfix/smtpd[989]: NOQUEUE: reject: RCPT from unknown[172.23.0.1]: 550 5.7.23 <prem@???>: Recipient address rejected: Message rejected due to: SPF fail - not authorized. Please see http://www.openspf.net/Why?s=helo;id=???;ip=172.23.0.1;r=<UNKNOWN>; from=<???@???> to=<prem@???> proto=ESMTP helo=<???>`

### *When* does this occur?

When a mail sent is from a server which instructs to fail all addresses with non-matching SPF.

## *How* do we replicate the issue?

I basically copied the original docker compose file and started it.

## Actual Behavior
IP addresses of the senders are replaced with host IP address. SPF fails.

## Expected behavior (i.e. solution)
IP addresses of the senders remain as they were. SPF works.

## Your Environment

* Amount of RAM available: 7.10 GiB
* Mailserver version used: v7.2.0
* Docker version used: 18.09.1
* Environment settings relevant to the config: none
* Any relevant stack traces ("Full trace" preferred): none

**Comment by przemub** [comment]
`PERMIT_DOCKER=host` allows me to receive messages but if I understand correctly it renders the SPF check useless, doesn't it?

**Comment by aendeavor** [comment]
Hey there! Some questions arose:

1. What are you actually doing to see thing behavior? Who's sending the mails? 
2. > All external messages fail the SPF check 

These "external" messages are `from unknown[172.23.0.1]`. This is not external as far as I can see. Again, who is sending?

3. > I basically copied the original docker compose file

This isn't very helpful. What does this file look like?

---

As far as I know, `PERMIT_DOCKER=host` can break SPF, yes.

**Comment by przemub** [comment]
Thanks for your response.

1 and 2) I'm sending an email from my university server which uses Microsoft Exchange to send the emails. My server rejects the message with the message above while at my university mailbox I get a message like this: "prem.moe couldn't confirm that your message was sent from a trusted location. (SPF validation error)." Therefore it is most definitely an external message; prem.moe sits at my home while the university mailbox is stored somewhere in the Microsoft datacentres.
3) You're right, sorry.
```
version: "3.7"
  mail:
    image: tvial/docker-mailserver:release-v7.2.0
    hostname: mail          # ${HOSTNAME}
    domainname: prem.moe    # ${DOMAINNAME}
    container_name: mail    # ${CONTAINER_NAME}
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - ./mail/maildata:/var/mail
      - ./mail/mailstate:/var/mail-state
      - ./mail/maillogs:/var/log/mail
      - ./mail/config/:/tmp/docker-mailserver/
    environment:
      - ENABLE_SPAMASSASSIN=1
      - SPAMASSASSIN_SPAM_TO_INBOX=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=1
      - ONE_DIR=1
      - DMS_DEBUG=0
     # capabilities disabled because otherwise there's no access to the container from the host
     # cap_add:
     # - NET_ADMIN
     #  - SYS_PTRACE
    restart: unless-stopped
```
