### ISSUE TITLE
Missing service managesieve-login at dovecot.conf

### ISSUE THREAD

**Issue by Danissss** [tomav/docker-mailserver#1700]
## Subject

* [ ] I would like to contribute to the project (code, documentation, advocacy, integration, ...)
* [ ] I would like some help for integrating this container with another service (rainloop, PostFWD, ...)
* [ ] I would like to configure a not documented mail server use case
* [ ] I would like some feedback concerning a use case
* [x] I have questions about TLS/SSL/STARTTLS/OpenSSL
* [ ] Other

## Description

Hi, I tried to setup the mail server with roundcube, but when I tried to use sieve, it gave me some issues.

Issue reports from roundcube log:
```
errors: <4dfcd29e> PHP Error: Cannot assign requested address (GET /?_task=settings&_action=plugin.managesieve)
errors: <4dfcd29e> PHP Error: Unable to connect to managesieve on localhost:4190 in /var/www/html/plugins/managesieve/lib/Roundcube/rcube_sieve_engine.php on line 223 (GET /?_task=settings&_action=plugin.managesieve)
errors: <4dfcd29e> PHP Error: Not currently in AUTHORISATION state (GET /?_task=settings&_action=plugin.managesieve)
errors: <4dfcd29e> PHP Error: Not currently connected (GET /?_task=settings&_action=plugin.managesieve)
```

Here is my docker-compose file
```yaml
version: '3.8'

services:
  mail:
    image: tvial/docker-mailserver:latest
    hostname: ${HOSTNAME}
    domainname: ${DOMAINNAME}
    container_name: ${CONTAINER_NAME}
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
      - "4190:4190"  # for managesieve port
    volumes:
      - maildata:/var/mail
      - mailstate:/var/mail-state
      - maillogs:/var/log/mail
      - ./config/:/tmp/docker-mailserver/
      - /etc/letsencrypt:/etc/letsencrypt/
    environment:
      - "SSL_TYPE=letsencrypt"
      - "ENABLE_MANAGESIEVE=1"  # enable managesieve
    env_file:
      - .env
      - mailserver.env
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    restart: always

volumes:
  maildata:
  mailstate:
  maillogs:
```

Possible error:

```
root@mail:~# docker logs 3174bd5dbd47 | grep sieve
Dec  3 21:15:38 mail dovecot: master: Dovecot v2.3.4.1 (f79e8e7e4) starting up for imap, lmtp, sieve
Dec  3 21:20:31 mail dovecot: managesieve-login: Disconnected (no auth attempts in 35 secs): user=<>, rip=172.103.132.234, lip=172.24.0.2, session=<lwb87ZW1XvSsZ4Tq>
```

I checked the dovecot.conf inside container
```
# 2.3.4.1 (f79e8e7e4): /etc/dovecot/dovecot.conf
# Pigeonhole version 0.5.4 ()
# OS: Linux 5.4.0-51-generic x86_64 Debian 10.6 ext4
# Hostname: mail.sample.ca
auth_mechanisms = plain login
auth_verbose = yes
auth_verbose_passwords = sha1:6
hostname = mail.sample.ca
lda_mailbox_autocreate = yes
lda_mailbox_autosubscribe = yes
mail_location = maildir:/var/mail/%d/%n
mail_plugins = " quota"
mail_privileged_group = docker
maildir_stat_dirs = yes
managesieve_notify_capability = mailto
managesieve_sieve_capability = fileinto reject envelope encoded-character vacation subaddress comparator-i;ascii-numeric relational regex imap4flags copy include variables body enotify environment mailbox date index ihave duplicate mime foreverypart extracttext imapflags notify vnd.dovecot.pipe vnd.dovecot.filter
namespace inbox {
  inbox = yes
  location = 
  mailbox Drafts {
    auto = subscribe
    special_use = \Drafts
  }
  mailbox Junk {
    auto = subscribe
    special_use = \Junk
  }
  mailbox Sent {
    auto = subscribe
    special_use = \Sent
  }
  mailbox Trash {
    auto = subscribe
    special_use = \Trash
  }
  prefix = 
}
passdb {
  args = scheme=CRYPT username_format=%u /etc/dovecot/userdb
  driver = passwd-file
}
plugin {
  quota = count:User quota
  quota_grace = 10%%
  quota_max_mail_size = 10M
  quota_rule = *:storage=0
  quota_rule2 = Trash:storage=+50M
  quota_status_nouser = DUNNO
  quota_status_overquota = 552 5.2.2 Mailbox is full
  quota_status_success = DUNNO
  quota_vsizes = yes
  quota_warning = storage=95%% quota-warning 95 %u %d
  quota_warning2 = storage=80%% quota-warning 80 %u %d
  quota_warning3 = -storage=100%% quota-warning below %u %d
  sieve = ~/.dovecot.sieve
  sieve_after = /usr/lib/dovecot/sieve-global/after/
  sieve_before = /usr/lib/dovecot/sieve-global/before/
  sieve_dir = ~/sieve
  sieve_extensions = +notify +imapflags +vnd.dovecot.pipe +vnd.dovecot.filter
  sieve_filter_bin_dir = /usr/lib/dovecot/sieve-filter
  sieve_pipe_bin_dir = /usr/lib/dovecot/sieve-pipe
  sieve_plugins = sieve_extprograms
}
postmaster_address = postmaster@sample.ca
protocols = " imap lmtp sieve"
service auth {
  unix_listener /var/spool/postfix/private/auth {
    group = docker
    mode = 0666
    user = docker
  }
  unix_listener auth-master {
    group = docker
    mode = 0600
    user = docker
  }
  unix_listener auth-userdb {
    group = docker
    mode = 0666
    user = docker
  }
}
service imap-login {
  inet_listener imaps {
    port = 993
    ssl = yes
  }
}
service lmtp {
  unix_listener lmtp {
    group = postfix
    mode = 0660
  }
}
service pop3-login {
  inet_listener pop3s {
    port = 995
    ssl = yes
  }
}
service quota-status {
  client_limit = 1
  executable = quota-status -p postfix
  inet_listener {
    port = 65265
  }
}
service quota-warning {
  executable = script /usr/local/bin/quota-warning.sh
  unix_listener quota-warning {
    group = dovecot
    mode = 0660
    user = dovecot
  }
}
ssl = required
ssl_cert = <omit cert here>
ssl_cipher_list = <omit cipher list here>
ssl_dh = # hidden, use -P to show it
ssl_key = # hidden, use -P to show it
ssl_min_protocol = TLSv1.2
ssl_prefer_server_ciphers = yes
userdb {
  args = username_format=%u /etc/dovecot/userdb
  default_fields = uid=docker gid=docker home=/var/mail/%d/%u
  driver = passwd-file
}
protocol lmtp {
  mail_plugins = " quota sieve"
}
protocol lda {
  mail_plugins = " quota sieve"
}
protocol imap {
  mail_plugins = " quota imap_quota"
}
```

I found it's missing
```
service managesieve-login {
  inet_listener sieve {
    port = 4190
  }
}
```

Should I use customized dovecot.conf?
Am I missing something?

I can send and receive email with no issue.

Thanks for help!
