### ISSUE TITLE
Unable to setup thunderbird with the created username

### ISSUE THREAD

**Issue by yogesh-cyber** [tomav/docker-mailserver#1710]
Hi
- Docker container is up and running
- this is my docker-compose.yml file's configurations
________________________________________________________________________________________________________________________________________

``` YAML
version: '2.0'

services:
  mail:
    image: tvial/docker-mailserver:latest
    hostname: mail # ${HOSTNAME}
    domainname: domain.com # ${DOMAINNAME}
    container_name: mail-server # ${CONTAINER_NAME}
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
      - "1025:1025"
      - "8025:8025"

    volumes:
      - maildata:/var/mail
      - mailstate:/var/mail-state
      - maillogs:/var/log/mail
      - ./config/:/tmp/docker-mailserver/
      # ? if SELinux is enabled, uncomment the line below and comment the line above
      # - ./config/:/tmp/docker-mailserver/${SELINUX_LABEL}
    env_file:
      - mailserver.env
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    restart: always

volumes:
  maildata:
  mailstate:
  maillogs:
```
________________________________________________________________________________________________________________________________________

I have also added the username by running following command
./setup.sh email add <user1@mail.domain.com> [Change123]

I just wanted to configure the thunderbird with the username i created here

I am not sure, if I had missed something or still something is to be configured, totally newbie here. Please help me what are the steps i need to follow to create the useremails and configure them in thunderbird in a local area network 

Thank you so much
Yogesh
