### ISSUE TITLE
SSL: using a 'named volume' in 'nginx reverse proxy' container as source of SSL certs, via docker-compose

### ISSUE THREAD

**Issue by xmatic** [tomav/docker-mailserver#1717]
## Subject
* [ ] I have questions about TLS/SSL/STARTTLS/OpenSSL

## Description
Firstly, thank you to the co-developers for this excellent project. I'm not particularly well-versed with Linux or Docker, but was still able to get my mailserver to work. Next, I decided to install DKIM, SPF and DMARC. All working. **Now, I'm trying to get SSL working** (during login via Thunderbird).

Before I installed `docker-mailserver`, I already had an `nginx reverse proxy` with `letsencrypt-nginx-proxy-companion`, and had two top level domains (TLDs) via `VIRTUALHOST`, and `SSL` working on both domains (i.e. the "lock" icon shows up in the browser when I navigate to the domains).

I tried to adapt the [Example using docker, nginx-proxy and letsencrypt-nginx-proxy-companion with docker-compose](https://github.com/tomav/docker-mailserver/wiki/Configure-SSL#example-using-docker-nginx-proxy-and-letsencrypt-nginx-proxy-companion-with-docker-compose) for my situation as follows:

(Below, for the sake of brevity, I've only included snippets of the code that I thought were relevant to my question. Am happy to include more code if needed.)

(Using Linux 20.04, Docker version 19.03.13,  docker-compose version 1.27.4)

### nginx reverse proxy
the `docker-compose.yml` file for the `nginx reverse proxy` is located in the folder:
`/home/nginx-proxy`

Relevant code from the  `docker-compose.yml` file:
```
services:
  nginx:
    volumes:
      - certs:/etc/nginx/certs
  	  
  dockergen:
    volumes:
      - certs:/etc/nginx/certs
  
  letsencrypt:
    volumes:
      - certs:/etc/nginx/certs
  
  
volumes:
  certs:


networks:
  default:
    external:
      name: nginx-proxy
```
Next, after navigating to the `/home/nginx-proxy` folder, I did `sudo docker-compose up -d`

This runs the `nginx reverse proxy` container and results in a `named volume` named `nginx-proxy_certs`

I would now like to point my `docker-mailserver` container to `nginx-proxy_certs` to look for `SSL certs` there.

### docker-mailserver
the `docker-compose.yml` file for the `docker-mailserver` is located in the folder:
`/home/mailserver2`

Relevant code from the  `docker-compose.yml` file:
```
services:
  mail:
    volumes:
      - nginx-proxy_certs:/etc/letsencrypt/live


volumes:
  nginx-proxy_certs:
    external: true
    

networks:
  default:
    external:
      name: nginx-proxy
```
Next, after navigating to the `/home/mailserver2` folder, I did `sudo docker-compose up -d mail`

After doing this, when I test SSL on my server
- with [https://www.checktls.com/TestReceiver](https://www.checktls.com/TestReceiver), I get the following report: [https://imgur.com/5LYOJci](https://imgur.com/5LYOJci)
- with [https://ssl-tools.net/mailservers](https://ssl-tools.net/mailservers), I get the following report: [https://imgur.com/z5xuhLL](https://imgur.com/z5xuhLL)

My Questions:

1. How can I make the `nginx-proxy_certs` `named volume` from the `nginx reverse proxy` available to the `docker-mailserver` to use for SSL?
2. Do I need the `networks` section in the `mailserver's docker-compose.yml file`?

---------------------

My suspicion: 

1. I didn't add the environmental variable `SSL_TYPE` with value `letsencrypt`. Wasn't sure whether to add it to the `nginx reverse proxy`'s `docker-compose.yml` or to the `docker-mailserver`'s `docker-compose.yml` (also, wasn't sure what was meant by this "(see `docker-compose.yml.dist`)"

2. the instructions say that:
    > the certs folder name located in `letsencrypt/live/` must be the `fqdn` of your container

    In my case, my certs were created for the `nginx proxy server` and the SSL seems to work for 2 different domain names. I'm not sure how I'd get a folder named `mail.domainname1.com` into `letsencrypt/live/`.
