### ISSUE TITLE
SSL login via Thunderbird -- certificate doesn't match, despite following exact code from Wiki

### ISSUE THREAD

**Issue by xmatic** [tomav/docker-mailserver#1723]
## Subject
* [ ] I have questions about TLS/SSL/STARTTLS/OpenSSL

## Description

My mailserver works. Am able to send and receive email. 
However, the `SSL` login doesn't work.
I used the exact code from here: https://github.com/tomav/docker-mailserver/wiki/Configure-SSL#lets-encrypt-recommended

However, when I try to log-into the email via Thunderbird, it tries to go to `imap.example.com:143` and says the certificate is mismatched. Here are 2 screencaps from Thunderbird's process:

(In the code below, `example.com` is replaced with my actual `domain.tld` in the actual code, and the email address is `mail@example.com`).

![2020-12-19_031101](https://user-images.githubusercontent.com/5103936/102687406-16f0eb00-41ac-11eb-9366-1bfefea01d6b.jpg)

![2020-12-19_031614](https://user-images.githubusercontent.com/5103936/102687419-2f610580-41ac-11eb-9259-4c31618bc7f9.jpg)

In the first screenshot, you can see that Thunderbird did some auto-configuration.

In the second screenshot, it's saying that the certificate for `imap.example.com:143` isn't as expected.

Thing is, nowhere in the process do I indicate `imap.example.com` or `smtp.example.com` to the `Lets Encrypt bot`. I indicate `mail.example.com` in the `.env` file. But not `imap.example.com` or `smtp.example.com`. 

**Shouldn't I be indicating `imap.example.com` and `smtp.example.com` somewhere?**

-------------------------------------------------

All my code is reproduced below:

$ `sudo docker network create nginx-proxy`

Then I navigate to the `sidecar` and `mailserver` directories and do: `sudo docker-compose up -d`

### sidecar/docker-compose.yml
```
version: "2"

services:
  nginx: 
    image: nginx
    container_name: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /mnt/data/nginx/htpasswd:/etc/nginx/htpasswd
      - /mnt/data/nginx/conf.d:/etc/nginx/conf.d
      - /mnt/data/nginx/vhost.d:/etc/nginx/vhost.d
      - /mnt/data/nginx/html:/usr/share/nginx/html
      - /mnt/data/nginx/certs:/etc/nginx/certs:ro
    networks:
      - proxy-tier
    restart: always

  nginx-gen:
    image: jwilder/docker-gen
    container_name: nginx-gen
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - /mnt/data/nginx/templates/nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl:ro
    volumes_from:
      - nginx
    entrypoint: /usr/local/bin/docker-gen -notify-sighup nginx -watch -wait 5s:30s /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    restart: always

  letsencrypt-nginx-proxy-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-companion
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /mnt/data/nginx/certs:/etc/nginx/certs:rw
    environment:
      - NGINX_DOCKER_GEN_CONTAINER=nginx-gen
      - DEBUG=false
    restart: always

networks:
  proxy-tier:
    external:
      name: nginx-proxy
```

### mailserver/docker-compose.yml
```
version: '2'
services:
  mail:
    image: tvial/docker-mailserver:latest
    hostname: ${HOSTNAME}
    domainname: ${DOMAINNAME}
    container_name: ${CONTAINER_NAME}
    ports:
    - "25:25"
    - "143:143"
    - "465:465"
    - "587:587"
    - "993:993"
    volumes:
    - ./mail:/var/mail
    - ./mail-state:/var/mail-state
    - ./config/:/tmp/docker-mailserver/
    - /mnt/data/nginx/certs/:/etc/letsencrypt/live/:ro
    cap_add:
    - NET_ADMIN
    - SYS_PTRACE
    restart: always

  cert-companion:
    image: nginx
    environment:
      - "VIRTUAL_HOST=mail.example.com"
      - "VIRTUAL_NETWORK=nginx-proxy"
      - "LETSENCRYPT_HOST=mail.example.com"
      - "LETSENCRYPT_EMAIL=example+letsencrypt@gmail.com"
    networks:
      - proxy-tier
    restart: always
    
networks:
  proxy-tier:
    external:
      name: nginx-proxy
```

### mailserver/.env

```
# –––––––––––––––––––––––––––––––––––––––––––––––
# ––– Docker Compose Settings Variables –––––––––
# –––––––––––––––––––––––––––––––––––––––––––––––

HOSTNAME=mail
DOMAINNAME=example.com
CONTAINER_NAME=mail      #can't use container name if there's name clash with another container

# –––––––––––––––––––––––––––––––––––––––––––––––
# ––– SELinux Compose File Settings Variables –––
# –––––––––––––––––––––––––––––––––––––––––––––––

SELINUX_LABEL=-Z

```
