### ISSUE TITLE
Maildata Volume

### ISSUE THREAD

**Issue by diiigle** [tomav/docker-mailserver#173]
I do not get any data volume generated by the compose file. So i think the data is stored in the container locally. 

Can you fix this, that the /var/mail folder is mapped to a secondary data volume container?

**Comment by tomav** [comment]
@diiigle could you try this one:

```
version: '2'

services:
  mail:
    image: tvial/docker-mailserver:v2
    # build: .
    hostname: mail
    domainname: domain.com
    container_name: mail
    ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
    volumes:
    - ./config/:/tmp/docker-mailserver/
    - maildata:/var/mail

volumes:
  maildata:
    driver: local
```

Let me know.

**Comment by diiigle** [comment]
Nope, didn't worked. Still getting only one container 'mail' created.
 From this discussion:

I think we need the volumes_from command for the Data Volume Container.

aside question: how important is the hostname in this file? i set it to 
the subdomain my mailserver is running on. Is that right?

**Comment by manthis** [comment]
@diiigle you could also do like me and store your emails on your host file system:

`version: '2'

services:
  mail:
    image: tvial/docker-mailserver:v2
    # build: .
    hostname: mail
    domainname: domain.com
    container_name: mail
    ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
    volumes:
    - ./config/:/tmp/docker-mailserver/
    - ./maildata/:/var/mail`

Feel free to change the path. I do actually store this folder on a USB key whose file system is encrypted ;)

**Comment by tomav** [comment]
@diiigle I have limited access to internet through my mobile phone, so I can't pull the image to test but try:

```
version: '2'

services:
  mail:
    image: tvial/docker-mailserver:v2
    # build: .
    hostname: mail
    domainname: domain.com
    container_name: mail
    ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
    volumes:
    - ./config/:/tmp/docker-mailserver/
    - maildata:/var/mail
volumes:
 maildata:
```
