### ISSUE TITLE
Not receiving emails

### ISSUE THREAD

**Issue by djolereject** [tomav/docker-mailserver#1743]
I tried all that I can but I can't get my mailserver to receive emails from the outside.

I do have a specific setup with [nginx-proxy and letsencrypt](https://github.com/nginx-proxy/docker-letsencrypt-nginx-proxy-companion) in front of the mailserver. This combination is mentioned in the wiki and I tried to follow [tutorial](https://github.com/tomav/docker-mailserver/wiki/Configure-SSL), but to no avail.

I can send emails and they look good at the destination, but receiving is the problem. Also, I tried to create multiple users in the container and they can send emails to each other.

## Context

This is just a last version of my setup, but I tried all the combination of ENV settings that I could find:

<details> 
  <summary>Click me to expand </summary>

```
version: '3.7'
services:
  mailserver:
    image: "tvial/docker-mailserver:latest"
    hostname: "mail"
    domainname: "mydomain.com"
    container_name: "mailserver"
    ports:
      - 25:25
      - 143:143
      - 465:465
      - 587:587
      - 993:993
      - 4190:4190
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./data/maildata:/var/mail
      - ./data/mailstate:/var/mail-state
      - ./data/maillogs:/var/log/mail
      - ./config/:/tmp/docker-mailserver/
      - ../data/certs/:/etc/letsencrypt/live/:ro
    environment:
      - PERMIT_DOCKER=network
      - SSL_TYPE=letsencrypt
      - ONE_DIR=1
      - DMS_DEBUG=1
      - SPOOF_PROTECTION=0
      - REPORT_RECIPIENT=1
      - ENABLE_SPAMASSASSIN=0
      - ENABLE_CLAMAV=0
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=0
      - ENABLE_MANAGESIEVE=1
    env_file:
      - mailserver.env
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    restart: always
  mailclient:
    image: "hardware/rainloop"
    container_name: "mailclient"
    volumes:
      - ./data/rainloop:/rainloop/data
    depends_on:
      - mailserver
    environment:
      - VIRTUAL_HOST=mail.mydomain.com
      - LETSENCRYPT_HOST=mail.mydomain.com
      - LETSENCRYPT_EMAIL=mailclient@mydomain.com
      - VIRTUAL_NETWORK=mynetwork-from-nginx-container
    networks:
      - mynetwork-from-nginx-container
    restart: always
networks:
  mynetwork-from-nginx-container:
    external: true
```

</details> 

### *What* is affected by this bug?

I cannot receive email that is sent from outside of this container.

## Actual Behavior
This is what I can confirm:

- certs are visible from the container, I can see them from inside the docker:
when I try to `sudo docker exec mailserver ls -a /etc/letsencrypt/live`, I get:
```
mail.mydomain.com
mail.mydomain.com.chain.pem
mail.mydomain.com.crt
mail.mydomain.com.dhparam.pem
mail.mydomain.com.key
```
- I tested with couple of online tools and my SPF, DKIM and DMARC looks good. I get "PASS" when I see received mails in gmail.

- I'm not sure if that is relevant, but from [dns checker](https://dnschecker.org) I get "SMTP No TLS support" and I can't telnet to port 25.

## Your Environment

* Amount of RAM available:
  - 4GB
* Mailserver version used:
  - latest
* Docker version used:
  - 20.10.1
* Environment settings relevant to the config:
  - mentioned above in the example, but they mostly produce the same problem.
* Any relevant stack traces ("Full trace" preferred):
  - nothing that I can see, grep for "error" returns nothing from logs

One more thing that I tried was to implement one [obscure wiki reference](https://github.com/tomav/docker-mailserver/wiki/FAQ-and-Tips#using-behind-proxy). This is never mentioned in another place, but I managed to create `config/postfix-main.cf` with that line and I confirmed that it really gets in the `/etc/postfix/main.cf` inside the container.

I have no more moves, any help would be apprretiated.
Thanks!

P. S. Just remembered to mention - Gmail that tried to reply gets back couple of hours after with the message:
```
The recipient server did not accept our requests to connect. Learn more at https://support.google.com/mail/answer/7720 [mail.mydomain.com. myip: FAILED_PRECONDITION: connect error (111): Connection refused]
--
```
