### ISSUE TITLE
Docker Swarm and HA

### ISSUE THREAD

**Issue by alidehghan** [tomav/docker-mailserver#1748]
## Subject

* [ ] Other

## Description
How can I setup this image with Docker Swarm and HA (multiple instances | replicas)?

**Comment by aendeavor** [comment]
This is very intricate and really not that easy. You will not find a satisfying answer in this tracker. I can only tell you about Swarm, the HA side of things must Google or another search engine do:

For Swarm, just remove the "restarts: always" and 

``` YAML
    hostname: ${HOSTNAME}
    domainname: ${DOMAINNAME}
    container_name: ${CONTAINER_NAME}
```

Then, use the environment variable `OVERRIDE_HOSTNAME` to set your hostnames. You will need to set environment variables in the `environment:` section. That's more or less it. I wish you good luck with HA.
