### ISSUE TITLE
Integrating mailserver to an existing gsuite

### ISSUE THREAD

**Issue by theyudhiztira** [tomav/docker-mailserver#1750]
Hi currently my office is using gsuite for their email, i'm planning to use this docker image for sending email from my system since gmail smtp is very unreliable. But i'm having trouble with sending or receiving the email. I am very noob on dev ops thingy, so i don't really understand where to start.

Steps i've done so far : 
* Created A record on my zone editor ( cPanel )
![Image of New Zone](https://i.ibb.co/W0bqqsF/Screen-Shot-2021-01-13-at-02-02-48.png)
* Added MX Record 
![Image of MX Record](https://i.ibb.co/Hz0CFPb/Screen-Shot-2021-01-13-at-02-06-45.png)
* All the container already running successfully 
* Certificate is also issued and mounted ( checked with tlscheck )
![tlscheck](https://i.ibb.co/M5L3HNn/Screen-Shot-2021-01-13-at-02-12-16.png)

But every time i tried to send and email it never been delivered, also when i tried to send an email to the address i generated from the **setup.sh -Z email add** gmail says that the email address is not exists.

Here is my docker compose : 
```
version: '3.8'

services:
  mail:
    image: tvial/docker-mailserver:latest
    hostname: ${HOSTNAME}
    domainname: ${DOMAINNAME}
    container_name: ${CONTAINER_NAME}
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - maildata:/var/mail
      - mailstate:/var/mail-state
      - maillogs:/var/log/mail
      - ./config/:/tmp/docker-mailserver/${SELINUX_LABEL}
      - ./letsencrypt/etc:/etc/letsencrypt
    env_file:
      - mailserver.env
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    restart: always

volumes:
  maildata:
  mailstate:
  maillogs:
```

Please kindly help me to figure out.
Thank you
