### ISSUE TITLE
Letsencrypt certs not loaded

### ISSUE THREAD

**Issue by dragonito** [tomav/docker-mailserver#184]
Hi there,

i generated some certs for my rwillig.de domain and this sould by loaded by adding env variables and mounting /etc/letsencrypt:/etc/letsencrypt. I looked through the docker image an the volumes are mounted correctly. But the check says it is still selfsigned.

Have I forgot some configurations?

Thanks for support!

Robin

**Comment by Josef-Friedrich** [comment]
I use the latest version of docker-mailserver and it works: 

`openssl s_client -connect mail.josef-friedrich.de:25 -starttls smtp`

Here is my docker compose file. I use a second docker container for letsencrypt.

```
version: '2'

services:
        mail:
                image: tomav_mail:latest
                #build: $HOME/.dotfiles/docker/image/tomav_docker-mailserver
                hostname: mail
                domainname: josef-friedrich.de
                container_name: mail_josef-friedrich.de
                volumes:
                        - /var/docker/mail_josef-friedrich.de/mail:/var/mail
                        - /var/docker/letsencrypt/etc:/etc/letsencrypt
                        - ./config/:/tmp/docker-mailserver/
                ports:
                        - "25:25"
                        - "143:143"
                        - "587:587"
                        - "993:993"
                environment:
                        - ENABLE_FAIL2BAN=1
                        - SSL_TYPE=letsencrypt
                cap_add:
                        - NET_ADMIN
                restart: always
```
