### ISSUE TITLE
Letsencrypt do not seems to work

### ISSUE THREAD

**Issue by FlyersWeb** [tomav/docker-mailserver#192]
I've tried to install your docker-mailserver image following the tutorial with a letsencrypt certificate.

The certificate works because I also use it on subdomain www for my website.

When I try to connect to the mail server I've got these error :
```
mail dovecot: imap-login: Disconnected (no auth attempts in 0 secs): user=<>, rip=86.245.31.214, lip=172.19.0.4, TLS: SSL_read() failed: error:14094418:SSL routines:SSL3_READ_BYTES:tlsv1 alert unknown ca: SSL alert number 48
```

There is my full up output :
```
mail     | Checking file line endings
mail     | Regenerating postfix 'vmailbox' and 'virtual' for given users
mail     | user 'contact' for domain 'domain.com' with password '********'
mail     | ==> Warning: 'config/postfix-virtual.cf' is not provided. No mail alias/forward created.
mail     | DKIM keys added for: domain.com
mail     | Changing permissions on /etc/opendkim
mail     | Postfix configurations
mail     | No extra postfix settings loaded because optional '/tmp/docker-mailserver/postfix-main.cf' not provided.
mail     | ==> Warning: 'SASL_PASSWD' is not provided. /etc/postfix/sasl_passwd not created.
mail     | Fixing permissions
mail     | Creating /etc/mailname
mail     | Configuring Spamassassin
mail     | Starting daemons
mail     |  * Starting enhanced syslogd rsyslogd
mail     |    ...done.
mail     |  * Starting dovecot services
mail     | Starting SpamAssassin Mail Filter Daemon: spamd.
mail     |  * Starting ClamAV daemon clamd
mail     | LibClamAV Warning: **************************************************
mail     | LibClamAV Warning: ***  The virus database is older than 7 days!  ***
mail     | LibClamAV Warning: ***   Please update it as soon as possible.    ***
mail     | LibClamAV Warning: **************************************************
mail     |    ...done.
mail     | Starting amavisd: amavisd-new.
mail     | Starting OpenDKIM: opendkim.
mail     | Starting OpenDMARC: opendmarc.
mail     |  * Starting Postfix Mail Transport Agent postfix
mail     |    ...done.
mail     | Listing users
mail     | contact@domain.com
mail     | Starting...
mail     | May 22 12:50:55 mail amavis[439]: Internal decoder for .tnef
mail     | May 22 12:50:55 mail amavis[439]: Found decoder for    .exe  at /usr/bin/arj
mail     | May 22 12:50:55 mail amavis[439]: Using primary internal av scanner code for ClamAV-clamd
mail     | May 22 12:50:55 mail amavis[439]: Found secondary av scanner ClamAV-clamscan at /usr/bin/clamscan
mail     | May 22 12:50:55 mail amavis[439]: Deleting db files __db.001,__db.003,nanny.db,__db.002,snmp.db in /var/lib/amavis/db
mail     | May 22 12:50:55 mail amavis[439]: Creating db in /var/lib/amavis/db/; BerkeleyDB 0.54, libdb 5.3
mail     | May 22 12:50:55 mail opendkim[455]: OpenDKIM Filter v2.9.1 starting (args: -x /etc/opendkim.conf -u opendkim -P /var/run/opendkim/opendkim.pid)
mail     | May 22 12:50:55 mail opendmarc[475]: OpenDMARC Filter v1.2.0 starting (args: -c /etc/opendmarc.conf -u opendmarc -P /var/run/opendmarc/opendmarc.pid -p inet:54321@localhost)
mail     | May 22 12:50:55 mail opendmarc[475]: trusted authentication services: mail.domain.com
mail     | May 22 12:50:55 mail postfix/master[570]: daemon started -- version 2.11.0, configuration /etc/postfix
```

and my docker-compose.yml config :
```yaml
mail:
    image: tvial/docker-mailserver:latest
    restart: always
    container_name: mail
    hostname: mail
    domainname: domain.com
    environment:
     - SSL_TYPE=letsencrypt
    ports:
     - "25:25"
     - "143:143"
     - "587:587"
     - "993:993"
    volumes:
     - /etc/letsencrypt:/etc/letsencrypt:ro
     - /var/mail:/var/mail
     - ./config/mail/:/tmp/docker-mailserver/
```

Do you have any idea why I'm not able to use TLS nor SSL while connecting to IMAP server ?

Thanks.
