### ISSUE TITLE
Can't get the container up and running on Rpi4

### ISSUE THREAD

**Issue by BaseCrusher** [tomav/docker-mailserver#2247]
# Can't get the container up and running on Rpi4

Why is the mailserver shutting itself down on the Rpi4

## Description
Hello everyone, I managed to get the mailserver up and running on my debian server.
No I've been trying to get it to work on my home RaspberrryPi4 as well but somehow the container does not behave the same on the Raspberry pi, eventhough I use the exact same setup on my debian server.

Some additional informations.
OS: Pi OS Buster
Docker version: 20.10.9
Docker-Compose version: 1.29.2

The Rpi is in my home network behind a NAT but I don't think that is the issue here.

Thanks in advance for the help. 

``` 
[ TASKLOG ]  Welcome to docker-mailserver 10.2.0,
[ TASKLOG ]  Initializing setup,
[ TASKLOG ]  Checking configuration,
[ TASKLOG ]  Configuring mail server,
[  FATAL  ]  Unless using LDAP, you need at least 1 email account to start Dovecot.,
2021-10-13 12:54:08,083 WARN received SIGTERM indicating exit request
[  ERROR  ]  Shutting down..,
```

**Comment by casperklein** [comment]
What happens, when you follow the advice from the error message? 😉

**Comment by BaseCrusher** [comment]
Yes, I have.

Normaly or atleast on debian the container did not shut down. Since it shuts down when I start the container it is almost alwas in a state restarting, where the setup script does not work.

```
Error response from daemon: Container 5085f9a12bb012c5a34b4d73db736c23f5e22f789cdaf74e30f75f9eb2ddfd5f is restarting, wait until the container is running

--- 
UNCHECKED ERROR
  - script    = ./setup.sh
  - function  = _main
  - command   = ${CRI} exec "${USE_TTY}" "${CONTAINER_NAME}" setup "${@:+$@}"
  - line      = 225
  - exit code = 1

This should not have happened. Please file a bug report.
```

So the other option is to generate the e-mail account before starting the container. So thats what I did. I created an e-mail account and generated the dkim key. Starting the container afterwords results in the same error message. :/

Also, when I'm checking the mail list, I do get some errors as well if the container is not running. I can't check how it behaves when it's running, Since it is always restarting.

```
doveadm(info@domain.com)<15><>: Error: userdb lookup: connect(/var/run/dovecot/auth-userdb) failed: No such file or directory
doveadm(info@domain.com): Error: User lookup failed: Internal error occurred. Refer to server log for more information.
/usr/local/bin/listmailuser: line 12: 1024 *  : syntax error: operand expected (error token is "*  ")
/usr/local/bin/listmailuser: line 12: 1024 *  : syntax error: operand expected (error token is "*  ")
* info@domain.com (  /  ) [%]
```

**Comment by BaseCrusher** [comment]
So, I have shut down the server with `docker-compose down`.
I deleted the docker image files of the mailserver.
I cleared both the config and the docker-data folders.
Generated a new email account and an alias for postmaster.
Created the dkim keys.

But I still get this error.

```
mailserver    | [ TASKLOG ]  Welcome to docker-mailserver 10.2.0
mailserver    | [ TASKLOG ]  Initializing setup
mailserver    | [ TASKLOG ]  Checking configuration
mailserver    | [ TASKLOG ]  Configuring mail server
mailserver    | [  FATAL  ]  Unless using LDAP, you need at least 1 email account to start Dovecot.
mailserver    | 2021-10-14 12:44:26,202 WARN received SIGTERM indicating exit request
mailserver    | [  ERROR  ]  Shutting down..
```

**Comment by BaseCrusher** [comment]
`docker-compose.yml`:
``` 
version: '3.8'

services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mailserver
    domainname: domain.com <= Here I did ofc set my own domain
    env_file: mailserver.env
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/edge/config/security/understanding-the-ports/
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    ports:
      - "25:25"    # SMTP  (explicit TLS => STARTTLS)
      - "143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "465:465"  # ESMTP (implicit TLS)
      - "587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "993:993"  # IMAP4 (implicit TLS)
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/localtime:/etc/localtime:ro
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
```

I actually did not make any changes besides setting the domain name and hostname.

Directory structure:

```
.:
config  docker-compose.yml  docker-data  mailserver.env  setup.sh

./config:
opendkim  postfix-accounts.cf  postfix-virtual.cf

./config/opendkim:
keys  KeyTable  SigningTable  TrustedHosts

./config/opendkim/keys:
ruzinski.com

./config/opendkim/keys/ruzinski.com:
mail.private  mail.txt

./docker-data:
dms

./docker-data/dms:
config  mail-data  mail-logs  mail-state

./docker-data/dms/config:
dovecot-quotas.cf

./docker-data/dms/mail-data:

./docker-data/dms/mail-logs:
clamav.log  freshclam.log

./docker-data/dms/mail-state:
```
