### ISSUE TITLE
[BUG] Default configuration leads to valid emails being bounced

### ISSUE THREAD

**Issue by emoldtmann** [tomav/docker-mailserver#2253]
### Miscellaneous first checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.

### Affected Component(s)

postfix

### What happened and when does this occur?

```Markdown
Several important mails have been rejected by postfix due to `smtpd_recipient_restrictions = [...] reject_rbl_client zen.spamhaus.org` being in the default configuration.
The spamhaus IP blocklist is way too harsh and has even led to emails coming from Gmail being bounced.
```

### What did you expect to happen?

```Markdown
I expected postfix to accept the emails and letting spamassassin do the handling of possible spam instead
```

### How do we replicate the issue?

```Markdown
Exact replication is not possible due to the dynamic nature of the spamhaus IP blocklist.
Searching the postfix logs for `blocked using zen.spamhaus.org` will possibly yield some results of bounced valid emails
```

### DMS version

latest

### What operating system is DMS running on?

Linux

### What instruction set architecture is DMS running on?

x86_64 / AMD64

### What container orchestration tool are you using?

Docker Compose

### docker-compose.yml

```yaml
mail:
    image: docker.io/mailserver/docker-mailserver:latest
    hostname: mail
    domainname: ...
    container_name: mail
    privileged: true
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - maildir:/var/mail
      - ./mail/mailstate:/var/mail-state
      - ./mail/config:/tmp/docker-mailserver/
      - nginx-proxy-certs:/etc/letsencrypt/live:ro
    environment:
      - VIRTUAL_HOST=...
      - LETSENCRYPT_HOST=...
      - LETSENCRYPT_EMAIL=...
      - SSL_TYPE=letsencrypt
      - ENABLE_SPAMASSASSIN=1
      - SPAMASSASSIN_SPAM_TO_INBOX=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
    cap_add:
      - NET_ADMIN
    restart: always
    env_file:
      - ./mail/global.env
    dns:
      - 9.9.9.9
      - 8.8.8.8
      - 1.1.1.1
      - 1.0.0.1
```

### Relevant log output

```shell
Oct 18 11:16:25 mail postfix/smtpd[18089]: NOQUEUE: reject: RCPT from mta.link.dach-hellofresh.com[161.71.37.172]: 554 5.7.1 Service unavailable; Client host [161.71.37.172] blocked using zen.spamhaus.org; from=<bounce-14621_HTML-12177489-261558-500009989-1205@bounce.link.dach-hellofresh.com> to=<...> proto=ESMTP helo=<mta.link.dach-hellofresh.com>
```

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution
