### ISSUE TITLE
[BUG] instructions don't quite work under Unbuntu Linux

### ISSUE THREAD

**Issue by goblimey** [tomav/docker-mailserver#2254]
### Miscellaneous first checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.

### Affected Component(s)

readme.md

### What happened and when does this occur?

```Markdown
I installed the latest docker-compose as suggested and downloaded the docker-compose.yml.  It specifies version 3.8 at the top.  I ran the first docker command to create an email address, then ran the second to bring up the server permanently:


docker-compose up -d mailserver
```

I get an error saying that the version in the docker-compose.yml is wrong (see log)

Cranking the version down to 3.5 fixes the error.
```


### What did you expect to happen?

```Markdown
I guess this issue may be caused by different versions in different operating systems - I presume that the supplied docker-compose.yml has been tested and works in some environments.  It would be useful if it could be general-purpose.  If that's not possible then some guidance on this issue would be handy.
```

### How do we replicate the issue?

```Markdown
1. install the mail server on a clean ubuntu server.
2. docker-compose up -d mailserver
3.
...
```

### DMS version

latest

### What operating system is DMS running on?

Linux

### What instruction set architecture is DMS running on?

x86_64 / AMD64

### What container orchestration tool are you using?

Docker Compose

### docker-compose.yml

```yaml
version: '3.8'

services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: mailserver
    hostname: mail
    domainname: goblimey.com
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - ./docker-data/dms/mail-data/:/var/mail/
      - ./docker-data/dms/mail-state/:/var/mail-state/
      - ./docker-data/dms/mail-logs/:/var/log/mail/
      - ./docker-data/dms/config/:/tmp/docker-mailserver/
      - /etc/letsencrypt:/etc/letsencrypt
      - /etc/localtime:/etc/localtime:ro
    environment:
      - SSL_TYPE=letsencrypt
      - ENABLE_SPAMASSASSIN=1
      - SPAMASSASSIN_SPAM_TO_INBOX=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=1
      - ENABLE_SASLAUTHD=0
      - ONE_DIR=1
      - DMS_DEBUG=0
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    restart: always
```

### Relevant log output

```shell
ERROR: Version in "./docker-compose.yml" is unsupported. You might be seeing this error because you're using the wrong Compose file version. Either specify a supported version (e.g "2.2" or "3.3") and place your service definitions under the `services` key, or omit the `version` key and place your service definitions at the root of the file to use version 1.
```

### Code of conduct

- [X] I have read this project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree
- [X] I have read the [README](https://github.com/docker-mailserver/docker-mailserver/blob/master/README.md) and the [documentation](https://docker-mailserver.github.io/docker-mailserver/edge/) and I searched the [issue tracker](https://github.com/docker-mailserver/docker-mailserver/issues?q=is%3Aissue) but could not find a solution

### Improvements to this form?

```Markdown
The "what level of experience" dropdown shows me only four options, all for people with little experience.  (It may be that there are more but the browser is not displaying them.  This is using Chrome under Ubuntu linux.)
```
