### ISSUE TITLE
SMTP will not connect

### ISSUE THREAD

**Issue by Anthony-Tatowicz** [tomav/docker-mailserver#269]
I need some guide on getting outgoing mail to work. I have looked through all the docs and wiki and can't find anything. I can run the container and connect to the server and even receive mail, but when sending it always fails, but there is no logs on the server side like it can't even connect, but the proper ports (25, 587) are open and the container is running.

**Comment by tomav** [comment]
If you even don't see a connection, you have another problem.
When you say "ports are open" it's because you configured your firewall to, or because you can telnet the server on port 25 and 587. If you can telnet from the host you're trying to send emails from, you will have something in `/var/log/mail/mail.log`.

Other question, do you recently change your DNS configuration?

**Comment by Anthony-Tatowicz** [comment]
Well the connection times out on port 25 and there is no log of connection with smtp, but imap works. I am not sure where I'm going wrong on the server 25 and 587 accepts connections from all ips and DNS works fine for imap, so everything seems to be correctly routed. I don't know what could be blocking the smtp traffic? This is also hosted remote on a virtual server, so there should be no blacklist or port restrictions.

**Comment by Anthony-Tatowicz** [comment]
```
version: '2'

services:
  mail:
    image: tvial/docker-mailserver:latest
    # build: .
    hostname: mail 
    domainname: fakedomain.com
    container_name: mail
    ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
    volumes:
    - ./mail/:/var/mail
    - ./config/:/tmp/docker-mailserver/
    - /etc/letsencrypt/:/etc/letsencrypt/
    environment:
    - ENABLE_FAIL2BAN=1
    - SSL_TYPE=letsencrypt
    cap_add:
    - NET_ADMIN

volumes:
  maildata:
    driver: local
```

Here is the compose, certs work DNS is is an `@ MX mail.fakedomain.com` and the A record points the the proper IP the DKIM is `@ TXT <key> for  fakedomain.com`
