### ISSUE TITLE
Allow Amavis configuration to be overriden

### ISSUE THREAD

**Issue by keslerm** [tomav/docker-mailserver#298]
While trying to get this running on a kubernetes cluster I ran into a problem where kubernetes will not allow you to define a hostname for a pod/container. This obviously breaks a few things.

1. The postfix configuration is fairly easy to fix, you can just define the hostname info in the override file.
2. Dovecot does not generally need a hostname but I found it broke without adding in a setting `postmaster_address=email@address.com` to the dovecot.conf - again easy to mend with an override file but seems weird that I would need to.
3. The problem child is Amavis, it tries to use `hostname` to get the hostname and obviously that will fail because it will not be a FQDN. You can easily fix this with a setting but there's no amavis override file.

1 is easy I don't think it needs a change, 2 is weird but i don't think it needs a change but maybe just a note in the wiki

3 will require a change which will allow the Amavis config files to be overridden. This should be pretty easy because Amavis provides a place to store user configuration (`/etc/amavis/conf.d/50-user`).

The only other thing I think would be maybe a wiki entry on running in Kubernetes with the config.

**Comment by keslerm** [comment]
One caveat is that Amavis config files are perl files so it is structured a specific way. I'm partial to requiring a user to provide the entire config file to copy rather than do any injecting into an existing file.

I figure if someone is needing to expand the Amavis config file they are probably aware of what it needs to look like.

**Comment by tyranron** [comment]
Please, look at parameter `subdomain` at [v1.PodSpec](http://kubernetes.io/docs/api-reference/v1/definitions/#_v1_podspec).
For me it resolved the relevant issue.

Example:
```yaml
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: mail-server
  namespace: kube-system
  labels:
    k8s-app: mail-server
    kubernetes.io/cluster-service: 'true'
    version: 'v2'
spec:
  replicas: 1
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      k8s-app: mail-server
      version: 'v2'
  template:
    metadata:
      labels:
        k8s-app: mail-server
        kubernetes.io/cluster-service: 'true'
        version: 'v2'
    spec:
      subdomain: mail-server  # <-- here it is
      containers:
        - name: docker-mailserver
          image: tvial/docker-mailserver:v2
          imagePullPolicy: Always
          ports:
            - name: smtp
              containerPort: 25
            - name: smtp-msa
              containerPort: 587
            - name: imap
              containerPort: 143
            - name: imap-secure
              containerPort: 993
          volumeMounts:
            - name: config
              mountPath: /tmp/docker-mailserver
            - name: maildata
              mountPath: /var/mail
      volumes:
        - name: config
          configMap:
            name: mail-server.config
        - name: maildata
          emptyDir: {}
```

After that all containers of your pod will have hostname as FQDN in Kubernetes DNS style `<hostname>.<subdomain>.<pod namespace>.svc.<cluster domain>`.
