### ISSUE TITLE
bug report: Upgrading to v11 to v12

### ISSUE THREAD

**Issue by marios88** [tomav/docker-mailserver#3395]
### 📝 Preliminary Checks

- [X] I checked that all ports are open and not blocked by my ISP / hosting provider.
- [X] I know that SSL errors are likely the result of a wrong setup on the user side and not caused by DMS itself. I'm confident my setup is correct.
- [X] I searched the issue tracker but was unable to find my issue.
- [X] I have read:  
  - The [extended documentation in general](https://docker-mailserver.github.io/docker-mailserver/latest/) but found nothing to resolve the issue;
  - The [documentation on debugging](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/), tried the proposed steps to debug the problem, but was still unable to resolve the issue;
  - This project's [Code of Conduct](https://github.com/docker-mailserver/docker-mailserver/blob/master/CODE_OF_CONDUCT.md) and I agree;
  - The [documentation about filing a bug report](https://docker-mailserver.github.io/docker-mailserver/latest/contributing/issues-and-pull-requests/#filing-a-bug-report).

### 👀 What Happened?

- Upgrade from v11 to v12
- Update env file
- Attempt to send email
- Got error

### 👟 Reproduction Steps

- Upgrade from v11 to v12
- Update env file
- Attempt to send email

### 🐋 DMS Version

v12.1.0

### 💻 Operating System and Architecture

Debain 11 x86_64

### ⚙️ Container configuration files

```yml
mail:
    image: docker.io/mailserver/docker-mailserver:latest
    container_name: ${CONTAINER_NAME}
    # If the FQDN for your mail-server is only two labels (eg: example.com),
    # you can assign this entirely to `hostname` and remove `domainname`.
    hostname: ${HOSTNAME}
    domainname: ${DOMAINNAME}
    env_file: ./mailserver/mailserver.env
    # More information about the mail-server ports:
    # https://docker-mailserver.github.io/docker-mailserver/edge/config/security/understanding-the-ports/
    # To avoid conflicts with yaml base-60 float, DO NOT remove the quotation marks.
    ports:
      - "0.0.0.0:25:25"    # SMTP  (explicit TLS => STARTTLS)
      - "0.0.0.0:143:143"  # IMAP4 (explicit TLS => STARTTLS)
      - "0.0.0.0:465:465"  # ESMTP (implicit TLS)
      - "0.0.0.0:587:587"  # ESMTP (explicit TLS => STARTTLS)
      - "0.0.0.0:993:993"  # IMAP4 (implicit TLS)
    volumes:
      - "/home/base/docker-volumes/mail/data/:/var/mail/"
      - "/home/base/docker-volumes/mail/mailstate/:/var/mail-state/"
      - "/home/base/docker-volumes/mail/config/:/tmp/docker-mailserver/"
      - "/home/base/docker-volumes/etc/letsencrypt/:/etc/letsencrypt/:ro"
      - "/etc/localtime:/etc/localtime:ro"
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: "ss --listening --tcp | grep -P 'LISTEN.+:smtp' || exit 1"
      timeout: 3s
      retries: 0
    logging:
      driver: "json-file"
      options:
        max-size: "100M"
        max-file: "1"
```

### 📜 Relevant log output

```Text
DOMAINNAME=xxx postfix/submission/smtpd[2164]: Anonymous TLS connection established from unknown[172.18.0.1]: TLSv1.3 with cipher TLS_AES_256_GCM_SHA384 (256/256 bits) key-exchange X25519 server-signature RSA-PSS (2048 bits) server-digest SHA256
Jun 14 15:49:58 mail
DOMAINNAME=xxx postfix/submission/smtpd[2164]: warning: SASL: Connect to /dev/shm/sasl-auth.sock failed: No such file or directory
Jun 14 15:49:58 mail
DOMAINNAME=xxx postfix/submission/smtpd[2164]: fatal: no SASL authentication mechanisms
Jun 14 15:49:59 mail
DOMAINNAME=xxx postfix/master[782]: warning: process /usr/lib/postfix/sbin/smtpd pid 2164 exit status 1
Jun 14 15:49:59 mail
DOMAINNAME=xxx postfix/master[782]: warning: /usr/lib/postfix/sbin/smtpd: bad command startup -- throttling
```
