### ISSUE TITLE
outbound email works fine ... inbound bounces : postfix/smtpd  NOQUEUE: reject: RCPT from 

### ISSUE THREAD

**Issue by scottstensland** [tomav/docker-mailserver#353]
outgoing emails work just fine : 

swaks -server mydomain.com:587 -tls --auth-user stens --auth-password mypwd   --to otherperson@gmail.com  --from  stens@mydomain.com

similarily sending outgoing email using nodejs client is OK too with env var

export MAIL_URL=smtp://stens:mypwd@mydomain.com:587/?debug=true

However I get a bounce back from external email accounts trying to send incoming email ... here is server log during inbound attempt which gets bounced back

```
/opt/code/github.com/tomav/docker-mailserver # docker-compose up

Recreating mail
Attaching to mail
mail    | Checking file line endings
mail    | Regenerating postfix 'vmailbox' and 'virtual' for given users
mail    | user 'stens' for domain 'stens' with password '********'
mail    | DKIM keys added for: mydomain.com
mail    | Changing permissions on /etc/opendkim
mail    | Postfix configurations
mail    | Adding container ip in my networks
mail    | Loaded 'config/postfix-main.cf'
mail    | ==> Warning: 'SASL_PASSWD' is not provided. /etc/postfix/sasl_passwd not created.
mail    | Fixing /var/mail permissions
mail    | Creating /etc/mailname
mail    | Configuring Spamassassin
mail    | Starting daemons
mail    |  * Starting enhanced syslogd rsyslogd
mail    |    ...done.
mail    | Sieve management enabled
mail    |  * Starting dovecot services
mail    | Adding file "dovecot.cf" to the Dovecot configuration
mail    |  * Starting ClamAV daemon clamd 
mail    |    ...done.
mail    | Starting amavisd: amavisd-new.
mail    | Starting OpenDKIM: opendkim.
mail    | Starting OpenDMARC: opendmarc.
mail    |  * Starting Postfix Mail Transport Agent postfix
mail    |    ...done.
mail    | Listing users
mail    | stens
mail    | Starting...
mail    | Oct 12 22:13:43 mail amavis[491]: Internal decoder for .tnef
mail    | Oct 12 22:13:43 mail amavis[491]: Found decoder for    .exe  at /usr/bin/arj
mail    | Oct 12 22:13:43 mail amavis[491]: Using primary internal av scanner code for ClamAV-clamd
mail    | Oct 12 22:13:43 mail amavis[491]: Found secondary av scanner ClamAV-clamscan at /usr/bin/clamscan
mail    | Oct 12 22:13:43 mail amavis[491]: Deleting db files  in /var/lib/amavis/db
mail    | Oct 12 22:13:43 mail amavis[491]: Creating db in /var/lib/amavis/db/; BerkeleyDB 0.54, libdb 5.3
mail    | Oct 12 22:13:43 mail opendkim[498]: OpenDKIM Filter v2.9.1 starting (args: -x /etc/opendkim.conf -u opendkim -P /var/run/opendkim/opendkim.pid)
mail    | Oct 12 22:13:43 mail opendmarc[509]: OpenDMARC Filter v1.2.0 starting (args: -c /etc/opendmarc.conf -u opendmarc -P /var/run/opendmarc/opendmarc.pid -p inet:54321@localhost)
mail    | Oct 12 22:13:43 mail opendmarc[509]: trusted authentication services: mail.mydomain.com
mail    | Oct 12 22:13:44 mail postfix/master[1320]: daemon started -- version 2.11.0, configuration /etc/postfix


mail    | Oct 12 22:23:00 mail postfix/smtpd[1330]: connect from nm10-vm9.bullet.mail.ir2.yahoo.com[212.82.96.161]
mail    | Oct 12 22:23:01 mail postfix/smtpd[1330]: NOQUEUE: reject: RCPT from nm10-vm9.bullet.mail.ir2.yahoo.com[212.82.96.161]: 554 5.7.1 <stens@mydomain.com>: Relay access denied; from=<otheraccount@yahoo.co.uk> to=<stens@mydomain.com> proto=ESMTP helo=<nm10-vm9.bullet.mail.ir2.yahoo.com>
mail    | Oct 12 22:23:01 mail postfix/smtpd[1330]: disconnect from nm10-vm9.bullet.mail.ir2.yahoo.com[212.82.96.161]
```
Here is my config file

```
/opt/code/github.com/tomav/docker-mailserver # cat docker-compose.yml 

version: '2'

services:
  mail:
    # image: tvial/docker-mailserver:latest
    image: stens_mail
    # build: .
    hostname: mail
    domainname: mydomain.com
    container_name: mail
    cap_add:
      - NET_ADMIN
    environment:
      - ENABLE_MANAGESIEVE=1
      - ENABLE_FAIL2BAN=1
      - SA_TAG=2.0
      - SA_TAG2=6.31
      - SA_KILL=6.31
      - SSL_TYPE=letsencrypt
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - maildata:/var/mail
      - ./config/:/tmp/docker-mailserver/
volumes:
  maildata:
    driver: local
```

Is there some setting I am missing to enable incoming emails ?
