### ISSUE TITLE
Easier LetsEncrypt SSL setup

### ISSUE THREAD

**Issue by KyleOndy** [tomav/docker-mailserver#367]
I am not sure if this is even the right place for this discussion, so if not this can be moved somewhere else.

---

Soon the wildcard SSL cert I use for my mail server will expire. I have planned to move to LetsEncrypt at this point. I read the [ssl page](https://github.com/tomav/docker-mailserver/wiki/Configure-SSL) in the wiki and saw that the instructions delegated out to LetsEncrypts's [certbot](https://github.com/certbot/certbot) for cert creation.

While this is a perfectly fine way of doing things; I always like to automate as much as possible. In turn I have put together my own project, [dns-certbot](https://github.com/KyleOndy/dns-certbot/tree/development) (fun stuff on development branch), which handles creating and renewing LetsEncrpy certs via the dns challenge.

`dns-certbot`  is designed as a sidekick container to any service that needs certs generated or renewed. Docker-mailserver is a great candidate.

The docker-compose I use that allows hands off SSL management is as follows

```
version: '2'

services:
  mail:
    image: tvial/docker-mailserver:latest
    hostname: mail
    domainname: ondy.me
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
      - "4190:4190"
    volumes:
      - maildata:/var/mail
      - ./config/:/tmp/docker-mailserver/
      - certs:/etc/letsencrypt/live
    environment:
      - SSL_TYPE=letsencrypt

  dns-certbot:
    image: kyleondy/dns-certbot:latest
    volumes:
      - certs:/certs 
      - ./dehydrated-config:/dehydrated/config:ro
    environment:
      - PROVIDER=route53
      - LEXICON_ROUTE53_ACCESS_KEY=<YOUR KEY HERE>
      - LEXICON_ROUTE53_ACCESS_SECRET=<YOUR SECRET HERE>
      - CERTBOT_DOMAIN=mail.ondy.me

volumes:
  maildata:
    driver: local
  certs:
    driver: local
```

---

I wanted to put this out there in case anyone has some comments, feedback, concerns, etc to this approach.
