### ISSUE TITLE
regexp aliases not working

### ISSUE THREAD

**Issue by electerious** [tomav/docker-mailserver#369]
Hi, I tried to use a regexp alias to receive all emails mailed to `@electerious.com`. Sadly it's not working for me. Mailing to my mailserver account works fine, but anything else returns `Recipient address rejected: User unknown in virtual mailbox table`.
- The `postfix-virtual.cf` file exists in the `config/` folder
- I'm not using any other virtual aliases (= no `postfix-virtual.cf` file)
- File uses the Unix format with `LF` line endings

**console**

```
Oct 30 14:44:38 mail postfix/smtpd[1511]: connect from mail-wm0-f41.google.com[74.125.82.41]
Oct 30 14:44:38 mail postfix/smtpd[1511]: NOQUEUE: reject: RCPT from mail-wm0-f41.google.com[74.125.82.41]: 550 5.1.1 <laudableapps@electerious.com>: Recipient address rejected: User unknown in virtual mailbox table; from=<mygmail@googlemail.com> to=<laudableapps@electerious.com> proto=ESMTP helo=<mail-wm0-f41.google.com>
```

**config/postfix-regexp.cf**

```
/^[\w]+@electerious.com/ tobias@electerious.com
```

**docker-compose.yml**

```
version: '2'
services:
  mail:
    image: tvial/docker-mailserver:latest
    hostname: mail
    domainname: electerious.com
    container_name: mail
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - /srv/mail/data:/var/mail
      - /srv/mail/config:/tmp/docker-mailserver
    environment:
      - ENABLE_FAIL2BAN=1
    cap_add:
      - NET_ADMIN
```
