### ISSUE TITLE
Mail relay does not work when amavis is disabled

### ISSUE THREAD

**Issue by mlegenhausen** [tomav/docker-mailserver#386]
Configuration

```yml
  mailserver:
    build: mailserver/
    hostname: mail
    domainname: example.com
    environment:
      DISABLE_AMAVIS: 1
```

Relay server configuration

```
smtp_sasl_auth_enable = yes
smtp_sasl_password_maps = static:xxx:xxx
smtp_sasl_security_options = noanonymous
smtp_tls_security_level = encrypt
header_size_limit = 4096000
relayhost = [smtp.sendgrid.net]:2525
```

The error message

```
Nov 23 11:06:46 mail postfix/smtp[1013]: connect to 127.0.0.1[127.0.0.1]:10024: Connection refused
Nov 23 11:06:46 mail postfix/smtp[1013]: 3B6EB950: to=<to@example.com>, orig_to=<system@server.com>, relay=none, delay=0.14, delays=0.13/0.01/0/0, dsn=4.4.1, status=deferred (connect to 127.0.0.1[127.0.0.1]:10024: Connection refused)
```

The problem is that `content_filter = smtp-amavis:[127.0.0.1]:10024` is statically set even when amavis is disabled.

Current workaround is to add `content_filter =` to the `postfix-main.cf`.

I think this value needs to be setted depending  amavis is enabled or disabled?
