### ISSUE TITLE
FAQ and Tips: named volumes

### ISSUE THREAD

**Issue by mestaritonttu** [tomav/docker-mailserver#395]
In the FAQ and Tips wiki there is this mention: "You should use a data volume container for /var/mail to persist data." It links to a Medium blog post. The blog post now has an update that **named volumes** should be used instead.

Should the Medium blog post link be replaced with this: https://docs.docker.com/engine/tutorials/dockervolumes/

People are working on improving that tutorial: https://github.com/docker/docker/issues/20465

**Comment by tomav** [comment]
Yep, documentation should be better. If you're comfortable with this topic, do not hesitate to contribute to Wiki and default config.

**Comment by mestaritonttu** [comment]
Sorry, I'm pretty ignorant when it comes to Docker :)

**Comment by tomav** [comment]
I suggest this configuration (tested locally, no deployed to production yet)

```
version: '2'

services:
  mail:
    image: tvial/docker-mailserver:v2
    hostname: mail
    domainname: domain.com
    container_name: mail
    ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
    volumes:
    - maildata:/var/mail
    - mailstate:/var/mail-state
    - ./config/:/tmp/docker-mailserver/
    environment:
    - ENABLE_FAIL2BAN=1
    - ONE_DIR=1
    cap_add:
    - NET_ADMIN

volumes:
  maildata:
    driver: local
  mailstate:
    driver: local
```

We create 2 docker volume to manager `/var/mail` and `/var/mail-state` (assuming `ONE_DIR=1`).
Start the container, create a dummy file in both directories.
Stop the container, remove (=delete) it.
Re-start it.
Your 2 dummy files should be kept.

cc @kbeaugrand
