### ISSUE TITLE
SSL Support

### ISSUE THREAD

**Issue by kbeaugrand** [tomav/docker-mailserver#417]
Hi, 

I'm using SSL support with letsencrypt for my mail server with your container and I've got an error with SSL. 

When trying connect to secured communication I encounter an SSL handshake failure on SMPTS ports (465, 587). 

```
openssl s_client -connect mail.domain.net:587
CONNECTED(00000003)
4294956672:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:s23_clnt.c:794:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 7 bytes and written 306 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID:
    Session-ID-ctx:
    Master-Key:
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1482322456
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
```

But this works fine with IMAPS port (993).
```
openssl s_client -connect mail.domain.net:993
CONNECTED(00000003)
depth=2 O = Digital Signature Trust Co., CN = DST Root CA X3
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = Let's Encrypt Authority X3
verify return:1
depth=0 CN = mail.domain.net
verify return:1
---
Certificate chain
 0 s:/CN=mail.domain.net
   i:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
 1 s:/C=US/O=Let's Encrypt/CN=Let's Encrypt Authority X3
   i:/O=Digital Signature Trust Co./CN=DST Root CA X3
---

*** OMMITTED FOR BREVITY***

* OK [CAPABILITY IMAP4rev1 LITERAL+ SASL-IR LOGIN-REFERRALS ID ENABLE IDLE AUTH=PLAIN AUTH=LOGIN] Dovecot (Ubuntu) ready.
read:errno=0
```
Here is an extract of my container configuration: 
```
volumes:
  maildata:
    driver: local
services:
  server:
    image: tvial/docker-mailserver:latest
    hostname: mail
    environment:
      DISABLE_AMAVIS: '1'
      DISABLE_CLAMAV: '1'
      ENABLE_FAIL2BAN: '1'
      ENABLE_FETCHMAIL: '0'
      ENABLE_LDAP: '1'
      ENABLE_MANAGESIEVE: '1'
      ENABLE_POP3: '1'
      ENABLE_SASLAUTHD: '1'
      LDAP_BIND_DN: cn=admin,dc=domain,dc=net
      LDAP_BIND_PW: XXXX
      LDAP_SEARCH_BASE: dc=domain,dc=net
      LDAP_SERVER_HOST: ldap
      ONE_DIR: '1'
      PERMIT_DOCKER: network
      POSTMASTER_ADDRESS: postmaster@domain.net
      SASLAUTHD_LDAP_BIND_DN: cn=admin,dc=domain,dc=net
      SASLAUTHD_LDAP_FILTER: (&(|(uid=%u)(mail=%u))(objectClass=CourierMailAccount))
      SASLAUTHD_LDAP_PASSWORD: XXXXXX
      SASLAUTHD_LDAP_SEARCH_BASE: dc=domain,dc=net
      SASLAUTHD_LDAP_SERVER: ldap
      SASLAUTHD_MECHANISMS: ldap
      SA_KILL: '6.31'
      SA_TAG: '2.0'
      SA_TAG2: '6.31'
      SSL_TYPE: letsencrypt
      VIRUSMAILS_DELETE_DELAY: '30'
    external_links:
    - Authentication/slapd-server:ldap
    volumes:
    - maildata:/var/mail
    - /etc/letsencrypt:/etc/letsencrypt 
```

Regards,
