### ISSUE TITLE
Connection refused after starting docker container

### ISSUE THREAD

**Issue by Rubytastic2** [tomav/docker-mailserver#449]
Unable to connect to the docker mailserver.
We disabled the port 25 , would this cause issues? port 25 is pop3 we would like to disable 
pop3.

Could someone please explain a bit more how to get this up and running?
I understand that the mail data is stored outside the docker container image on the host itself? 
We use CentOS

**Comment by tomav** [comment]
Hi @Rubytastic2, port `25` is SMTP.
POP3 is disabled by default (port `110').
Without SMTP, it won't work. you probably should have a look to the [wiki](https://github.com/tomav/docker-mailserver/wiki) where more things are explained.

Regarding data, its like every docker container, the choice is yours. Locally in the container (no volume), using shared folder with the host, using docker volumes (recommended). In all cases, think about backups as soon as you start.

Hope this helps. Feel free to close if you found your information, or let us know how we can help.

**Comment by Rubytastic2** [comment]
Thank you Tomav;

Im following exactly instructions with new docker-compose

```
    hostname: mail
    domainname: domain.com
    container_name: mail
```

hostname is this the hostname of the mailserver or is it where it connects to like 'mail.mydomain.ltd' was not clear from reading the readme.

**Comment by tomav** [comment]
You have to configure that with you own domain/sub-domain: `hostname.domainname`.
Hostname is usually `mail` but it can be whatever you want.

**Comment by Rubytastic2** [comment]
ok thank you im currently trying to get it up and running,
docker image runs but cannot connect from apple mail. I add as subdomain mail to my domain.ltd probably that is the problem.

**Comment by Rubytastic2** [comment]
I can now ping on mail.mydomain.ltd but apple mail still refuses anything else I need to do?
I added the email account and password to the config file like

```
docker run --rm \
  -e MAIL_USER=info@mydomain.ltd \
  -e MAIL_PASS=LKsMfBsxCcVsBVLqiU4tXLJ7dQJyRtYXAEpzXL2eab94aE4Q9QZpy7zLCj3LU3Yu \
  -ti tvial/docker-mailserver:latest \
  /bin/sh -c 'echo "$MAIL_USER|$(doveadm pw -s SHA512-CRYPT -u $MAIL_USER -p $MAIL_PASS)"' >> config/postfix-accounts.cf
```

This is in 
```
/opt/mailserver/config
```
I then run the docker image

Still it says unable to verify password

In advanched settings i can choose a TLS certificate to connect to the mailserver.
Perhaps its an idea for a write up on how to configure mail clients in the readme this is not really clear

**Comment by Rubytastic2** [comment]
Sucesfully managed all the steps but it Throws an:

```
ERROR: Named volume "letsencrypt:/tmp/letsencrypt:rw" is used in service "mail" but no declaration was found in the volumes section.
```

```
version: '2'

services:
  mail:
    image: tvial/docker-mailserver:2.1
    hostname: mail
    domainname: mydomain.ltd
    container_name: mail
    ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
    volumes:
    - maildata:/var/mail
    - mailstate:/var/mail-state
    - ./config/:/opt/mailserver/
    - letsencrypt:/tmp/letsencrypt
    environment:
    - ENABLE_SPAMASSASSIN=1
    - ENABLE_CLAMAV=1
    - ENABLE_FAIL2BAN=1
    - ONE_DIR=1
    - DMS_DEBUG=0
    - SSL_TYPE=letsencrypt
    cap_add:
    - NET_ADMIN

volumes:
  maildata:
    driver: local
  mailstate:
    driver: local
```
