### ISSUE TITLE
bug report: spam rejection issues

### ISSUE THREAD

**Issue by MarcS1975** [tomav/docker-mailserver#4495]
### 📝 Preliminary Checks

- [x] I tried searching for an existing issue and followed the [debugging docs](https://docker-mailserver.github.io/docker-mailserver/latest/config/debugging/) advice, but still need assistance.

### 👀 What Happened?

An external (known) user michael_lastname@hotmail.com is sending an email to 3 of my users running on 2 domains on my docker mailserver and the email gets rejected as spam. Strange things is that I have no trace of the rejection in mailserver. The sender only tells me that my server is rejecting his emails (his rejection message is below). 
The user is a legitimate sender that I had email exchange in the past.
Can anyone see the issue? Is this rejection caused by my Amavis and is it even caused by my server or any other server/software? Why am I not seeing anything in my logs?

Recipients on my server below. The issue has so far only happened for this on sender.
```
name1anis@domnameinvest.com" <name1anis@domnameinvest.com>
CC: "name2@domnameluxgp.com" <name2@domnameluxgp.com>,
        "name3@domnameinvest.com" <name3@domnameinvest.com>

```

### 👟 Reproduction Steps

```
Diagnostic information for administrators:

Generating server: DS7PR02MB9457.namprd02.prod.outlook.com

name1anis@domnameinvest.com
Remote server returned '550 5.7.520 Message blocked because it contains content identified as spam. AS(4810)'

name2@domnameluxgp.com
Remote server returned '550 5.7.520 Message blocked because it contains content identified as spam. AS(4810)'

name3@domnameinvest.com
Remote server returned '550 5.7.520 Message blocked because it contains content identified as spam. AS(4810)'

Original message headers:

Received: from CYXPR02MB10228.namprd02.prod.outlook.com (2603:10b6:930:dd::8)
 by DS7PR02MB9457.namprd02.prod.outlook.com (2603:10b6:8:e4::17) with
 Microsoft SMTP Server (version=TLS1_2,
 cipher=TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384) id 15.20.8792.23; Thu, 29 May
 2025 20:03:18 +0000
Received: from CYXPR02MB10228.namprd02.prod.outlook.com
 ([fe80::fae8:7d97:6c26:7ad0]) by CYXPR02MB10228.namprd02.prod.outlook.com
 ([fe80::fae8:7d97:6c26:7ad0%5]) with mapi id 15.20.8769.025; Thu, 29 May 2025
 20:03:18 +0000
Content-Type: application/ms-tnef; name="winmail.dat"
Content-Transfer-Encoding: binary
From: Michael lastname <michael_lastname@hotmail.com>
To: "name1anis@domnameinvest.com" <name1anis@domnameinvest.com>
CC: "name2@domnameluxgp.com" <name2@domnameluxgp.com>,
        "name3@domnameinvest.com" <name3@domnameinvest.com>
Subject: RE: Additional Documents 
Thread-Topic: Additional Documents 
Thread-Index: AQHbztPXGrtBheFNX0mvzylFt1ZIlbPqCk3A
Date: Thu, 29 May 2025 20:03:18 +0000
Message-ID: <CYXPR02MB102284DC6AE2C2B6EF45F86418A66A@CYXPR02MB10228.namprd02.prod.outlook.com>
References: <003b01dbcdb3$928d85b0$b7a89110$@domnameluxgp.com>
 <20250525103742.B215A156B62@mail.mymailserver.com>
 <CYXPR02MB10228E9184928E5BD5B5D8F7E8A9AA@CYXPR02MB10228.namprd02.prod.outlook.com>
 <2dee998e6c2f056c291c814277ad0363@domnameinvest.com>
In-Reply-To: <2dee998e6c2f056c291c814277ad0363@domnameinvest.com>
Accept-Language: en-US
Content-Language: en-GB
X-MS-Has-Attach:
X-MS-TNEF-Correlator: <CYXPR02MB102284DC6AE2C2B6EF45F86418A66A@CYXPR02MB10228.namprd02.prod.outlook.com>
MIME-Version: 1.0
X-MS-PublicTrafficType: Email
X-MS-TrafficTypeDiagnostic: CYXPR02MB10228:EE_|DS7PR02MB9457:EE_
Return-Path: michael_lastname@hotmail.com
X-MS-Office365-Filtering-Correlation-Id: 254d46d3-2e04-4527-8c4b-08dd9eebdabc
X-MS-Exchange-SLBlob-MailProps:
 9IecXKUgicB0Vgu95vFSoXNdCFmhIzagB4MvQOpO5cmqqO6QZVQakFbWfiHlU2d/+LOm4BYM3NdsPkHMRyMHWkmFDX3URACgDQWks2G85L3pEElIRysuY8NpSxgl8Jjx6W6dLr7RWZxoq7h3/tBCSmGNd4giFgVgc/Wzjmp7m19Cd4Plrd1mGqt8DoE1V4z/u4EaxYvMXl8gLlopJqLTxYiKOyEQoBmVDboS3fZa2QfIcxuSMUYSvTxKHvROOr8XsgVQiMm08VxUnOyLeC75mML3Yr+6VzK4LbXe6iv4dk94lPaHnutuO9Xl2ZHevzaQzQT3AM1wHe4/ByHhh46CzkxWMCNUfGYfDDycU5lyl0Wa34zXsTwML6hkfwC90vaZFf94U2yDlbsUG7FDBPODdyCnB3+Xo44IfMan7ellhuEMTKcSfI21KZU3cyCSqVv++ILZmtpBy8pYC3NsGrpAe5gD6pcJb8rJHIeLX4n1qmGA5glwkBU/5DfV7wz7f9ZgTjENSNoiZDWTlXRU/t5UTmmuA6TFYWap0pUMRRJS3xQD/OMG1KR5/Hi0xzUBYDlBhuynCqSr9lpidRgkROyv0oYdbVM3WK9mGyrjAdUTSQXn8qTM9DAoTlCijl3Tmz+UdzSJQszkLNGlkBC7ms6TDL4FU23kzB2jHyvDqycDEcKJIuFPt22tES5bmTvkstTyhtSBmu7x3QyCIB5FBh+LgTDz4wBProAum7OoxdwiGWNR2m/hiwaCSw==
X-Microsoft-Antispam:
 BCL:0;ARA:14566002|7092599006|461199028|41001999006|12121999007|15080799009|8062599006|8060799009|9400799033|19110799006|12050799012|440099028|3412199025|102099032|10035399007|2015499007;
X-Microsoft-Antispam-Message-Info:
        =?us-ascii?Q?PH4XXkMRe3sza1/CvWNGXvMTX8eZAZX1FbwHuRWYUA7tFYvJG3Z6pjtovzVN?=

```

### 🐋 DMS Version

v15.0.2

### 💻 Operating System and Architecture

Debian 11

### ⚙️ Container configuration files

```yml
services:
  mailserver:
    image: docker.io/mailserver/docker-mailserver:latest
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    container_name: mailserver
    # Provide the FQDN of your mail server here (Your DNS MX record should point to this value)
    # added one vol for import aj
    hostname: mail.myserver.com
    ports:
      - "26:25"
      - "143:143"
      - "587:587"
      - "993:993"
      - "465:465"
    volumes:
      - /srv/dev-disk-by-uuid-786fbfe4-2782-4b41-b28a-9ec8130edb8d/DockerappsHot/myserverOMVv2/mail-data/:/var/mail/
      - /srv/dev-disk-by-uuid-786fbfe4-2782-4b41-b28a-9ec8130edb8d/DockerappsHot/myserverOMVv2/mail-state/:/var/mail-state/
      - /srv/dev-disk-by-uuid-786fbfe4-2782-4b41-b28a-9ec8130edb8d/DockerappsHot/myserverOMVv2/mail-logs/:/var/log/mail/
      - /srv/dev-disk-by-uuid-786fbfe4-2782-4b41-b28a-9ec8130edb8d/DockerappsHot/myserverOMVv2/config/:/tmp/docker-mailserver/
      - /etc/localtime/:/etc/localtime:ro
      - /srv/Braid/DockerappsHot/Caddy/caddy_data/caddy/certificates/acme-v02.api.letsencrypt.com-directory/mail.mymail24.com/mail.mymail24.com.crt:/etc/letsencrypt/live/mail.mymail24.com/fullchain.pem
      - /srv/Braid/DockerappsHot/Caddy/caddy_data/caddy/certificates/acme-v02.api.letsencrypt.com-directory/mail.mymail24.com/mail.mymail24.com.key:/etc/letsencrypt/live/mail.mymail24.com/privkey.pem
    environment:
      - POSTFIX_MESSAGE_SIZE_LIMIT=20480000
      - POSTFIX_MAILBOX_SIZE_LIMIT=0
      - LOG_LEVEL=warn #by AJ
      - SPOOF_PROTECTION=0 
      - PFLOGSUMM_TRIGGER=logrotate # by AJ
      - PFLOGSUMM_RECIPIENT=nmax3@rec44.win # by AJ
      - LOGWATCH_INTERVAL=weekly # by AJ
      - LOGWATCH_RECIPIENT=nmax3@rec44.win
      - LOGROTATE_INTERVAL=weekly
      - REPORT_RECIPIENT=nmax3@rec44.win
      - ENABLE_SPAMASSASSIN=0
      - ENABLE_SPAMASSASSIN_KAM=0
      - SPAMASSASSIN_SPAM_TO_INBOX=1
      - ENABLE_DNSBL=1
      - ENABLE_POLICYD_SPF=1
      - ENABLE_CLAMAV=0 # by AJ
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=0
      - SSL_TYPE=letsencrypt
    restart: always
    stop_grace_period: 1m
    cap_add:
      - NET_ADMIN
```

### 📜 Relevant log output

```Text

```
