### ISSUE TITLE
Logs are not printed anymore

### ISSUE THREAD

**Issue by theomega** [tomav/docker-mailserver#467]
I have the issue that after some restarts of the docker container, I don't get any usable outputs on `docker log [container]` anymore. Also the `/var/log/mail/mail.log` inside the container contains the same information and is not growing:

```
#
#
# docker-mailserver
#
#

Initializing setup
Checking configuration
Configuring mail server
Starting Misc
Starting mail server

#
# mail.dbruhn.de is up and running
#

tail: unrecognized file system type 0x794c7630 for '/var/log/mail/mail.log'. please report this to bug-coreutils@gnu.org. reverting to polling

```

The last message is only a warning, so for some reason, no messages are appended anymore. The strange this is that it looks like the server is still working, but I would feel better if I could get the logs of postfix back. What could be the issue?

**Comment by theomega** [comment]
I tried to debug this:
1. Restarting postfix inside the container is not even possible (this is because the init script is not able to detect that postfix is running although it is. Reason is that the init script makes some wrong assumption how /proc works)
2. Killing postfix by hand (kill [pid]) and then restarting it doesn't fix the issue.

I tried to trace this down and found an entry for rsyslogd in /etc/rsyslog.d/postfix:
```
# Create an additional socket in postfix's chroot in order not to break
# mail logging when rsyslog is restarted.  If the directory is missing,
# rsyslog will silently skip creating the socket.
$AddUnixListenSocket /var/spool/postfix/dev/log
```

After I deleted this socket, restarted `rsyslogd` and `postfix`, logging starts to work again.

Now my (weak) theory starts: Rsyslogd will not overwrite this socket. As the `/var/spool` is on a volume, on restarts of the container, the socket will always be there. For some reasons, the socket is not connected to rsyslogd, so logging messages from postfix never go into rsyslogd and therefore never to the logs.

If my theory is good, it might make sense to delete this file on startup of the container. Not sure though.

**Comment by tomav** [comment]
Can I see you `docker-compose.yml` to try to reproduce the issue? Thanks.

**Comment by theomega** [comment]
Sure, I can. 


```
version: '2'

services:
  mail:
    image: tvial/docker-mailserver:2.1
    hostname: mail
    domainname: dbruhn.de
    container_name: mail
    ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
    - "4190:4190"
    volumes:
    - maildata:/var/mail
    - mailstate:/var/mail-state
    - ./config/:/tmp/docker-mailserver/
    - proxy_certs:/tmp/ssl:ro
    environment:
    - ENABLE_SPAMASSASSIN=1
    - ENABLE_CLAMAV=1
    - ENABLE_FAIL2BAN=0
    - ENABLE_MANAGESIEVE=1
    - ONE_DIR=1
    - DMS_DEBUG=0
    - SA_TAG=-10000.0
    - SA_TAG2=5
    - SA_KILL=1000
    - POSTMASTER_ADDRESS=postmaster@mail.dbruhn.de
    - SSL_TYPE=manual
    - SSL_CERT_PATH=/tmp/ssl/mail.dbruhn.de/fullchain.pem
    - SSL_KEY_PATH=/tmp/ssl/mail.dbruhn.de/key.pem
    cap_add:
    - NET_ADMIN

volumes:
  maildata:
    driver: local
  mailstate:
    driver: local
  proxy_certs:
    external: true

```
