### ISSUE TITLE
Can't login to mail server

### ISSUE THREAD

**Issue by jalenconner** [tomav/docker-mailserver#479]
I'm on the newest version (2.1) and everything is broken... Trying to login from any local email client just gives me an error about either the email server being unreachable or the username and password being incorrect (depends on the client). I could use some assistance ASAP @tomav  - just let me know what will be helpful for you so you can diagnose...

**Comment by thiesschneider** [comment]
I had the same issue and after removing `--cap-add=NET_ADMIN` it works with my desktop client (apple mail). On iOS i cannot send anything for now.

**Comment by jalenconner** [comment]
@thiesschneider Yep removing `--cap-add=NET_ADMIN` fixed it for me too... I also disabled Fail2Ban for the time being. Would like a permanent solution though!

I'm going to propose tagging this as a bug @tomav

**Comment by jalenconner** [comment]
Would be nice to have this working on an iPhone... It seems the default ports and everything don't work (I'm guessing it has to do with the new STARTTLS requirement)?

**Comment by thiesschneider** [comment]
can you give an update how you get it working?

**Comment by tomav** [comment]
Hi guys, could you give me step to reproduce? (full config and log startup with `DMS_DEBUG=1`).
It will help me to confirm there's a bug and give a lead to resolve it.

I personally use `2.1` in production with OSX and iOS clients and it works.
Are you sure you have been banned by fail2ban?

Thanks.

**Comment by jalenconner** [comment]
@tomav here's my `docker-compose.yml` (undid the changes I mentioned above):
```
version: '2'

services:
  mail:
    image: tvial/docker-mailserver:latest
    hostname: mail
    domainname: dominion-designs.com
    container_name: mail
    restart: always
    ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
    volumes:
    - maildata:/var/mail
    - mailstate:/var/mail-state   
    - ./config/:/tmp/docker-mailserver/
    - /etc/letsencrypt:/etc/letsencrypt
    environment:
    - SSL_TYPE=letsencrypt
    - ENABLE_SPAMASSASSIN=1
    - ENABLE_CLAMAV=1
    - ENABLE_FAIL2BAN=1
    - ONE_DIR=1
    - DMS_DEBUG=1
    cap_add:
    - NET_ADMIN

volumes:
  maildata:
    driver: local
  mailstate:
    driver: local
```
 Attempted to start the Docker container so I could get you log files and now it all works. 🙄 Weird... Must have been a one-time kink. Or maybe I fixed the bug without knowing it. I seriously spent all afternoon trying to get this working and only opened the issue when I couldn't think of anything else to try and debug, so I'm not sure what happened.

I'm going to close this for now since I'm not experiencing the issue right now. Will open if I ever experience it again. Thanks for your assistance and sorry to bother.
