### ISSUE TITLE
ELK not starting in production

### ISSUE THREAD

**Issue by citec** [tomav/docker-mailserver#480]
Hi, I got ELK running in localhost ok, but when I tried to publish it on production, I get this error from elk container:
```
elk_1 | [2017-01-18T09:12:04,094][INFO ][o.e.n.Node               ] [Uegwgym] starting ...
elk_1 | [2017-01-18T09:12:04,186][INFO ][o.e.t.TransportService   ] [Uegwgym] publish_address {172.17.0.6:9300}, bound_addresses {[::]:9300}
elk_1 | [2017-01-18T09:12:04,189][INFO ][o.e.b.BootstrapCheck     ] [Uegwgym] bound or publishing to a non-loopback or non-link-local address, enforcing bootstrap checks
elk_1 | [2017-01-18T09:12:04,190][ERROR][o.e.b.Bootstrap          ] [Uegwgym] node validation exception
elk_1 | bootstrap checks failed
```

I have tried to override /etc/elasticsearch/elasticsearch.yml file, setting `network.bind_host` and other settings, with no result. I also have tried to expose and publish port 9300, same result.

My `docker-compose.yml` file, elk part, looks like this (I have commented some lines so you know what I tried):
```
elk:
    build: elk
    # volumes:
    #     - ./config/elasticsearch.yml:/etc/elasticsearch/elasticsearch.yml
    ports:
        - "5601:5601"  # kibana
        - "9200:9200"  # elasticsearch
        # - "9300:9300"  # elasticsearch
        - "5044:5044"
        - "5000:5000"  # logstash
```
The server has 3 IPs, I tried to publish on specific IP -> no result, also without specifing (as in the shown docker-compose.yml file) -> no result

:/
