### ISSUE TITLE
Swarm Mode

### ISSUE THREAD

**Issue by AndrewMoneronGenex** [tomav/docker-mailserver#487]
Hi

Is this container able to work in swarm mode, since the --hostname param in not supported by docker service create?

**Comment by tomav** [comment]
Hi @AndrewMoneronGenex, you're the first asking for Swarm information 😄 
In the documentation, [it seems supported](https://docs.docker.com/engine/reference/commandline/service_create/).

The best thing to do is to try it out.

**Comment by Berndinox** [comment]
@AndrewMoneronGenex Have a look @ #509

**Comment by Berndinox** [comment]
It does work in swarm, however its not possible to scale the container.. :(


```
  allinone:
    image: tvial/docker-mailserver:2.1
    ports:
      - 25:25
      - 143:143
      - 587:587
      - 993:993
    volumes:
      - maildata:/var/mail
      - mailstate:/var/mail-state
      - config:/tmp/docker-mailserver
      - ssl:/tmp/ssl
    environment:
      - ENABLE_SPAMASSASSIN=1
      - ENABLE_CLAMAV=0
      - ONE_DIR=0
      - ENABLE_FETCHMAIL=0
      - OVERRIDE_HOSTNAME=mail.berndklaus.at
      - POSTMASTER_ADDRESS=admin@berndklaus.at
      - SSL_TYPE=manual
      - DMS_DEBUG=0
      - SSL_CERT_PATH=/tmp/ssl/cert/public.crt
      - SSL_KEY_PATH=/tmp/ssl/private/private.key
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
        delay: 30s
        monitor: 10s
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 10
        window: 60s
    healthcheck:
      test: ["CMD", "curl", "-f", "localhost:143"]
      interval: 20s
      timeout: 10s
      retries: 3
    logging:
      driver: json-file
```
