### ISSUE TITLE
Can send mail but cannot receive mail

### ISSUE THREAD

**Issue by gordanyang** [tomav/docker-mailserver#490]
hi tomav,can you help me?.
the error is:

```
postfix/local[1494]: DFC58114181E: to=<yangtao@mail.finogeeks.club>, relay=local, delay=0.02, delays=0/0/0/0.01, dsn=5.1.1, status=bounced (unknown user: "yangtao")

```
my main.cf ：
```
myhostname = mail.finogeeks.club
mydomain=finogeeks.club
mydestination = $myhostname localhost.$mydomain $mydomain

```
 
```
mail    | Jan 24 12:36:00 mail postfix/smtpd[1482]: connect from m15-66.126.com[220.181.15.66]
mail    | Jan 24 12:36:00 mail postfix/smtpd[1482]: CA0041141765: client=m15-66.126.com[220.181.15.66]
mail    | Jan 24 12:36:00 mail postfix/cleanup[1487]: CA0041141765: message-id=<19901fc8.5492.159d079c474.Coremail.gordanyang@126.com>
mail    | Jan 24 12:36:00 mail opendkim[155]: CA0041141765: m15-66.126.com [220.181.15.66] not internal
mail    | Jan 24 12:36:00 mail opendkim[155]: CA0041141765: not authenticated
mail    | Jan 24 12:36:03 mail postfix/smtpd[1466]: timeout after END-OF-MESSAGE from localhost[127.0.0.1]
mail    | Jan 24 12:36:03 mail postfix/smtpd[1466]: disconnect from localhost[127.0.0.1]
mail    | Jan 24 12:36:04 mail opendkim[155]: CA0041141765: DKIM verification successful
mail    | Jan 24 12:36:04 mail opendkim[155]: CA0041141765: s=s110527 d=126.com SSL
mail    | Jan 24 12:36:04 mail opendmarc[175]: CA0041141765 ignoring Authentication-Results at 0 from mail.finogeeks.club
mail    | Jan 24 12:36:04 mail opendmarc[175]: CA0041141765: 126.com none
mail    | Jan 24 12:36:04 mail postfix/qmgr[1481]: CA0041141765: from=<gordanyang@126.com>, size=2619, nrcpt=1 (queue active)
mail    | Jan 24 12:36:04 mail postfix/smtpd[1482]: disconnect from m15-66.126.com[220.181.15.66]
mail    | Jan 24 12:36:06 mail postfix/smtpd[1493]: connect from localhost[127.0.0.1]
mail    | Jan 24 12:36:06 mail postfix/smtpd[1493]: DFC58114181E: client=localhost[127.0.0.1]
mail    | Jan 24 12:36:06 mail postfix/cleanup[1487]: DFC58114181E: message-id=<19901fc8.5492.159d079c474.Coremail.gordanyang@126.com>
mail    | Jan 24 12:36:06 mail postfix/qmgr[1481]: DFC58114181E: from=<gordanyang@126.com>, size=3194, nrcpt=1 (queue active)
mail    | Jan 24 12:36:06 mail amavis[1422]: (01422-01) Passed CLEAN {RelayedInbound}, [220.181.15.66]:24936 [119.33.99.240] <gordanyang@126.com> -> <yangtao@mail.finogeeks.club>, Queue-ID: CA0041141765, Message-ID: <19901fc8.5492.159d079c474.Coremail.gordanyang@126.com>, mail_id: tQXdmJlGHNzf, Hits: -0.65, size: 2848, queued_as: DFC58114181E, dkim_sd=s110527:126.com, 2146 ms
mail    | Jan 24 12:36:06 mail postfix/smtp[1489]: CA0041141765: to=<yangtao@mail.finogeeks.club>, relay=127.0.0.1[127.0.0.1]:10024, delay=6.7, delays=4.5/0/0.01/2.1, dsn=2.0.0, status=sent (250 2.0.0 from MTA(smtp:[127.0.0.1]:10025): 250 2.0.0 Ok: queued as DFC58114181E)
mail    | Jan 24 12:36:06 mail postfix/qmgr[1481]: CA0041141765: removed
mail    | Jan 24 12:36:06 mail postfix/local[1494]: DFC58114181E: to=<yangtao@mail.finogeeks.club>, relay=local, delay=0.02, delays=0/0/0/0.01, dsn=5.1.1, status=bounced (unknown user: "yangtao")
mail    | Jan 24 12:36:06 mail postfix/cleanup[1487]: E44501141765: message-id=<20170124123606.E44501141765@mail.finogeeks.club>
mail    | Jan 24 12:36:06 mail postfix/bounce[1495]: DFC58114181E: sender non-delivery notification: E44501141765
mail    | Jan 24 12:36:06 mail postfix/qmgr[1481]: E44501141765: from=<>, size=5096, nrcpt=1 (queue active)
mail    | Jan 24 12:36:06 mail postfix/qmgr[1481]: DFC58114181E: removed
mail    | Jan 24 12:36:07 mail postfix/smtp[1496]: Trusted TLS connection established to 126mx02.mxmail.netease.com[220.181.15.143]:25: TLSv1.2 with cipher AES256-GCM-SHA384 (256/256 bits)
mail    | Jan 24 12:36:07 mail postfix/smtp[1496]: E44501141765: to=<gordanyang@126.com>, relay=126mx02.mxmail.netease.com[220.181.15.143]:25, delay=0.46, delays=0/0.01/0.28/0.17, dsn=2.0.0, status=sent (250 Mail OK queued as mx25,K8mowACn02k2SodY_DcoAQ--.12875S3 1485261367)
mail    | Jan 24 12:36:07 mail postfix/qmgr[1481]: E44501141765: removed
mail    | Jan 24 12:39:25 mail postfix/anvil[1485]: statistics: max connection rate 1/60s for (smtp:220.181.15.66) at Jan 24 12:36:00
mail    | Jan 24 12:39:25 mail postfix/anvil[1485]: statistics: max connection count 1 for (smtp:220.181.15.66) at Jan 24 12:36:00
mail    | Jan 24 12:39:25 mail postfix/anvil[1485]: statistics: max cache size 1 at Jan 24 12:36:00
```

** when i set mydestination as blank,there has an other error.**

```
mail    | Jan 24 12:53:15 mail postfix/smtpd[1469]: connect from m15-66.126.com[220.181.15.66]
mail    | Jan 24 12:53:15 mail postfix/smtpd[1469]: NOQUEUE: reject: RCPT from m15-66.126.com[220.181.15.66]: 554 5.7.1 <yangtao@mail.finogeeks.club>: Relay access denied; from=<gordanyang@126.com> to=<yangtao@mail.finogeeks.club> proto=ESMTP helo=<m15-66.126.com>
```

my compose environment:

```
version: '2'

services:
  mail:
    image: tvial/docker-mailserver:2.1
    hostname: mail
    domainname: finogeeks.club
    container_name: mail
    ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
    volumes:
    - maildata:/var/mail
    - mailstate:/var/mail-state
    - ./config/:/tmp/docker-mailserver/
    - ./config/certs:/etc/postfix/certs
    environment:
    - ENABLE_SPAMASSASSIN=1
    - ENABLE_CLAMAV=1
    - ENABLE_FAIL2BAN=1
    - ONE_DIR=1
    - DMS_DEBUG=0
    - SSL_TYPE=manual
    - SSL_CERT_PATH=/tmp/docker-mailserver/ssl/mail.finogeeks.club.pem
    - SSL_KEY_PATH=/tmp/docker-mailserver/ssl/mail.finogeeks.club.key
    - ENABLE_LDAP=1
    - LDAP_SERVER_HOST=***
    - LDAP_SEARCH_BASE=dc=finogeeks,dc=club
    - LDAP_BIND_DN=cn=**
    - LDAP_BIND_PW=***
    - POSTMASTER_ADDRESS=admin@finogeeks.club
    - ENABLE_SASLAUTHD=1
    - SASLAUTHD_MECHANISMS=ldap
    - SASLAUTHD_LDAP_SERVER=***
    - SASLAUTHD_LDAP_SSL=0
    - SASLAUTHD_LDAP_BIND_DN=***
    - SASLAUTHD_LDAP_PASSWORD=***
    - SASLAUTHD_LDAP_SEARCH_BASE=dc=finogeeks,dc=club
    - SASLAUTHD_LDAP_FILTER=(&(mail=%u))
    cap_add:
    - NET_ADMIN

volumes:
  maildata:
    driver: local
  mailstate:
    driver: local
```

LDAP is work.only can not receive mail..
