### ISSUE TITLE
Document LDAP usage / tips in Wiki

### ISSUE THREAD

**Issue by tomav** [tomav/docker-mailserver#491]
@alinmear or someone else?

**Comment by gordanyang** [comment]
LDAP is work。
I connect openLDAP success.
* 1. dovecot-ldap.conf.ext
···
auth_bind = yes
base = ****
dn = ****
dnpass = **
hosts = **.**.**.**
ldap_version        = 3
scope = subtree
pass_attrs          = uid=cn,userPassword=password
pass_filter         = (&(objectClass=posixAccount)(mail=%u))
#user_attrs          =  uidNumber=uid,mailHomeDirectory=home,mailUidNumber=uid,mailGidNumber=gid,mailStorageDirectory=mail
user_attrs = uidNumber=uid,gidNumber=gid
user_filter         = (&(objectClass=posixAccount)(mail=%u))
···

* 2. ldap-users.cf
```
bind             = yes
bind_dn = ***
bind_pw = *
query_filter     = (&(mail=%s))
result_attribute = mail
search_base = *
server_host = *.*.*.*
version          = 3
```

* 3. ldap-aliases.cf
```
bind             = yes
bind_dn = *
bind_pw = *
query_filter     = (&(mail=%s))
result_attribute = mail
search_base = *
server_host = *.*.*.*
version          = 3
```
* 4. compose environment
```
ENABLE_SPAMASSASSIN=1
ENABLE_CLAMAV=1
ENABLE_FAIL2BAN=1
ONE_DIR=1
DMS_DEBUG=0
SSL_TYPE=manual
SSL_CERT_PATH=/tmp/docker-mailserver/ssl/mail.finogeeks.club.pem
SSL_KEY_PATH=/tmp/docker-mailserver/ssl/mail.finogeeks.club.key
ENABLE_LDAP=1
LDAP_SERVER_HOST=*.*.*.*
LDAP_SEARCH_BASE=*
LDAP_BIND_DN=*
LDAP_BIND_PW=*
POSTMASTER_ADDRESS=*
ENABLE_SASLAUTHD=1
SASLAUTHD_MECHANISMS=ldap
SASLAUTHD_LDAP_SERVER=*.*.*.*
SASLAUTHD_LDAP_SSL=0
SASLAUTHD_LDAP_BIND_DN=*
SASLAUTHD_LDAP_PASSWORD=*
SASLAUTHD_LDAP_SEARCH_BASE=*
SASLAUTHD_LDAP_FILTER=(&(mail=%u))
```

**Comment by tomav** [comment]
@gordanyang are you sure you're posting in the right thread? This should go to #490 no?

**Comment by alinmear** [comment]
@tomav, i will take over for the documentation.

**Comment by alinmear** [comment]
@tomav i started to write the wiki page. https://github.com/tomav/docker-mailserver/wiki/Configue-LDAP

At the actual state it is not much, but i will extend it, when i have time. I am trying to cover several basic use cases, such as a docker-compose file for a dovecot setup.

**Comment by emieza** [comment]
Don't know if here is the place, but have an issue with my LDAP configuration. Once solved (or not solved), I will be happy to contribute to the wiki doc. Your work is great and save me lots of time :)

Have three containers, your mailserver:2.2 , osixia's ldap docker and roundcube.

I have that configuration:
```
    mail:
        image: tvial/docker-mailserver:2.2
        hostname: mail
        domainname: example.com
        container_name: mail
        # only needed for fail2ban
        cap_add:
        - NET_ADMIN
        ports:
        - "25:25"
        - "143:143"
        - "587:587"
        - "993:993"
        volumes:
        - "/data/maildata:/var/mail"
        - "/data/mailstate:/var/mail-state"
        - "./config/:/tmp/docker-mailserver/"
        environment:
        - ENABLE_SPAMASSASSIN=1
        - ENABLE_CLAMAV=1
        # - ENABLE_FAIL2BAN=1
        - ENABLE_POSTGREY=1
        - ONE_DIR=1
        - DMS_DEBUG=1
        # ldap integration
        - ENABLE_LDAP=1
        - LDAP_SERVER_HOST=ldap
        - LDAP_BIND_DN=cn=admin,dc=example,dc=com
        - LDAP_BIND_PW=Passw0rd.
        - LDAP_SEARCH_BASE=dc=example,dc=com
        - ENABLE_SASLAUTHD=1
        - SASLAUTHD_LDAP_SERVER=ldap
        - SASLAUTHD_LDAP_PROTO=
        - SASLAUTHD_LDAP_BIND_DN=cn=admin,dc=example,dc=com
        - SASLAUTHD_LDAP_PASSWORD=Passw0rd.
        - SASLAUTHD_LDAP_SEARCH_BASE=dc=example,dc=com
        - SASLAUTHD_LDAP_FILTER=(&(cn=%U)(objectClass=person))
        - SASLAUTHD_MECHANISMS=ldap
        links:
        - ldap
        depends_on:
        - ldap
```

And have this errors appearing:
```
ldap_1       | 59353a3e conn=1009 fd=18 ACCEPT from IP=172.19.0.6:49489 (IP=0.0.0.0:389)
ldap_1       | 59353a3e conn=1009 op=0 BIND dn="cn=admin,dc=example,dc=com" method=128
ldap_1       | 59353a3e conn=1009 op=0 BIND dn="cn=admin,dc=example,dc=com" mech=SIMPLE ssf=0
ldap_1       | 59353a3e conn=1009 op=0 RESULT tag=97 err=0 text=
ldap_1       | 59353a3e conn=1009 op=1 SRCH base="dc=example,dc=com" scope=2 deref=0 filter="(&(?objectClass=PostfixBookMailAccount)(uniqueIdentifier=emieza))"
ldap_1       | 59353a3e conn=1009 op=1 SRCH attr=uniqueIdentifier userPassword
ldap_1       | 59353a3e conn=1009 op=1 SEARCH RESULT tag=101 err=0 nentries=0 text=
mail         | Jun  5 11:02:22 mail dovecot: auth: ldap(emieza,172.19.0.4,<djf2bzRRSgCsEwAE>): unknown user (SHA1 of given password: d85c25)
mail         | Jun  5 11:02:24 mail dovecot: imap-login: Disconnected (auth failed, 1 attempts in 2 secs): user=<emieza>, method=PLAIN, rip=172.19.0.4, lip=172.19.0.6, TLS, session=<djf2bzRRSgCsEwAE>
ldap_1       | 59353a7c conn=1009 op=2 UNBIND
ldap_1       | 59353a7c conn=1009 fd=18 closed
```
So, my authentications can never find the user since I didnt't find the way to change the filter settings, and is always using PostfixBookMailAccound, which I prefer not to use. That can be seen in the line:

    ldap_1       | 59353a3e conn=1009 op=1 SRCH base="dc=example,dc=com" scope=2 deref=0 filter="(&(?objectClass=PostfixBookMailAccount)(uniqueIdentifier=emieza))"

It makes no difference if I comment out all SASLDAUTH params.

Any clues? I stand in contributing to wiki doc :)

**Comment by alinmear** [comment]
Hello @emieza. You have to specify the LDAP_QUERY_FILTER. Basically the logic is like this: 

`{PREFIX=LDAP}_ENV=VALUE` 

This means, that you can specify each env variable with it's corresponding value. The only thing you need to take care of is that the key value pair is actually available within the ldap files. Which means for your use-case, if there is a key called `"query_filter"` (in fact it is within the default files; if you provide specific ldap files on your own, take care that the key value pairs you wanna substitute are in place) you only need to specify the prefix for the LDAP section. 

All characters need to be uppercase --> Within the environment part: 

´"LDAP_QUERY_FILTER=(&(mail=%s)(mailEnabled=TRUE))"´.

Please use the latest version 2.3 just to be sure that all the logics and fixes are merged.

Hopefully this helps!

**Comment by emieza** [comment]
First of all, thanks a lot for the quick response.
OK, trying it, but still some issues.

1) When using v2.3 mailserver does not start with that message:
```
mail         | Starting Misc
mail         |   * Consolidating all state onto /var/mail-state
mail         |   *   Destination /var/mail-state/spool-postfix exists, linking /var/spool/postfix to it
mail         |   *   Destination /var/mail-state/lib-postfix exists, linking /var/lib/postfix to it
mail         |   *   Destination /var/mail-state/lib-amavis exists, linking /var/lib/amavis to it
mail         |   *   Destination /var/mail-state/lib-clamav exists, linking /var/lib/clamav to it
mail         |   *   Destination /var/mail-state/lib-spamassasin exists, linking /var/lib/spamassasin to it
mail         |   *   Destination /var/mail-state/lib-fail2ban exists, linking /var/lib/fail2ban to it
mail         |   *   Destination /var/mail-state/lib-postgrey exists, linking /var/lib/postgrey to it
mail         |   * Fixing /var/mail-state/* permissions
mail         | Starting mail server
mail         |   Starting cron  [ OK ]
mail         |   Starting rsyslog  [ OK ]
mail         |   Starting dovecot services  [ OK ]
mail         |   Starting opendkimfalse
mail         |   *  [ FAILED ]
mail         | Error: Please fix your configuration. Exiting...
mail exited with code 1
```
So, still using mailserver v2.2. Deleting volumes does not help. Am I missing some additional configuration from 2.2 to 2.3?

2) LDAP_QUERY_FILTER doesn't work, neither does LDAP_FILTER. I don't get the logic behind it. You said "the corresponding value for ldap config files", which files should I look at?

3) Do you mean all SASLAUTHD parameters are currently useless?

4) Our whole [config project file is that one](https://github.com/AWS2/Alumn-ID/blob/master/docker/docker-compose.yml), we are working in a docker environment for moodle + ldap + mailserver + roundcube and still other things, to manage a complete academic administration site with some extra scripts to add students and courses automatically.

**Comment by tomav** [comment]
Hi @emieza, could you check that you have the latest `2.3` image? It has been rebuilt few days ago.

```$ docker images | grep tvial/docker-mailserver | grep 2.3
tvial/docker-mailserver           2.3                 842262f7ba29        7 days ago          569MB
```

If yes, there's probably something buggy to fix in the image.
If no, please `docker rmi tvial/docker-mailserver:2.3 && docker pull tvial/docker-mailserver:2.3` and try again.

Thanks.

**Comment by emieza** [comment]
OK, seems that v2.3 doesn't let you start unless you have created DKIM keys. I don't know if that would be a "bug" or a mandatory configuration, although I think it should be optional to have them.

Another thing is: it always takes a lot of time to re-create /var/lib/amavis/db/ , (particularly when testing) I was going to make it persistent but I see that always does "Deleting db files in /var/lib/amavis/db". So, I guess that no shortcut to make quick testing...

For the issue about LDAP, still got the same:
```
ldap_1       | 59357853 conn=1000 op=1 SRCH base="dc=example,dc=com" scope=2 deref=0 filter="(&(?objectClass=PostfixBookMailAccount)(uniqueIdentifier=emieza))"
ldap_1       | 59357853 conn=1000 op=1 SRCH attr=uniqueIdentifier userPassword
ldap_1       | 59357853 conn=1000 op=1 SEARCH RESULT tag=101 err=0 nentries=0 text=
mail         | Jun  5 15:27:15 mail dovecot: auth: ldap(emieza,172.19.0.4,<aWJCIzhRm7CsEwAE>): unknown user (SHA1 of given password: d85c25)
```
So, LDAP_QUERY_FILTER still not working for me. I remember [my docker-compose.yml](https://github.com/AWS2/Alumn-ID/blob/master/docker/docker-compose.yml) (still not update to v2.3, but just in case it helps to understand)

**Comment by alinmear** [comment]
Trying to structure the problem here:

a.) Container is not starting up with v.2.3 without dkim keys. As @tomav mentioned above, opendkim fails if the file `/etc/opendkim/KeyTable` is missing --> quick solution (i will make a pr to fix this): create the folder and file by your self within the config folder `- "./config/:/tmp/docker-mailserver/"` --> `mkdir ./config/opendkim && touch ./config/opendkim/KeyTable`. After this the container will copy the required KeyTable file to /etc/opendkim.

b.) The env variables of SASLAUTHD are working as described in the README and they have no dependencies to ENABLE_LDAP and LDAP_SOME_VALUE. 

c.) For the the 3 files of postfix ldap integration (ldap-users.cf, ldap-groups.cf and ldap-aliases.cf) there is a special logic for maximal flexibility implemented by me: for instance you could provide the ldap files at container startup at /tmp/docker-mailserver. 


e.g. ldap-users.cf
```
bind             = yes
bind_dn = cn=admin,dc=mydomain,dc=loc
bind_pw = mypass
query_filter = (&(objectClass=inetOrgPerson)(mail=%s))
result_attribute = mail
search_base = dc=mydomain,dc=loc
server_host = ldap-host
version          = 3
myfunvar = working
```

So i do not have to write a sed block for each of the variables. Instead of this i wrote a logic which parses the env variables with the specific LDAP_ prefix. You could access the key myfunvar with the env variable `LDAP_MYFUNVAR=workinggreat`. That's what i am trying to say in my last post.

---

**But now to your actual Problem**: your problem is not related to postfix itself. This project is not implementing the docker best practice, 1 Container, 1 Process. Which means we have several processes running within this container. For your needs you have focus on the smtp server/service part, provided by postfix and the imap server/service part provided by dovecot. In your case not postfix is complaining about the `unknown user` but dovecot does. 

What your are trying to accomplish is dovecot talking to ldap. I just looked at this in start-mailserver.sh (line 579-585) and the crucial part for the search filter is missing here. To fix this, we need to add the search_filter substitution right there. The default value within `/etc/dovecot/dovecot-ldap.conf.ext` is `user_filter         = (&(objectClass=PostfixBookMailAccount)(uniqueIdentifier=%n))`. That's where your log value comes from.

As a quick workaround issue the following command after container startup, to substitute the value manually:


`docker exec -it <your-container-name> /bin/bash -c "sed -i -e 's|^user_filter[[:space:]]\+.*|user_filter = (\&\(cn=%U\)\(objectClass=person\)\)|g' /etc/dovecot/dovecot-ldap.conf.ext"`

After this please check `/etc/dovecot/dovecot-ldap.conf.ext` whether the variables are set as supposed by the above command.

Do not forget to restart the container to get the dovecot ps restarted as well.

Hopefully this helps. I will try to make a pr on this as soon as i can.

Best regards

**Comment by emieza** [comment]
Wonderful, that really helps. I finally decided to add PostfixBookMailAccount schema to my ldap, but that also adds extra work on the ldap container side. I see that in your tests appear the postifx-book.schema to do that patch.

Once I have all tested and working, I will be pleased to add that doc to the LDAP wiki here :)

Talk to you soon

**Comment by emieza** [comment]
Well, returning to the LDAP, I have tried the configuration in your ```test/docker-openldap``` folder, which is osixia's one that I was using too. But it does no start properly, it stops when trying to add the ldif files:

```
Add bootstrap ldif...
Processing file /container/service/slapd/assets/config/bootstrap/ldif/01-config-password.ldif
593844b0 conn=1019 fd=16 ACCEPT from PATH=/var/run/slapd/ldapi (PATH=/var/run/slapd/ldapi)
593844b0 conn=1019 op=0 BIND dn="" method=163
593844b0 conn=1019 op=0 BIND authcid="gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth" authzid="gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth"
593844b0 conn=1019 op=0 BIND dn="gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth" mech=EXTERNAL sasl_ssf=0 ssf=71
593844b0 conn=1019 op=0 RESULT tag=97 err=0 text=
593844b0 conn=1019 op=1 MOD dn="cn=config"
593844b0 conn=1019 op=1 RESULT tag=103 err=0 text=
593844b0 conn=1019 op=2 MOD dn="olcDatabase={0}config,cn=config"
593844b0 conn=1019 op=2 MOD attr=olcRootPW
593844b0 conn=1019 op=2 RESULT tag=103 err=0 text=
593844b0 conn=1019 op=3 UNBIND
593844b0 conn=1019 fd=16 closed
modifying entry "cn=config"
Processing file /container/service/slapd/assets/config/bootstrap/ldif/01_mail-tree.ldif
593844b0 conn=1020 fd=16 ACCEPT from PATH=/var/run/slapd/ldapi (PATH=/var/run/slapd/ldapi)
593844b0 conn=1020 op=0 BIND dn="" method=163
593844b0 conn=1020 op=0 BIND authcid="gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth" authzid="gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth"
593844b0 conn=1020 op=0 BIND dn="gidNumber=0+uidNumber=0,cn=peercred,cn=external,cn=auth" mech=EXTERNAL sasl_ssf=0 ssf=71
593844b0 conn=1020 op=0 RESULT tag=97 err=0 text=
593844b0 conn=1020 op=1 ADD dn="ou=people,dc=localhost,dc=localdomain"
593844b0 conn=1020 op=1 RESULT tag=105 err=53 text=no global superior knowledge
593844b0 conn=1020 op=2 UNBIND
593844b0 conn=1020 fd=16 closed
ldap_add: Server is unwilling to perform (53)
593844b0 conn=1021 fd=16 ACCEPT from IP=127.0.0.1:46559 (IP=127.0.0.1:389)
593844b0 conn=1021 op=0 BIND dn="cn=admin,dc=example,dc=org" method=128
593844b0 conn=1021 op=0 BIND dn="cn=admin,dc=example,dc=org" mech=SIMPLE ssf=0
593844b0 conn=1021 op=0 RESULT tag=97 err=0 text=
593844b0 conn=1021 op=1 ADD dn="ou=people,dc=localhost,dc=localdomain"
593844b0 conn=1021 op=1 RESULT tag=105 err=53 text=no global superior knowledge
ldap_add: Server is unwilling to perform (53)
593844b0 conn=1021 op=2 UNBIND
593844b0 conn=1021 fd=16 closed
*** /container/run/startup/slapd failed with status 53

*** Run commands before finish...
*** Killing all processes...
593844b0 daemon: shutdown requested and initiated.
593844b0 slapd shutdown: waiting for 0 operations/tasks to finish
593844b0 slapd stopped.
```

Any idea what is happening?

**Comment by emieza** [comment]
OK, solved, it was just the line in 02_user_email.ldif that had to be corrected with the proper domain:
```
# Some User
dn: uniqueIdentifier=some.user,ou=people,dc=example,dc=com
```

**Comment by johansmitsnl** [comment]
I'm struggling for 2 days making it work with the ldap setup. Found this issue but reading it does not make it 100% clear for me. This is mostly due to my ldap skils.
I use in a addition the osixia/phpldapadmin for managing the ldap. When building the ldap server with PostfixBookMailAccount how are the entries added to the ldap? I can see that the scheme is loaded but I cannot select it from the phpldapadmin when adding a new user.

* https://imagebin.ca/v/3QiPXMYjHeAM
* https://imagebin.ca/v/3QiPhfMDG6BO

This might not be related to this project itself but the ldap tutorial makes it very difficult to understand the setup.
When done I will make a nice wiki for this so that the ldap documentation is complete and working.

**Comment by emieza** [comment]
Simply create a "default" object, and then add the PostfixBookMailAccount to the objectClass. Then, you will be able to add the required fields for the mail account. You will need most of them, just take care to see docker-mailserver log output (better in debug mode) and it will tell you what is missing in your object.

**Comment by johansmitsnl** [comment]
@emieza thnx that worked. I can login to the imap and see my folders.

Now I have the issue delivering email:

The docker-compose is:
```yaml
services:
  mail:
    restart: always
    image: tvial/docker-mailserver:latest
    hostname: mail
    domainname: xxx.net
    container_name: mail
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
      - "4190:4190"
    volumes:
      - ./mail/data/mail:/var/mail
      - ./mail/data/mail-state:/var/mail-state
      - ./mail/config/:/tmp/docker-mailserver/
      - ./mail/config/letsencrypt:/etc/letsencrypt
    environment:
      - ENABLE_SPAMASSASSIN=1
      - ENABLE_CLAMAV=1
      #- ENABLE_FAIL2BAN=1
      - ENABLE_FAIL2BAN=0
      - ENABLE_POSTGREY=1
      - ONE_DIR=1
      - DMS_DEBUG=1
      - ENABLE_MANAGESIEVE=1
      - SSL_TYPE=letsencrypt
      - SASLAUTHD_PASSWD=
      # >>> SASL Authentication
      - ENABLE_SASLAUTHD=1
      - SASLAUTHD_LDAP_SERVER=ldap
      - SASLAUTHD_LDAP_PROTO=
      - SASLAUTHD_LDAP_BIND_DN=cn=admin,dc=xxx,dc=net
      - SASLAUTHD_LDAP_PASSWORD=xxx
      - SASLAUTHD_LDAP_SEARCH_BASE=ou=people,dc=xxx,dc=net
      - SASLAUTHD_LDAP_FILTER=(&(uniqueIdentifier=%U)(objectClass=PostfixBookMailAccount))
      - SASLAUTHD_MECHANISMS=ldap
      # <<< SASL Authentication
      # >>> Postfix Ldap Integration
      - ENABLE_LDAP=1
      - LDAP_SERVER_HOST=ldap
      - LDAP_SEARCH_BASE=ou=people,dc=xxx,dc=net
      - LDAP_BIND_DN=cn=admin,dc=xxx,dc=net
      - LDAP_BIND_PW=xxx
      # <<< Postfix Ldap Integration
      - PERMIT_DOCKER=host
```

The log of sending email from myself to myself:
```log
Jun 21 20:51:59 mail postfix/submission/smtpd[1710]: connect from unknown[x.x.x.x]
Jun 21 20:52:00 mail postfix/submission/smtpd[1710]: 042A5182685: client=unknown[x.x.x.x], sasl_method=PLAIN, sasl_username=johan.smits@mail.smitsmail.net
Jun 21 20:52:00 mail postfix/cleanup[1712]: 042A5182685: message-id=<dd209c76-3d49-deb5-9591-a0a0d921b268@smitsmail.net>
Jun 21 20:52:00 mail opendkim[380]: 042A5182685: DKIM-Signature field added (s=mail, d=smitsmail.net)
Jun 21 20:52:00 mail opendmarc[390]: implicit authentication service: mail.smitsmail.net
Jun 21 20:52:00 mail opendmarc[390]: 042A5182685: smitsmail.net fail
Jun 21 20:52:00 mail postfix/qmgr[1232]: 042A5182685: from=<johan@smitsmail.net>, size=713, nrcpt=1 (queue active)
Jun 21 20:52:00 mail postfix/submission/smtpd[1710]: disconnect from unknown[x.x.x.x] ehlo=2 starttls=1 auth=1 mail=1 rcpt=1 data=1 quit=1 commands=8
Jun 21 20:52:00 mail dovecot: imap(johan.smits): Connection closed (IDLE running for 0.001 + waiting input for 156.682 secs, 2 B in + 10+10 B out, state=wait-input) in=809 out=1879
Jun 21 20:52:00 mail dovecot: imap-login: Login: user=<johan.smits>, method=PLAIN, rip=x.x.x.x, lip=172.16.38.2, mpid=1719, TLS, session=<PuAiin5S7cpYnye1>
Jun 21 20:52:00 mail postfix/smtpd[1721]: connect from localhost[127.0.0.1]
Jun 21 20:52:00 mail postfix/smtpd[1721]: 96B1B18268C: client=localhost[127.0.0.1]
Jun 21 20:52:00 mail postfix/cleanup[1712]: 96B1B18268C: message-id=<dd209c76-3d49-deb5-9591-a0a0d921b268@xxx.net>
Jun 21 20:52:00 mail postfix/qmgr[1232]: 96B1B18268C: from=<johan@xxx.net>, size=1658, nrcpt=1 (queue active)
Jun 21 20:52:00 mail postfix/smtpd[1721]: disconnect from localhost[127.0.0.1] ehlo=1 mail=1 rcpt=1 data=1 quit=1 commands=5
Jun 21 20:52:00 mail amavis[1638]: (01638-03) Passed CLEAN {RelayedInbound}, [x.x.x.x]:51948 [x.x.x.x] <johan@xxx.net> -> <johan@xxx.net>, Queue-ID: 042A5182685, Message-ID: <dd209c76-3d49-deb5-9591-a0a0d921b268@xxx.net>, mail_id: Ghhe5tkF5oK6, Hits: -0.89, size: 1108, queued_as: 96B1B18268C, 475 ms
Jun 21 20:52:00 mail postfix/smtp[1713]: 042A5182685: to=<johan@xxx.net>, relay=127.0.0.1[127.0.0.1]:10024, delay=0.64, delays=0.16/0/0/0.48, dsn=2.0.0, status=sent (250 2.0.0 from MTA(smtp:[127.0.0.1]:10025): 250 2.0.0 Ok: queued as 96B1B18268C)
Jun 21 20:52:00 mail postfix/qmgr[1232]: 042A5182685: removed
Jun 21 20:52:00 mail dovecot: lmtp(1701): Connect from local
Jun 21 20:52:00 mail dovecot: auth: ldap(johan@xxx.net): unknown user
Jun 21 20:52:00 mail postfix/lmtp[1722]: 96B1B18268C: to=<johan@xxx.net>, relay=mail.xxx.net[/var/run/dovecot/lmtp], delay=0.03, delays=0.01/0.01/0/0.01, dsn=5.1.1, status=bounced (host mail.xxx.net[/var/run/dovecot/lmtp] said: 550 5.1.1 <johan@xxx.net> User doesn't exist: johan@xxx.net (in reply to RCPT TO command))
Jun 21 20:52:00 mail dovecot: lmtp(1701): Disconnect from local: Successful quit
Jun 21 20:52:00 mail postfix/cleanup[1712]: 9EA3118268D: message-id=<20170621205200.9EA3118268D@mail.xxx.net>
Jun 21 20:52:00 mail postfix/qmgr[1232]: 9EA3118268D: from=<>, size=3719, nrcpt=1 (queue active)
Jun 21 20:52:00 mail postfix/bounce[1723]: 96B1B18268C: sender non-delivery notification: 9EA3118268D
Jun 21 20:52:00 mail postfix/qmgr[1232]: 96B1B18268C: removed
Jun 21 20:52:00 mail dovecot: lmtp(1701): Connect from local
Jun 21 20:52:00 mail dovecot: auth: ldap(johan@xxx.net): unknown user
Jun 21 20:52:00 mail postfix/lmtp[1722]: 9EA3118268D: to=<johan@xxx.net>, relay=mail.xxx.net[/var/run/dovecot/lmtp], delay=0.02, delays=0.01/0/0/0, dsn=5.1.1, status=bounced (host mail.xxx.net[/var/run/dovecot/lmtp] said: 550 5.1.1 <johan@xxx.net> User doesn't exist: johan@xxx.net (in reply to RCPT TO command))
Jun 21 20:52:00 mail dovecot: lmtp(1701): Disconnect from local: Successful quit
```

Almost there but unclear why it is failing. It seems like a silly issue but i'm not able to place it.
