### ISSUE TITLE
Not working in AWS swarm with compose V3

### ISSUE THREAD

**Issue by adventuresoflucylu** [tomav/docker-mailserver#509]
Hi,

I am trying out the new Docker Swarm in AWS and when I try and convert the compose v2 to v3 and run it in my AWS swarm it fails to start. Any help would be appreciated.

**Comment by tomav** [comment]
HI @adventuresoflucylu, what do you mean by "fails to start"?
Could you provide more information as stated in https://github.com/tomav/docker-mailserver/blob/master/CONTRIBUTING.md ?

Thanks.

**Comment by Berndinox** [comment]
Running example:

export DOMAIN=mysite.com

```
version: '3'

services:
  mail:
    image: tvial/docker-mailserver:latest
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - maildata:/var/mail
      - mailstate:/var/mail-state
      - config:/tmp/docker-mailserver
    environment:
      - ENABLE_SPAMASSASSIN=1
      - ENABLE_CLAMAV=1
      - ONE_DIR=1
      - ENABLE_FETCHMAIL=1
      - OVERRIDE_HOSTNAME=mail.${DOMAIN}.at
      - POSTMASTER_ADDRESS=admin@${DOMAIN}.at
      - SSL_TYPE=letsencrypt
    deploy:
      replicas: 1

networks:
  default:
    driver: overlay

volumes:
  maildata:
    driver: local-persist
    driver_opts:
      mountpoint: /mnt/glusterfs/docker/mail/data/
  mailstate:
    driver: local-persist
    driver_opts:
      mountpoint: /mnt/glusterfs/docker/mail/state/
  config:
    driver: local-persist
    driver_opts:
      mountpoint: /mnt/glusterfs/docker/mail/config/
```
