### ISSUE TITLE
Question: plain text access to imap (no ssl)

### ISSUE THREAD

**Issue by edvorg** [tomav/docker-mailserver#519]
Hi. Is it possible to achieve such configuration in testing purposes? It's not clear from the documentation, but accessing using plain text imap doesn't work for me. This is my config:
```
version: '2'

services:
  raven-mail:
    networks:
      - raven
    image: tvial/docker-mailserver:2.1
    hostname: raven-mail
    domainname: domain.com
    container_name: raven-mail
    ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
    volumes:
    - maildata:/var/mail
    - mailstate:/var/mail-state
    - ./config/:/tmp/docker-mailserver/
    environment:
    - ENABLE_SPAMASSASSIN=0
    - ENABLE_CLAMAV=0
    - ENABLE_FAIL2BAN=0
    - ENABLE_POSTGREY=0
    - ONE_DIR=1
    - DMS_DEBUG=0
    cap_add:
    - NET_ADMIN

volumes:
  maildata:
    driver: local
  mailstate:
    driver: local

networks:
  raven:
    external: true

```
