### ISSUE TITLE
Fail2Ban bans docker gateway address

### ISSUE THREAD

**Issue by PAFsec** [tomav/docker-mailserver#523]
Hello,

Thank you so much for your work.

I have a problem.
When attempting several connections with a wrong password (and user!), fail2ban ban the remote IP at the source of those requests, which is a normal behavior.
Unfortunately, this remote IP is my Docker gateway (172.18.0.1), thus completely avoiding anything coming from that IP to reach dovecot, making my entire mailserver not working anymore.

It here seems that the only two solutions would be:
- disable fail2ban entirely (which is a shame ! :))
or
- whitelist the docker IP gateway (leading to no filtering anymore, as all requests goes through this IP to communicate to my docker-mailserver container)

What can be done here ?

Thank you in advance.

**Comment by flole** [comment]
Docker's userland proxy masquerades the source address of all incoming connections. You could use the `--net=host` option to share the network stack between the Docker host and your container. This would bypass the issue.

More here:
https://github.com/docker/docker/issues/15086

**Comment by tomav** [comment]
Perhaps there's something to do here: https://github.com/tomav/docker-mailserver/blob/master/target/start-mailserver.sh#L763-L791

**Comment by tomav** [comment]
@PAFsec let us know if you can contribute to this enhancement. Thanks.

**Comment by niko886** [comment]
>Docker's userland proxy masquerades the source address of all incoming connections. You could use the >--net=host option to share the network stack between the Docker host and your container. This would >bypass the issue.

how I can use `--net=host` with `docker-compose`?

**Comment by johansmitsnl** [comment]
Is this still an issue?
If not how did you solve it?

**Comment by niko886** [comment]
This is still issue

**Comment by johansmitsnl** [comment]
@niko886 when you tails the output do and you connect to smtp for example, do you see the docker gateway ip or the client ip?

My setup runs with a ipv6 nat and docker network bridge just fine.
See here a snippet of my log:
```log
mail                     | Sep  8 18:29:47 mail postfix/smtpd[1861]: connect from o10.sgmail.github.com[167.89.101.201]
```

```yaml
mail:
    restart: always
    image: tvial/docker-mailserver:latest
...
    networks:
      app_net:
        ipv4_address: 172.16.38.2

networks:
  app_net:
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: 172.16.38.0/24
        - subnet: fd00:aaaa:bbbb::/48
```

How is your configured?

**Comment by niko886** [comment]
@johansmitsnl The only way to me to solve this problem is using `--net=host`. 

>do you see the docker gateway ip or the client ip?

Without `--net=host` I see docker gateway ip, here is my config:


```
    networks:
      mail-net:
        ipv4_address: 172.16.0.10
...

networks:
  mail-net:
    driver: bridge
    ipam:
      driver: default
      config:
      -
        subnet: 172.16.0.0/24
```
