### ISSUE TITLE
HOW to ensuring Mailserver NOT lose mail?

### ISSUE THREAD

**Issue by voti** [tomav/docker-mailserver#525]
sometime I lost mail, 
so I build 2 mailserver with 2 host, Does it ensure that the mail is not lost？
```
                        mail to
                          |
                      example.com
mail1.example.com  10  /  MX  \  20 mail2.example.com
                      /        \                        
                host1          host2
              mailbox1          mailbox2
```
but the mailbox isn‘t synchronize，how to sync ? or other way ?

###relay
or build host1 mailserver and host2 postfix relay, Does it ensure that the mail is not lost？
```
                      mail to
                          |
                      example.com
mail1.example.com  10  /  MX  \  20 mail2.example.com
                      /        \                        
                host1          host2
            mailbox1 <------- Postfix relay
```
if host1 down, mail send to host2,
 host2 send to host1 when it work,and keep sending if not work,
is it possible? and how to modify docker-compose?

help me~thanks a lot.

**Comment by voti** [comment]
###relay
host2 docker-compose
```
version: '2'

services:
  mail:
    image: tvial/docker-mailserver:latest
    # build: .
    hostname: mail2
    domainname: domain.com
    container_name: mail
    environment:
      - SSL_TYPE=letsencrypt
      - SMTP_ONLY=1
      - POSTMASTER_ADDRESS=postmaster@domain.com
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - maildata:/var/mail
      - ./config/:/tmp/docker-mailserver/
      - /etc/letsencrypt:/etc/letsencrypt
volumes:
  maildata:
    driver: local
```
config/postfix-main.cf/
```
relay_domains = mail1.domain.com
```
