### ISSUE TITLE
config/docker-mailserver/postfix-accounts.cf not provided yet there in config folder

### ISSUE THREAD

**Issue by Mathieu-R** [tomav/docker-mailserver#577]
I have put my config files _(postfix-accounts.cf, opendkim folder,...)_ in a config folder but now I have another problem.
_(I created an issue before that for another problem : https://github.com/tomav/docker-mailserver/issues/576)_

![image](https://cloud.githubusercontent.com/assets/16360664/25091318/c97423aa-2388-11e7-9db3-b98bd00d712f.png)

But I have this in my `docker-compose.yml` 
```yml
mail:
...
  volumes:
        - ./mail/ingoing:/var/mail
        - ./mail/state:/var/mail-state
        - ./config/:/tmp/docker-mailserver/
        - /etc/letsencrypt:/etc/letsencrypt/
```

And here's my `config directory` : 
```
config
├── dovecot.conf
├── fail2ban-jail.conf
├── fetchmail.cf
├── opendkim
│   ├── keys
│   │   └── wt4.ephec-ti.be
│   │       ├── mail.private
│   │       └── mail.txt
│   ├── KeyTable
│   ├── SigningTable
│   └── TrustedHosts
└── postfix-accounts.cf
```
