### ISSUE TITLE
Unable to connect email client

### ISSUE THREAD

**Issue by JC1738** [tomav/docker-mailserver#582]
Thank you for the Docker Image, I think I am close, but can't seem to set my mail client to connect.  I have pasted in the docker-compose.yml as well as my output from docker logs mail.

Thank you,
Jim

```
version: '2'

services:
  mail:
    image: tvial/docker-mailserver:2.1
    hostname: mail
    domainname: jcastillo.us
    container_name: mail
    ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
    volumes:
    - /mnt/owncloud/maildata:/var/mail
    - /mnt/owncloud/mailstate:/var/mail-state
    - /mnt/owncloud/mail/config/:/tmp/docker-mailserver/
    - /mnt/owncloud/ssl:/tmp/ssl:ro
    environment:
    - ENABLE_SPAMASSASSIN=1
    - ENABLE_CLAMAV=1
    - ENABLE_FAIL2BAN=1
    - ENABLE_POSTGREY=1
    - ONE_DIR=1
    - DMS_DEBUG=1
    - SSL_TYPE=manual
    - SSL_CERT_PATH=/tmp/ssl/jcastillo.us.pem
    - SSL_KEY_PATH=/tmp/ssl/privkey.pem
    cap_add:
    - NET_ADMIN

volumes:
  maildata:
    driver: local
  mailstate:
    driver: local
```

```
#
#
# ENV
#
#

SSL_CERT_PATH=/tmp/ssl/jcastillo.us.pem
HOSTNAME=mail.jcastillo.us
SSL_KEY_PATH=/tmp/ssl/privkey.pem
DMS_DEBUG=1
ENABLE_CLAMAV=1
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ENABLE_FAIL2BAN=1
ENABLE_SPAMASSASSIN=1
PWD=/
SHLVL=1
HOME=/root
ONE_DIR=1
SSL_TYPE=manual
ENABLE_POSTGREY=1
_=/usr/bin/printenv

#
#
# docker-mailserver
#
#

Initializing setup
  Registering check,setup,fix,misc and start-daemons functions
  * _check_environment_variables() registered
  * _check_hostname() registered
  * _setup_default_vars() registered
  * _setup_dovecot() registered
  * _setup_dovecot_local_user() registered
  * _setup_dkim() registered
  * _setup_ssl() registered
  * _setup_docker_permit() registered
  * _setup_mailname() registered
  * _setup_amavis() registered
  * _setup_postfix_override_configuration() registered
  * _setup_postfix_sasl_password() registered
  * _setup_security_stack() registered
  * _setup_postfix_aliases() registered
  * _setup_postfix_vhost() registered
  * _fix_var_mail_permissions() registered
  * _misc_save_states() registered
  * _start_daemons_cron() registered
  * _start_daemons_rsyslog() registered
  * _start_daemons_dovecot() registered
  * _start_daemons_opendkim() registered
  * _start_daemons_opendmarc() registered
  * _start_daemons_postfix() registered
  * _start_daemons_fail2ban() registered
  * _start_daemons_clamav() registered
  * _start_daemons_amavis() registered
Checking configuration
  Check that there are no conflicts with env variables [_check_environment_variables]
  Check that hostname/domainname is provided or overidden (no default docker hostname/kubernetes) [_check_hostname]
  * Domain has been set to jcastillo.us
  * Hostname has been set to mail.jcastillo.us
Configuring mail server
  Setting up default variables [_setup_default_vars]
  * Set ENABLE_LDAP=0
  * Set ENABLE_FETCHMAIL=0
  * Set OVERRIDE_HOSTNAME=
  * Set ENABLE_MANAGESIEVE=0
  * Set DMS_DEBUG=1
  * Set VIRUSMAILS_DELETE_DELAY=7
  * Set ENABLE_POP3=0
  * Set ENABLE_SASLAUTHD=0
  * Set ENABLE_CLAMAV=1
  * Set SMTP_ONLY=0
  * Set ENABLE_FAIL2BAN=1
  * Set ENABLE_SPAMASSASSIN=1
  Setting up Dovecot
  Setting up Dovecot Local User
  * Checking file line endings
  * Regenerating postfix user list
  * user 'jc' for domain 'jcastillo.us' with password '********'
  * user 'jim' for domain 'jcastillo.us' with password '********'
  Setting up DKIM
  * DKIM keys added for: jcastillo.us
  * Changing permissions on /etc/opendkim
  Setting up SSL
  * Configuring certificates using cert /tmp/ssl/jcastillo.us.pem and key /tmp/ssl/privkey.pem
  * SSL configured with 'Manual' certificates
  Setting up PERMIT_DOCKER Option
  * Adding container ip in my networks
  Setting up Mailname
  * Creating /etc/mailname
  Setting up Amavis
  * Applying hostname to /etc/amavis/conf.d/05-node_id
  Setting up Postfix Override configuration
  * Loaded 'config/postfix-main.cf'
  Setting up Postfix SASL Password
  * Warning: 'SASL_PASSWD' is not provided. /etc/postfix/sasl_passwd not created.
  Setting up Security Stack
  * Enabling and configuring spamassassin
  * Enabling clamav
  * Fail2ban enabled
  Setting up Postfix Aliases
  * Warning 'config/postfix-virtual.cf' is not provided. No mail alias/forward created.
  Setting up Postfix vhost
  Fixing /var/mail permissions
  * Permissions in /var/mail look OK
Starting Misc
  * Consolidating all state onto /var/mail-state
  *   Destination /var/mail-state/spool-postfix exists, linking /var/spool/postfix to it
  *   Destination /var/mail-state/lib-postfix exists, linking /var/lib/postfix to it
  *   Destination /var/mail-state/lib-amavis exists, linking /var/lib/amavis to it
  *   Destination /var/mail-state/lib-clamav exists, linking /var/lib/clamav to it
  *   Destination /var/mail-state/lib-spamassasin exists, linking /var/lib/spamassasin to it
  *   Destination /var/mail-state/lib-fail2ban exists, linking /var/lib/fail2ban to it
Starting mail server
  Starting cron  [ OK ]
  Starting rsyslog  [ OK ]
  Starting dovecot services  [ OK ]
  Starting opendkim  [ OK ]
  Starting opendmarc  [ OK ]
  Starting postfix  [ OK ]
  Starting fail2ban  [ OK ]
```
