### ISSUE TITLE
Connection timed out when sending mails

### ISSUE THREAD

**Issue by abbert** [tomav/docker-mailserver#598]
Don't know what I'm doing wrong. The logs say connect to ........ connection timed out. This also occurs when sending to eg. a gmail account.

This is my docker-compose.yml:

```yaml
version: '2'
services:
  mail:
    image: tvial/docker-mailserver:latest
    hostname: mail
    domainname: adsf.tld
    container_name: mail
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    volumes:
      - maildata:/var/mail
      - mailstate:/var/mail-state
      - ./config/:/tmp/docker-mailserver/
      - ./letsencrypt/etc/:/etc/letsencrypt/
    environment:
      - ENABLE_SPAMASSASSIN=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=0
      - ONE_DIR=1
      - DMS_DEBUG=0
      - SSL_TYPE=letsencrypt
      - PERMIT_DOCKER=network
    cap_add:
      - NET_ADMIN
  rainloop:
    image: hardware/rainloop
    container_name: rainloop
    volumes:
      - ./rainloop:/rainloop/data
    ports:
      - "8888:8888"
volumes:
  maildata:
    driver: local
  mailstate:
    driver: local
```
 Am I missing some kind of configuration?
