### ISSUE TITLE
Thunderbird Certificate Security Exception when sending via 587

### ISSUE THREAD

**Issue by fatalhalt** [tomav/docker-mailserver#605]
![thunderbird-cert-exception](https://cloud.githubusercontent.com/assets/3224548/26032030/74d376ea-384e-11e7-8b02-2de8328ad345.jpg)

Hello,

I'm attempting to learn and use this docker image. I have successfully setup the container and can send emails from email providers like gmail to my container, but I cannot compose e-mail within Thunderbird and make replies (or send new emails).

Is this normal? I have Thunderbird setup to use port 587 SMARTTLS to push emails to postfix as described in Wiki's FAQ. As soon as I reply to an email in Thunderbird it pops out a Cert Security Exception due to "Unknown Issuer" as if it didn't recognize letsencrypt's CA. Looking at the Issuer I see that it says "ce4e6f5a3526". Here is a relevant mail.log when popup happened:
May 14 06:44:56 myhost postfix/submission/smtpd[1054]: connect from unknown[205.197.242.141]
May 14 06:44:56 myhost postfix/submission/smtpd[1054]: **warning: TLS library problem: error:14094418:SSL routines:ssl3_read_bytes:tlsv1 alert unknown ca:s3_pkt.c:1487:SSL alert number 48:**
May 14 06:44:56 myhost postfix/submission/smtpd[1054]: lost connection after STARTTLS from unknown[205.197.242.141]
May 14 06:44:56 myhost postfix/submission/smtpd[1054]: disconnect from unknown[205.197.242.141] ehlo=1 starttls=1 commands=2

I have found the occurrence of 'ce4e6f5a3526' CN in a dump of postfix's certs speciffied in main.cf:
> smtpd_tls_cert_file=/etc/ssl/certs/ssl-cert-snakeoil.pem

> root@myhost:/etc/dovecot# openssl x509 -in /etc/ssl/certs/ssl-cert-snakeoil.pem -text
> Certificate:
>     Data:
>         Version: 3 (0x2)
>         Serial Number: 18041405933464011722 (0xfa5ff31be8bf43ca)
>     Signature Algorithm: sha256WithRSAEncryption
>         Issuer: **CN=ce4e6f5a3526**
>         Validity
>             Not Before: May 10 07:59:45 2017 GMT
>             Not After : May  8 07:59:45 2027 GMT
>         Subject: CN=ce4e6f5a3526
>         Subject Public Key Info:
>             Public Key Algorithm: rsaEncryption
>                 Public-Key: (2048 bit)
> ...

Is this normal? Any help would be greatly appreciated. I would like to roll on my own mailserver again.

docker-compose.yml 
```
version: '2'

services:
  mail:
    image: tvial/docker-mailserver:latest
    hostname: myhost
    domainname: foo.bar
    container_name: mail
    ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
    volumes:
    - maildata:/var/mail
    - mailstate:/var/mail-state
    - ./config/:/tmp/docker-mailserver/
    environment:
    - ENABLE_SPAMASSASSIN=1
    - ENABLE_CLAMAV=0
    - ENABLE_FAIL2BAN=0
    - ENABLE_POSTGREY=0
    - ONE_DIR=1
    - DMS_DEBUG=1
    - SSL_TYPE=letsencrypt
    cap_add:
    - NET_ADMIN

volumes:
  maildata:
    driver: local
  mailstate:
    driver: local
```
