### ISSUE TITLE
hostname/domainname is required during backup

### ISSUE THREAD

**Issue by camory** [tomav/docker-mailserver#625]
Hello

I am trying the mailserver by using the _docker-compose.yml_ example. All works great, I can send and receive email but I am getting an issue while trying to back up my mails. 

```
$ docker run --rm --volume mail_maildata:/var/mail -v "$(pwd)":/backups -ti tvial/docker-mailserver

#
#
# docker-mailserver
#
#

Initializing setup
Checking configuration
  * Setting hostname/domainname is required
Error: Please fix your configuration. Exiting...
```

And here is my _docker-compose.yml_ file:

```
version: '2'

services:
  mail:
    image: tvial/docker-mailserver:latest
    hostname: mail
    domainname: example.com
    container_name: mail

    ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
    volumes:
    - maildata:/var/mail
    - mailstate:/var/mail-state
    - ./config/:/tmp/docker-mailserver/
    environment:
    - ENABLE_SPAMASSASSIN=1
    - ENABLE_CLAMAV=1
    - ENABLE_FAIL2BAN=1
    - ENABLE_POSTGREY=1
    - ONE_DIR=1
    - DMS_DEBUG=0
    cap_add:
    - NET_ADMIN

volumes:
  maildata:
    driver: local
  mailstate:
    driver: local
```
