### ISSUE TITLE
LDAP accounts/domain/alias  fully functional

### ISSUE THREAD

**Issue by kopax** [tomav/docker-mailserver#641]
I have a old mail-server (v1) with my own ldap implementation.

I have tried to play with the v2 and the following `docker-compose.yml`

```yml
version: '2'

services:
  mail:
    image: tvial/docker-mailserver:2.1
    hostname: mail
    domainname: domain.com
    container_name: mail
    ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
    volumes:
    - maildata:/var/mail
    - mailstate:/var/mail-state
    - ./config/:/tmp/docker-mailserver/
    - /home/me/workspace/private/domain-keys/mail-server:/tmp/ssl:ro
    environment:
    - ENABLE_LDAP=1
    - LDAP_SERVER_HOST=ldap.domain.com
    - LDAP_SEARCH_BASE=dc=mail,dc=domain,dc=com
    - LDAP_BIND_DN=cn=readonly,dc=domain,dc=com
    - LDAP_QUERY_FILTER=(&(objectClass=CourierMailAccount)(mail=%s))
    - LDAP_BIND_PW=abc
    - ENABLE_SPAMASSASSIN=1
    - ENABLE_CLAMAV=1
    - ENABLE_FAIL2BAN=1
    - ENABLE_SASLAUTHD=1
    - SASLAUTHD_MECHANISMS=ldap
    - SASLAUTHD_LDAP_SERVER=ldap.domain.com
    - SASLAUTHD_LDAP_PROTO=ldap://
    - SASLAUTHD_LDAP_SSL=0
    - SASLAUTHD_LDAP_PASSWORD=domain
    - SASLAUTHD_LDAP_BIND_DN=cn=readonly,dc=domain,dc=com
    - SASLAUTHD_LDAP_PASSWORD=abc
    - SASLAUTHD_LDAP_SEARCH_BASE=dc=mail,dc=domain,dc=com
    - SASLAUTHD_LDAP_FILTER=(&(objectClass=CourierMailAccount)(mail=%s))
    - SSL_TYPE=manual
    - SSL_CERT_PATH=/tmp/ssl/mail.domain.com-full.pem
    - SSL_KEY_PATH=/tmp/ssl/mail.domain.com-key.pem
    - ONE_DIR=1
    - DMS_DEBUG=0
    cap_add:
    - NET_ADMIN
    restart: always

volumes:
  maildata:
    driver: local
  mailstate:
    driver: local
```

Two remarks : 

 - Generated LDAP configuration doesn't load all my values (filters)
-  I haven't found in the documentation how to also configure alias filter query and domain filter query.

Is the ldap feature fully functional ?
