### ISSUE TITLE
Auto Renew Letsencrypt Certificate?

### ISSUE THREAD

**Issue by FlorianWendelborn** [tomav/docker-mailserver#656]
Are there any plans to offer "hassle-free SSL", like [Caddy](https://caddyserver.com) does? I switched from `nginx` to `caddy` and now the only reason I keep letsencrypt/certbot installed is this repo.

That's the only remaining "hard thing to do". I'd appreciate it a lot if something like this got implemented or if someone told me how to implement this myself.

---

I ended up using this solution:

1. [Use `henridwyer/docker-letsencrypt-cron` for SSL](https://github.com/dodekeract/config/blob/2c092efa3b17cec1d9965949cbc2c2048db77edb/compose/ssl/docker-compose.yml)
2. [Tell Caddy (my HTTP server) to forward `mail.domain.tld` to `/docker/caddy/static/tld.domain.mail`](https://github.com/dodekeract/config/blob/b591ef2b68871802db71672a17bc493bbcb4f860/compose/caddy/Caddyfile#L1-L3)
3. [Tell docker-mailserver to use custom SSL](https://github.com/dodekeract/config/blob/b591ef2b68871802db71672a17bc493bbcb4f860/compose/mail/docker-compose.yml#L21-L23)

The only issue is that I actually had to open a shell in `docker-letsencrypt-cron` to run the script for the first time. `docker exec -it ssl /bin/sh` -> `/scripts/run_certbot.sh`

---

The issue isn't closed because I still think it would be great to offer hassle-free 100% automatic SSL in this repo.

**Comment by gegere** [comment]
There is a way to auto renew letsencrypt/certbot. Setup the following as a cron process. Continuing to help develop this docker container to support high-level functions.

This has been running well on test systems.

```
0 0 * 1 * certbot-auto renew --quiet --no-self-upgrade
```

**Comment by dodekeract** [comment]
@gegere The thing is that I'd like my server to *only* use docker containers for services and _ideally_ this means that `docker-mailserver` should get its own SSL certificate automatically.

**Comment by klud1** [comment]
I'm using a cron job with a docker image
`* * 15 * * docker run --rm -ti -v /path/to/letsencrypt/log:/var/log/letsencrypt -v /path/to/letsencrypt/certs:/etc/letsencrypt -p 443:443 deliverous/certbot renew`

**Comment by 1n5aN1aC** [comment]
None of these solutions seem to work for me, since port 443 is already bound by the nginx docker, as expected.
@klud1 are you also stopping said docker before the update, and starting it after?

I'm not aware of any solution other than stopping the nginx docker, updating cert, then re-starting the nginx docker.

**Comment by klud1** [comment]
@1n5aN1aC  are you running any other services in that node? i can't see any other reason to have nginx running than having other services along with docker-mailserver, if so check this [jrcs/letsencrypt-nginx-proxy-companion](https://hub.docker.com/r/jrcs/letsencrypt-nginx-proxy-companion/) or you can use [traefik](https://github.com/containous/traefik) :)

**Comment by gutmensch** [comment]
I also went with the le nginx proxy companion solution to automatize the cert handling for the mailserver container. I have a roundcube container running, which exports ENV vars for the le-n-p-c container, docker-gen container and nginx container itself (in this case a SAN certificate for imap.example.com, smtp.example.com and mail.example.com):
```
  roundcube:
    image: "{{ docker_registry }}/roundcube"
    hostname: roundcube
    container_name: roundcube
    networks: "{{ docker_default_networks }}"
    depends_on:
      - front
      - docker-gen
    volumes:
      - "roundcube-data:/var/www/db"
    environment:
      - "VIRTUAL_HOST=mail.example.com,smtp.example.com,imap.example.com"
      - "VIRTUAL_PORT=80"
      - "LETSENCRYPT_HOST=mail.example.com,smtp.example.com,imap.example.com"
      - "LETSENCRYPT_EMAIL=letsencrypt@example.com"
```
This SAN cert I then just use for the docker-mailserver container and the resp. mail ports (where I don't have to care about the certs anymore).
