### ISSUE TITLE
Getting ***Unchecked***, clamav enabled

### ISSUE THREAD

**Issue by klud1** [tomav/docker-mailserver#682]
I have the mail server running
But everytime I get a new mail it gets prefixed with `***UNCHECKED***`

`docker-compose.yml`:
```yml
version: '3'
services:
  mailer:
    image: tvial/docker-mailserver:latest
    hostname: mail
    domainname: domain.tld
    container_name: mailer
    volumes:
      ...
    ports:
      - "25:25"
      - "110:110"
      - "143:143"
      - "587:587"
      - "993:993"
      - "995:995"
    environment:
      - ENABLE_SPAMASSASSIN=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=1
      - ENABLE_POP3=1
      - ONE_DIR=1
      - DMS_DEBUG=1
      - SSL_TYPE=letsencrypt
    cap_add:
      - NET_ADMIN
    restart: always
```
