### ISSUE TITLE
Setting hostname/domainname is required

### ISSUE THREAD

**Issue by mrflowo** [tomav/docker-mailserver#689]
Hello,
I try now for a few hours to get a mail server to run.
The server is a Rancher OS v1.0.4 and the mail server is to run as system service.

The server always crashes with the error "Setting hostname/domainname is required"

My Config:

```yaml
mail:
    image: tvial/docker-mailserver:latest
    hostname: mail
    domainname: mydomain.de
    ports:
        - "25:25"
        - "143:143"
        - "587:587"
        - "993:993"
    volumes:
        - /mnt/mail:/var/mail
        - /mnt/mail-state:/var/mail-state
        - /mnt/mail-config/:/tmp/docker-mailserver/
    environment:
        - ENABLE_SPAMASSASSIN=1
        - ENABLE_CLAMAV=1
        - ENABLE_FAIL2BAN=1
        - ENABLE_POSTGREY=1
        - ONE_DIR=1
        - DMS_DEBUG=1
    cap_add:
        - NET_ADMIN
```

The Output:

```
2017-08-12 14:46:58,938 CRIT Supervisor running as root (no user in config file)
2017-08-12 14:46:58,939 WARN Included extra file "/etc/supervisor/conf.d/saslauth.conf" during parsing
2017-08-12 14:46:58,939 WARN Included extra file "/etc/supervisor/conf.d/supervisor-app.conf" during parsing
Unlinking stale socket /var/run/supervisor.sock
2017-08-12 14:46:59,255 INFO RPC interface 'supervisor' initialized
2017-08-12 14:46:59,256 CRIT Server 'unix_http_server' running without any HTTP authentication checking
2017-08-12 14:46:59,257 INFO supervisord started with pid 5
2017-08-12 14:47:00,260 INFO spawned: 'mailserver' with pid 8

2017-08-12 14:47:00,280 INFO success: mailserver entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
#
#
# ENV
#
#

HOSTNAME=mail
SASLAUTHD_MECHANISMS=pam
DMS_DEBUG=1
SASLAUTHD_MECH_OPTIONS=
VIRUSMAILS_DELETE_DELAY=7
ENABLE_CLAMAV=1
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
ENABLE_FAIL2BAN=1
ENABLE_SPAMASSASSIN=1
SUPERVISOR_GROUP_NAME=mailserver
PWD=/
POSTGREY_DELAY=300
SUPERVISOR_ENABLED=1
SHLVL=1
HOME=/root
POSTGREY_TEXT=Delayed by postgrey
ONE_DIR=1
SUPERVISOR_SERVER_URL=unix:///var/run/supervisor.sock
SUPERVISOR_PROCESS_NAME=mailserver
DEBIAN_FRONTEND=noninteractive
ENABLE_POSTGREY=1
POSTGREY_MAX_AGE=35
_=/usr/bin/printenv

#
#
# docker-mailserver
#
#

Initializing setup
  Registering check,setup,fix,misc and start-daemons functions
  * _check_environment_variables() registered
  * _check_hostname() registered
  * _setup_default_vars() registered
  * _setup_dovecot() registered
  * _setup_dovecot_local_user() registered
  * _setup_postgrey() registered
  * _setup_dkim() registered
  * _setup_ssl() registered
  * _setup_docker_permit() registered
  * _setup_mailname() registered
  * _setup_amavis() registered
  * _setup_dmarc_hostname() registered
  * _setup_postfix_hostname() registered
  * _setup_dovecot_hostname() registered
  * _setup_postfix_sasl() registered
  * _setup_postfix_override_configuration() registered
  * _setup_postfix_sasl_password() registered
  * _setup_security_stack() registered
  * _setup_postfix_aliases() registered
  * _setup_postfix_vhost() registered
  * _setup_environment() registered
  * _fix_var_mail_permissions() registered
  * _fix_var_amavis_permissions() registered
  * _misc_save_states() registered
  * _start_daemons_cron() registered
  * _start_daemons_rsyslog() registered
  * _start_daemons_dovecot() registered
  * _start_daemons_opendkim() registered
  * _start_daemons_opendmarc() registered
  * _start_daemons_postgrey() registered
  * _start_daemons_postfix() registered
  * _start_daemons_fail2ban() registered
  * _start_daemons_clamav() registered
  * _start_daemons_amavis() registered
Checking configuration
  Check that there are no conflicts with env variables [_check_environment_variables]
  Check that hostname/domainname is provided or overidden (no default docker hostname/kubernetes) [_check_hostname]
  * Setting hostname/domainname is required
Aborted
```
