### ISSUE TITLE
setup.sh: Own volume configuration

### ISSUE THREAD

**Issue by mrflowo** [tomav/docker-mailserver#698]
Hello,
I use with my own volume configuration. This is not compatible with setup.sh.

Could one extend the setup.sh please by the possibility that i can use other volume configurations?

```yaml
mail:
    image: tvial/docker-mailserver:latest
    hostname: mail
    domainname: example.net
    ports:
        - "25:25"
        - "143:143"
        - "587:587"
        - "993:993"
    volumes:
        - /mnt/mail:/var/mail
        - /mnt/mail-state:/var/mail-state
        - /mnt/mail-config:/tmp/docker-mailserver
    environment:
        - ENABLE_SPAMASSASSIN=1
        - ENABLE_CLAMAV=1
        - ENABLE_FAIL2BAN=1
        - ENABLE_POSTGREY=1
        - ONE_DIR=1
        - DMS_DEBUG=1
        - OVERRIDE_HOSTNAME=example.net
    cap_add:
        - NET_ADMIN
```
