### ISSUE TITLE
Dovecot not fully running.

### ISSUE THREAD

**Issue by ChromoX** [tomav/docker-mailserver#701]
Output of supervisorctl status looks good. Dovecot in the running state without any restarts, but in the logs I see the following lines.
```
Aug 22 23:11:54 00d7ef713a86 dovecot: imap-login: Error: Timeout waiting for handshake from auth server. my pid=393, input bytes=0
Aug 22 23:11:54 00d7ef713a86 dovecot: imap-login: Error: Timeout waiting for handshake from auth server. my pid=391, input bytes=0
Aug 22 23:11:54 00d7ef713a86 dovecot: imap-login: Error: Timeout waiting for handshake from auth server. my pid=395, input bytes=0
Aug 22 23:11:54 00d7ef713a86 dovecot: imap-login: Disconnected: Auth process broken (disconnected before auth was ready, waited 144 secs): user=<>, rip=10.10.10.10, lip=10.42.68.75, TLS handshaking, session=<3fdfg34g3gde2>
```
It is not possible to login to any part of the server. Seems like the auth process is down?

**Comment by johansmitsnl** [comment]
With _docker ps_ you can see the ID of the container.
Then with _docker exec -ti ID_container bash_ you can enter the running container.

**Comment by ChromoX** [comment]
Yes I entered and looked around for a while to try and find out what was going on, but I couldn't find anything other than the above errors. I eventually restarted and finagled it to working, but it doesn't come up every time I restart.

**Comment by ChromoX** [comment]
It seems like the real problem is that postfix doesn't full come up. I can't find anything interesting in the logs though.

**Comment by johansmitsnl** [comment]
Do you restart of kill start?

**Comment by ChromoX** [comment]
I've tried both. I can also get everything working, but then if I try to send some mail everything dies again.

Using the latest tag pulled about 5 hours ago.

```
Aug 23 15:17:31 999dc03b149c postfix/smtpd[14203]: warning: unknown[<ip>]: SASL LOGIN authentication failed: UGFzc3dvcmQ6
```

I don't have SASL enabled. I'm simply using the passwd-file authentication. Do I need to enable SASL with a password file?

**Comment by johansmitsnl** [comment]
Can you post your compose settings?
If you run manually these command from the make file are used for testing the containers: https://github.com/tomav/docker-mailserver/blob/a2f65912121041cbccf18211ee9db79f696d942e/Makefile#L21-L36

**Comment by ChromoX** [comment]
Docker-Compose Settings:

```  
mail:
    cap_add:
    - NET_ADMIN
    image: tvial/docker-mailserver:latest
    environment:
      DMS_DEBUG: '1'
      ENABLE_CLAMAV: '1'
      ENABLE_FAIL2BAN: '1'
      ENABLE_POSTGREY: '1'
      ENABLE_SPAMASSASSIN: '1'
      ONE_DIR: '1'
      OVERRIDE_HOSTNAME: mail.domain.com
      PERMIT_DOCKER: network
      POSTMASTER_ADDRESS: postmaster@domain.com
      SSL_CERT_PATH: /tmp/ssl/mail.domain.com/fullchain.pem
      SSL_KEY_PATH: /tmp/ssl/mail.domain.com/privkey.pem
      SSL_TYPE: manual
    volumes:
    - mail-data:/var/mail
    - mail-state:/var/mail-state
    - mail-config:/tmp/docker-mailserver/
    - certs:/tmp/ssl:ro
```
