### ISSUE TITLE
How to keep log persistent ?

### ISSUE THREAD

**Issue by VincentGuyader** [tomav/docker-mailserver#712]
Hi, 

I would like to save all logs, so i add a volume like this `/home/stack/docker-mailserver/log:/var/log/`
But the log folder is empty. Do I miss something ? all other folders are OK...

this is my docker-compose.yml file : 
```

version: '2'

services:
  mail:
    restart: always
    image: tvial/docker-mailserver:latest
    hostname: mail
    domainname: mydomain.fr
    container_name: mail
    ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
    volumes:
    - /home/stack/docker-mailserver/cert/etc:/etc/letsencrypt
    - /home/stack/docker-mailserver/cert/etc:/etc/letsencrypt
    - /home/stack/docker-mailserver/maildata:/var/mail
    - /home/stack/docker-mailserver/mailstate:/var/mail-state
    - /home/stack/docker-mailserver/log:/var/log/
    - /home/stack/docker-mailserver/config/:/tmp/docker-mailserver/
    environment:
    - ENABLE_SPAMASSASSIN=1
    - SSL_TYPE=letsencrypt
    - ENABLE_CLAMAV=1
    - ENABLE_FAIL2BAN=1
    - ENABLE_POSTGREY=0
    - ENABLE_SASLAUTHD=0
    - ONE_DIR=1
    - DMS_DEBUG=0
    cap_add:
    - NET_ADMIN

volumes:
  maildata:
    driver: local
  mailstate:
    driver: local

```
