### ISSUE TITLE
No secure imap connection possible with letsencrypt certs

### ISSUE THREAD

**Issue by konstantinj** [tomav/docker-mailserver#72]
Hi,

still can't figure out why I can't get a secure imap connection. The combined.pem is there and has the privkey.pem and the cert.pem in it.

    > openssl s_client -connect mail.host.tld:143 -starttls imap -tlsextdebug
    > CONNECTED(00000003)
    > 140493167040416:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:s23_clnt.c:769:
    > ---
    > no peer certificate available
    > ---
    > No client certificate CA names sent

Do you know how to debug this more?

**Comment by Pixinn** [comment]
Hi !

Maybe it is because I mounted the _letsencrypt_ volume Read-Only, but I had to manually build my _combined.pem_ file using _cat_.
Here is the error I got before that : 

> Feb  7 23:39:20 mail imapd-ssl: couriertls: /etc/letsencrypt/live/mail.XXXX.tld/combined.pem: error:02001002:system library:fopen:No such file or directory

I did not recall reading a clear warning from your starting script about the missing file or the impossibility to build it. If I'm not mistaken, maybe you should add one.

**Comment by konstantinj** [comment]
Hi, as I said the combined.pem is in the correct place and I also created it myself to see if that helps. I wonder why s_client is complaining about ssl23 since both ssl protocols are disabled. But even if I tell it to only use tls it fails with the same error message. Still no clue how to debug courier to track this down.

**Comment by tomav** [comment]
Hi @konstantinj, could you give me your `docker-compose.yml` file and run `tree` command at your project root? Thank you.

**Comment by konstantinj** [comment]
Hi @tomav 

```
mail:
  hostname: mail.host
  restart: always
  image: tvial/docker-mailserver
  ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
  environment:
    - COLLECTD_DOCKER_APP=mail_mail
    - DMS_SSL=letsencrypt
  volumes:
    - /etc/localtime:/etc/localtime:ro
    - /usr/share/zoneinfo:/usr/share/zoneinfo:ro
    - ./spamassassin:/tmp/spamassassin
    - ./postfix:/tmp/postfix
    - ./opendkim/etc:/etc/opendkim
    - ./mail:/var/mail
    - ./../nginx-proxy/certs:/etc/letsencrypt/live
```

```
.
├── docker-compose.yml
├── mail
├── opendkim
│   └── etc
├── postfix
└── spamassassin
```
nginx-procy/certs is
```
├── mail.host
│   ├── account_key.json
│   ├── cert.pem
│   ├── chain.pem
│   ├── combined.pem
│   ├── fullchain.pem
│   ├── key.pem
│   └── privkey.pem
```
