### ISSUE TITLE
volumes

### ISSUE THREAD

**Issue by andrius** [tomav/docker-mailserver#73]
I have removed some pieces to external volumes, below you'll find my docker-compose.yml. However, I had some permission issues with opendkim. Could you update how to use external data volumes properly with docker-mailserver? (permissions, ownership, any  notes?)

```
mail:
  image: tvial/docker-mailserver
  restart: always
  hostname: mail
  domainname: XXXXXX
  ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
  volumes:
    - ./spamassassin:/tmp/spamassassin/
    - ./postfix:/tmp/postfix/
    - ./opendkim:/etc/opendkim/
    - ./letsencrypt:/etc/letsencrypt/
    - ./mail:/var/mail
  environment:
    - DMS_SSL=letsencrypt
```
