### ISSUE TITLE
ERROR: can't open lock file: /var/lib/postgrey/postgrey.lock

### ISSUE THREAD

**Issue by lonly197** [tomav/docker-mailserver#755]
## Docker:
```
Client:
 Version:      17.06.2-ce
 API version:  1.30
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 19:59:06 2017
 OS/Arch:      linux/amd64

Server:
 Version:      17.06.2-ce
 API version:  1.30 (minimum version 1.12)
 Go version:   go1.8.3
 Git commit:   cec0b72
 Built:        Tue Sep  5 20:00:25 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

### Image
```
tvial/docker-mailserver:latest
```

### docker-compose.yml
```
version: '2'

services:
  mail:
    image: tvial/docker-mailserver:latest
    hostname: dmp1
    domainname: dmp.airflow.com
    container_name: mail
    ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
    volumes:
    - /opt/mail:/var/mail
    - /opt/mail/mail-state:/var/mail-state
    - /opt/mail/config/:/tmp/docker-mailserver/
    environment:
    - ENABLE_SPAMASSASSIN=1
    - ENABLE_CLAMAV=1
    - ENABLE_FAIL2BAN=1
    - ENABLE_POSTGREY=1
    - ONE_DIR=1
    - DMS_DEBUG=0
    cap_add:
    - NET_ADMIN
    - SYS_PTRACE

volumes:
  maildata:
    driver: local
  mailstate:
    driver: local
```

## Error message
```
U2017-10-27T07:36:37.031586651Z Binding to TCP port 10023 on host 127.0.0.1 with IPv4
82017-10-27T07:36:37.031590410Z Setting gid to "115 115"
42017-10-27T07:36:37.031593533Z Setting uid to "111"
\2017-10-27T07:36:37.031596135Z ERROR: can't open lock file: /var/lib/postgrey/postgrey.lock
```
