### ISSUE TITLE
OVH configuration, help wanted

### ISSUE THREAD

**Issue by ticruz38** [tomav/docker-mailserver#759]
Hi,
I'm trying to setup a mail server for the first time. I do think everything is fine on my server side. However it seems that my ovh configuration is a bit more painful.
Her is my docker-compose.yaml
```
services:
  mail:
    image: tvial/docker-mailserver:latest
    hostname: mail
    domainname: bnbkeeper.thibautduchene.fr
    container_name: mail
    ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
    volumes:
    - maildata:/var/mail
    - mailstate:/var/mail-state
    - ./config/:/tmp/docker-mailserver/
    environment:
    - ENABLE_SPAMASSASSIN=1
    - ENABLE_CLAMAV=1
    - ENABLE_FAIL2BAN=1
    - ENABLE_POSTGREY=1
    - ONE_DIR=1
    - DMS_DEBUG=0
    cap_add:
    - NET_ADMIN
    - SYS_PTRACE

volumes:
  maildata:
    driver: local
  mailstate:
    driver: local
```

I do end up with this in my logs

`mail.bnbkeeper.thibautduchene.fr is up and running`

I also configured a user and dkim keys.

here is my config so far in ovh and I cant send emails.

<img width="779" alt="github issue" src="https://user-images.githubusercontent.com/5814378/32284870-474ae298-bf31-11e7-8583-de214281d73c.png">
