### ISSUE TITLE
cannot receive mails , but sending mails is okay

### ISSUE THREAD

**Issue by helmutundarnold** [tomav/docker-mailserver#781]
docker-mailserver cannot retrieve mails from outside.

I've installed this mailserver according to your description on a CentOs 7.3 box with docker-compose and sending mails is working properly. 

The problem is that I cannot receive mails from other mailservers. If I send a message from one mail-box to another internally its working.  If I send an email from a mailserver of another domain, I get the response  "`[x.x.x.x]:25: Connection refused`". 

I'm a bit confused because if I run on the dockerhost "`telnet mail.mydomain.com 25`",  I receive a "Connection refused", but if I jump into the container and run the same I get the mail-prompt.

Below my docker-compose.yml
```
Version: '2'

services:
  mail:
    image: tvial/docker-mailserver:latest
    hostname: mail
    domainname: mydomain.com
    container_name: mycontainername
    restart: unless-stopped
    
    ports:
    - 25:25
    - 110:110
    - 143:143
    - 587:587
    - 993:993
    
    volumes:
    - maildata:/var/mail
    - mailstate:/var/mail-state
    - <config-directory>:/tmp/docker-mailserver/
    - /etc/letsencrypt/:/etc/letsencrypt/
    
    environment:
    - POSTMASTER_ADDRESS=admin@mydomain.com
    - ENABLE_SPAMASSASSIN=1
    - ENABLE_CLAMAV=1
    - ENABLE_SASLAUTHD=0
    - ENABLE_FAIL2BAN=0
    - ENABLE_POSTGREY=1
    - ENABLE_POSTGREY_DELAY=300
    - ENABLE_POP3=1
    - ONE_DIR=1
    - DMS_DEBUG=1
    - SSL_TYPE=letsencrypt
    
    cap_add:
    - NET_ADMIN
    - SYS_PTRACE

volumes:
  maildata:
    driver: local
  mailstate:
    driver: local
```
