### ISSUE TITLE
Delay of up to 15 Minutes when receiving eMail

### ISSUE THREAD

**Issue by Gymnae** [tomav/docker-mailserver#803]
This container has been working like a charm since I set it up, but there's a long delay in receiving eMail.
It's the only MX assigned to the domain with priority 1 - so there should be no bouncing.

DNS settings:
```
MX <mydomain>.de	mail handled by imap.<mydomain> Automatic		
SPF <mydomain>.de	v=spf1 mx a -all	Automatic		
TXT <mydomain>.de	v=spf1 mx a -all	Automatic		
TXT  imap._domainkey	v=DKIM1; k=rsa; p=MIGfMA...<restofkey>	Automatic
```
docker compose:
```
version: '2'

services:
  mail:
    image: tvial/docker-mailserver:latest
    hostname: imap
    domainname: <mydomain>.de
    restart: always
    container_name: mail
    ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
    - "4190:4190"
    volumes:
    - grundstil_maildata:/var/mail
    - grundstil_mailstate:/var/mail-state
    - ./config/:/tmp/docker-mailserver/
    - ./letsencrypt/etc/letsencrypt/:/etc/letsencrypt/
    environment:
    - ENABLE_SPAMASSASSIN=1
    - ENABLE_CLAMAV=1
    - ENABLE_FAIL2BAN=1
    - ENABLE_POSTGREY=1
    - ENABLE_MANAGESIEVE=1
    - ONE_DIR=1
    - DMS_DEBUG=0
    - SSL_TYPE=letsencrypt
    cap_add:
    - NET_ADMIN

volumes:
  <mydomain>_maildata:
    driver: local
  <mydomain>_mailstate:
    driver: local
```
Could it be a server-side slowness? The machine is running other services, like web server, without a problem, the load is also not too high.
