### ISSUE TITLE
What is DOVECOT_PASS_FILTER and DOVECOT_USER_FILTER?

### ISSUE THREAD

**Issue by jeffwji** [tomav/docker-mailserver#805]
I have been very confused by this two variables:
``` 
     - DOVECOT_PASS_FILTER="(&(objectClass=PostfixBookMailAccount)(uniqueIdentifier=%n))"
     - DOVECOT_USER_FILTER="(&(objectClass=PostfixBookMailAccount)(uniqueIdentifier=%n))"
```

I'm trying to setup the mailbox against with AD, I think I should have something like
```
      - LDAP_QUERY_FILTER_USER="(&(objectCategory=Person)(sAMAccountName=%s)(memberOf=cn=emailusers,dc=company,dc=com))"
```

But what is DOVECOT_PASS_FILTER and DOVECOT_USER_FILTER? `start-mailserver.sh` has this contents from line 558:
```
	# Not sure whether this can be the same or not
	# _dovecot_ldap_mapping["DOVECOT_PASS_FILTER"]="${DOVECOT_PASS_FILTER:="${LDAP_QUERY_FILTER_USER}"}"
	# _dovecot_ldap_mapping["DOVECOT_USER_FILTER"]="${DOVECOT_USER_FILTER:="${LDAP_QUERY_FILTER_USER}"}
```

Which has been commented out, and even funny thing is looks like the script author himself is not sure how to use this two variables?

**Comment by dolanor** [comment]
Well, I've been fighting it also, and I'm taming the beast as we speak.
So, yes, that [comment](https://github.com/tomav/docker-mailserver/blob/master/target/start-mailserver.sh#L558) is valid, depending on the point of view.

Can DOVECOT_PASS_FILTER and DOVECOT_USER_FILTER be the same ? I'd say yes. This is what I do (with an OpenLDAP, but should be the same for AD)
Can DOVECOT_PASS_FILTER and DOVECOT_USER_FILTER use the same value as LDAP_QUERY_FILTER_USER ? Definitely NO.

LDAP_QUERY_FILTER_USER use %s as a value passed to it. %s is simply the user string passed to postfix (and handled via saslauthd). So it can be the username, or the user@domain.com email
DOVECOT_PASS_FILTER and DOVECOT_USER_FILTER can use [dovecot variables](https://wiki2.dovecot.org/Variables). So you can use %u, %d, %n if you want the username, the full email, or the domain.

**Comment by jeffwji** [comment]
Hi @dolanor , Thank you for answer, I also guess it should be able to be the same. So I put in:

    DOVECOT_PASS_FILTER: (&(userPrincipalName=%u)(objectClass=person)(memberOf=cn=emailusers,cn=Users,dc=example,dc=com))
    DOVECOT_USER_FILTER: (&(userPrincipalName=%u)(objectClass=person)(memberOf=cn=emailusers,cn=Users,dc=example,dc=com))

But it doesn't work and finally I figured out that the script `/etc/dovecot/dovecot-ldap.conf.ext` has been generated as:

    base = cn=Users,dc=example,dc=com
    default_pass_scheme = SSHA
    dn = cn=postmaster,cn=Users,dc=example,dc=com
    dnpass = password
    hosts = dc.example.com
    tls                 = no
    ldap_version        = 3
    pass_attrs          = uniqueIdentifier=user,userPassword=password
    pass_filter = (&(userPrincipalName=%u)(objectClass=person)(memberOf=cn=emailusers,cn=Users,dc=example,dc=com))
    user_attrs          = mailHomeDirectory=home,mailUidNumber=uid,mailGidNumber=gid,mailStorageDirectory=mail
    user_filter = (&(userPrincipalName=%u)(objectClass=person)(memberOf=cn=emailusers,cn=Users,dc=example,dc=com))

The problem is `pass_attrs` and `user_attrs` were fixed! and `mailUidNumber` and `mailGidNumber` were unrecognized by dovecot which must be `uid` and `gid`, both of the value must be `5000`.

And even worse is for AD authentication, Dovecot need setup `auth_bind = yes`, this argument is missing, which causes `userPassword=password` failed, because AD doesn't allow password to be retrieved. The same thing also happens to `/etc/postfix/ldap-aliases.cf`, `/etc/postfix/ldap-users.cf` and `/etc/postfix/ldap-groups.cf`. `result_attribute` is fixed to `mail`, which in AD should be `userPrincipalName`. 

So the configuration is totally not compatible with AD. 

Finally, I have to customized all the configuration files and mounted them to container, disabled environment variables to prevent the files to be overwritten. I thought it must works now, yes, I past the authentication, but now is hitting in another problem. When I tried to send an email to another account in the same domain, I got error:

    status=bounced (mail for kube02.stanford.lab loops back to myself)

When some said I should setup `mydestination=example.com` in the `main.cf`, so I changed `start-mailserver.sh` to add a line (looks like I changed most of your files). but I have been bounced again!!! The reason is:

    status=bounced (unknown user: "test.user")

Some said is because `mydestination` will considers the user as local user, but my user is managed by AD....I've spent 3 days already, exhausted...

**Comment by dolanor** [comment]
Here is a little trick I learned from reading the [start-mailserver.sh](https://github.com/tomav/docker-mailserver/blob/master/target/start-mailserver.sh#L566)
It uses configomat to create config out of env vars.
So, yes, user_attrs and pass_attrs seem to be fixed, but actually, the config file is modified by configomat. So by creating an env var `DOVECOT_USER_ATTRS="blablabla"`, it will fill the user_attrs the way you define it. I needed it because those default settings requires you have an LDAP configured with a postfix-book schema, which I didn't have, and I didn't want to. So the same applies to you, you don't have that schema. But instead of using LDAP keys as I did, you would define your AD keys.
(explained by the author in [this thread](https://github.com/tomav/docker-mailserver/issues/680#issuecomment-323031450) )

AD not making you retrieve password, is it just some authorization configuration missing from your `cn=postmaster,cn=Users,dc=example,dc=com`? For me, I had to autorize my `cn=mailacct,ou=users,dc=example,dc=com` to read userPassword.

Before you look to change the postfix base configuration, again, look in AD configuration, and mostly `/etc/postfix/ldap-domains.cf` to see if it is well configured so it can lookup local domain. If it is not well configured, it is maybe because of a bug that I need to report. Just make sure you configure a LDAP_QUERY_FILTER_DOMAIN env var for the time being.

Look also on the SASL configuration side.
I know it's a lot of systems, but I still think this project is the one that makes it easier to configure. The sheer complexity of the standard system is just too much to grasp.
I also spent nearly ~100s hours to configure this. But I'm happy, now I just need the image and the env var + a `config/dovecot.cf` containing 
```
mail_uid = 5000
mail_gid = 5000
```
My docker-compose part of mailserver:
```
version: '2.1'
services:
  mail:
    image: tvial/docker-mailserver:testing
    hostname: gate
    domainname: mydomain.com
    container_name: mail
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "465:465"
      - "993:993"
    volumes:
      - ./mail/data:/var/mail
      - ./mail/state:/var/mail-state
      - ./mail/config/:/tmp/docker-mailserver/
    environment:
      ENABLE_SPAMASSASSIN: 1
      ENABLE_CLAMAV: 1
      ENABLE_FAIL2BAN: 1
      ENABLE_POSTGREY: 1
      ENABLE_SASLAUTHD: 1
      ENABLE_LDAP: 1
      ONE_DIR: 1
      DMS_DEBUG: 1
      LDAP_SERVER_HOST: ldap
      LDAP_SEARCH_BASE: ou=people,dc=multiverse
      LDAP_BIND_DN: cn=mailacct,ou=apps,dc=mydomain,dc=com,dc=multiverse
      LDAP_BIND_PW: mypassword
      LDAP_QUERY_FILTER_USER: "(mail=%s)"
      LDAP_QUERY_FILTER_GROUP: "(mailGroupMember=%s)"
      LDAP_QUERY_FILTER_ALIAS: "(mailalias=%s)"
      LDAP_QUERY_FILTER_DOMAIN: "(|(mail=*@%s)(mailalias=*@%s))"
      DOVECOT_PASS_FILTER: "(&(objectClass=inetOrgPerson)(mail=%u))"
      DOVECOT_USER_FILTER: "(&(objectClass=inetOrgPerson)(mail=%u))"
      DOVECOT_USER_ATTRS: "homeDirectory=home"
      SASLAUTHD_MECHANISMS: ldap
      SASLAUTHD_LDAP_SERVER: ldap
      SASLAUTHD_LDAP_SEARCH_BASE: ou=people,dc=multiverse
      SASLAUTHD_LDAP_BIND_DN: cn=mailacct,ou=apps,dc=mydomain,dc=com,dc=multiverse
      SASLAUTHD_LDAP_PASSWORD: password
      SASLAUTHD_LDAP_FILTER: "(&(objectClass=inetOrgPerson)(mail=%u))"
      POSTMASTER_ADDRESS: postmaster@mydomain.com
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
```
