### ISSUE TITLE
SMTP: No AUTH option

### ISSUE THREAD

**Issue by scrwr** [tomav/docker-mailserver#838]
In latest version (286 MB, 5 days ago, 9ef4efc51cd7...) SMTP EHLO doesn't provide 
```
250-AUTH PLAIN LOGIN
250-AUTH=PLAIN LOGIN
```
anymore. Ergo login isn't possible anymore.
In tag 2.3 (320 MB, 17 days ago, 7aaf98379b39...) its still working fine.

I checked the usual suspects:
```
# doveconf 
auth_mechanisms = plain login

# postconf
smtpd_tls_auth_only = no
smtpd_sasl_type = dovecot
```

And I also tried via STARTTLS:
```
 > openssl s_client -starttls smtp -crlf -connect mail.example.com:25
...
250 SMTPUTF8
EHLO test
250-mail.example.com <- changed
250-SIZE 10240000
250-ETRN
250-ENHANCEDSTATUSCODES
250-8BITMIME
250-DSN
250 SMTPUTF8
```

My docker-compose:
```
  mx:
    image: tvial/docker-mailserver
    hostname: mail
    domainname: example.com
    cap_add:
     - NET_ADMIN
    ports:
     - "25:25"
     - "143:143"
     - "587:587"
     - "993:993"
    volumes:
     - /opt/mx/config/:/tmp/docker-mailserver/
     - /opt/mx/maildir:/var/mail
     - /opt/mx/mail-state:/var/mail-state
     - /opt/mx/certs/mail.example.com:/etc/letsencrypt/live/mail.example.com
    environment:
      SSL_TYPE: letsencrypt
      ENABLE_SPAMASSASSIN: 1
      ENABLE_CLAMAV: 1
      ENABLE_FAIL2BAN: 1
      SA_TAG2: 4.0
    restart: unless-stopped
```
