### ISSUE TITLE
Is there a way to cleanup the docker logs output?

### ISSUE THREAD

**Issue by helmutundarnold** [tomav/docker-mailserver#860]
Current when I run _`"docker logs <docker-container>"`_ the loglines start with the time from the latest docker-creation. If I checked the logfiles inside  of the container i.e. /var/log/mail/mail.info I can see they are rotated and there are only 4 files. Of course it would be possible to limit the output using 
`_"docker logs --since 1h"_`,  but i fear that memory, disk, swap or something else fills up.

Is there a way to automatically cleanup the docker logs output?
Best Regards  and a big thank you for your excellent job.
               Helmut Arnold

**Comment by 17Halbe** [comment]
Would that help: [Docker-compose Logging](https://docs.docker.com/compose/compose-file/#logging)?
In a different container I use something like this:
```
logging:                                         
      driver: "json-file"                            
      options:                                       
        max-size: "200k"                             
        max-file: "10"                    
```
