### ISSUE TITLE
Spoof failure with valid account and sender address

### ISSUE THREAD

**Issue by johansmitsnl** [tomav/docker-mailserver#892]
@17Halbe introduced in #872 spoof protection but this fails with ldap accounts.

```
 Mar 11 09:30:44 mail postfix/submission/smtpd[1874]: NOQUEUE: reject: RCPT from unknown[172.16.38.1]: 553 5.7.1 <johan@domain.net>: Sender address rejected: not owned by user username@mail.domain.net; from=<johan@domain.net> to=<johan@other.net> proto=ESMTP helo=<macbook>
```

The email server has `mail.domain.net` as the hostname and the email address is johan@domain.net. It  verifies with my username and mail host domain to verify the sender address.

This is incorrect because it should check if the email address matches what is in the ldap as the `mail` field or `mailalias` fields.

**Comment by 17Halbe** [comment]
Thanks for testing! 
Can you check, why the ldap tests succeed? What’s different in the mail_with_ldap container than in yours?
I did check the address against the default ldap-account and ldap-alias config. 
Would be great if you could help debugging since I don‘t run a ldap setup.

**Comment by johansmitsnl** [comment]
Try to use this email address for the account:
https://github.com/17Halbe/docker-mailserver-1/blob/c53c0f67cf18a22acbb1e1434dbb79099778d7ed/test/docker-openldap/bootstrap/ldif/04_user-email-different-uid.ldif

Could it be that the `sender_login_maps.ldap` file is missing? Looking at the tests I don't see why this works and my setup does not. I added in the past fixes to the ldap (found from my setup) and it seemed good to me.

**Comment by 17Halbe** [comment]
No, sender_login_maps.ldap was only needed to aggregate the account and alias config into one file. Since they are being tested directly, this config isn‘t(shouldn‘t) be needed anymore.
I‘m not at home and can‘t test and debug right now. Probably tomorrow. 

So what‘s happening here? 
The emailaddress trying to send an email (in this case user@domain.com) is being tested against all the ldap configs listed in (from memory) sender_login_maps. If there is no match that results in what your server thinks is the logged in user (user@mail.domain.com(strange, right?)) the test will fail and your error message is the result of that.

The strange thing is, why does your system think that your user is logged in as user@mail.domain.com or why is this wrong emailaddress being tested for.
(Sorry for all the probably made mistakes, this has been written on a too small mobile. ;) )

**Comment by johansmitsnl** [comment]
The email adres is like: my_name@domain.com but it rewrites to user@mail.domain.com.
The rest you wrote is correct.

**Comment by 17Halbe** [comment]
Yes, that's what I don't get either. There shouldn't be anyone trying to rewrite anything. 
It's just a lookup table. 
Postfix looks for a match of the address( which is trying to send a mail) in those tables. 
If it doesn't find a match or the match doesn't match exactly the logged in user, it reports `Sender address rejected: not owned by user logged_in_user@domain.net`.
So in your case the lookup doesn't even matter. Postfix might even find a match for johan@domain.net, HOWEVER when postfix then compares the looked up result(johan@domain.net) to the logged in user(username@mail.domain.net) it (correctly) fails.
The big question here now is, why the hell is postfix thinking, that username@mail.domain.net is the logged in user. And i have no idea how to solve this. It would be great to find a test, where the same problem arises.
The only thing I could come up with is, that maybe your 
``` yaml 
hostname: ${HOSTNAME}
domainname: ${DOMAINNAME}
```
settings in the compose file are mangled?! But I don't even know how this would translate to this error.. 

Or do your users log in as `username@mail.domain.net`?

**Comment by 17Halbe** [comment]
@TechnicLab Can you help? You are running a ldap service, right? Do you have the same problems with the current image?

**Comment by 17Halbe** [comment]
@johansmitsnl I really don't know anything about ldap. How do I set up a service for testing? How do I setup the former mentioned user? You got a link to a quick tutorial or the basics?

**Comment by TechnicLab** [comment]
Just verified that messages with forged mail address are rejected and I can still send normal mails, so all things are working as expected.

**Comment by 17Halbe** [comment]
Thanks a lot for your quick reply!!
Could you share your ldap configs? And your docker-compose.yml file? It would be great if we could track that issue down!

**Comment by TechnicLab** [comment]
version: '2'

services:
  mail:
    image: tvial/docker-mailserver:latest
    container_name: mail
    restart: always
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    hostname: mail
    domainname: techniclab.net
    networks:
      ldap:
      internet:
      mail:
       aliases:
          - mail.techniclab.net
    volumes:
      - maildata:/var/mail
      - mailstate:/var/mail-state
      - config:/tmp/docker-mailserver/
      - nginx_ssl:/etc/certs
    environment:
      - OVERRIDE_HOSTNAME=techniclab.net
      - ENABLE_SPAMASSASSIN=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - SPOOF_PROTECTION=1
      - SSL_TYPE=manual
      - SSL_CERT_PATH=/etc/certs/tcl.net.pem
      - SSL_KEY_PATH=/etc/certs/tcl.net.key
      - ONE_DIR=1
      - DMS_DEBUG=0
      - ENABLE_SASLAUTHD=1
      - SASLAUTHD_PASSWD=
      - SASLAUTHD_LDAP_SERVER=ldap_ldap_1
      - SASLAUTHD_MECHANISMS=ldap
      - SASLAUTHD_LDAP_BIND_DN=cn=admin,dc=techniclab,dc=net
      - SASLAUTHD_LDAP_PASSWORD=92kdoejjApwd2
      - SASLAUTHD_LDAP_SEARCH_BASE=dc=techniclab,dc=net
      - SASLAUTHD_LDAP_FILTER=(&(uid=%U)(objectClass=person))
      - ENABLE_LDAP=1
      - LDAP_SERVER_HOST=ldap_ldap_1
      - LDAP_SEARCH_BASE=dc=techniclab,dc=net
      - LDAP_BIND_DN=cn=admin,dc=techniclab,dc=net
      - LDAP_BIND_PW=92kdoejjApwd2
      - LDAP_QUERY_FILTER_GROUP=(&(mailGroupMember=%s)(objectClass=person))
      - LDAP_QUERY_FILTER_ALIAS=(&(mailalias=%s)(objectClass=person))
      - LDAP_QUERY_FILTER_USER=(&(mail=%s)(objectClass=person)) 
      - LDAP_QUERY_FILTER_DOMAIN=(&(|(mail=*@%s)(mailalias=*@%s)(mailGroupMember=*@%s)))
      - DOVECOT_USER_FILTER="(&(mail=%u)(objectClass=person))"
      - DOVECOT_PASS_FILTER="(&(mail=%u)(objectClass=person))"
    cap_add:
      - NET_ADMIN

volumes:
  maildata:
    driver: local
  mailstate:
    driver: local
  config:
    driver: local
  nginx_ssl:
    external:
     name: nginx_ssl
networks:
  ldap:
   external:
    name: ldap
  internet:
   external:
    name: main
  mail:
   external:
    name: mail

**Comment by TechnicLab** [comment]
version: '2'

services:
  mail:
    image: tvial/docker-mailserver:latest
    container_name: mail
    restart: always
    ports:
      - "25:25"
      - "143:143"
      - "587:587"
      - "993:993"
    hostname: mail
    domainname: techniclab.net
    networks:
      ldap:
      internet:
      mail:
       aliases:
          - mail.techniclab.net
    volumes:
      - maildata:/var/mail
      - mailstate:/var/mail-state
      - config:/tmp/docker-mailserver/
      - nginx_ssl:/etc/certs
    environment:
      - OVERRIDE_HOSTNAME=techniclab.net
      - ENABLE_SPAMASSASSIN=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - SPOOF_PROTECTION=1
      - SSL_TYPE=manual
      - SSL_CERT_PATH=/etc/certs/tcl.net.pem
      - SSL_KEY_PATH=/etc/certs/tcl.net.key
      - ONE_DIR=1
      - DMS_DEBUG=0
      - ENABLE_SASLAUTHD=1
      - SASLAUTHD_PASSWD=
      - SASLAUTHD_LDAP_SERVER=ldap_ldap_1
      - SASLAUTHD_MECHANISMS=ldap
      - SASLAUTHD_LDAP_BIND_DN=cn=admin,dc=techniclab,dc=net
      - SASLAUTHD_LDAP_PASSWORD=dedede
      - SASLAUTHD_LDAP_SEARCH_BASE=dc=techniclab,dc=net
      - SASLAUTHD_LDAP_FILTER=(&(uid=%U)(objectClass=person))
      - ENABLE_LDAP=1
      - LDAP_SERVER_HOST=ldap_ldap_1
      - LDAP_SEARCH_BASE=dc=techniclab,dc=net
      - LDAP_BIND_DN=cn=admin,dc=techniclab,dc=net
      - LDAP_BIND_PW=dedede
      - LDAP_QUERY_FILTER_GROUP=(&(mailGroupMember=%s)(objectClass=person))
      - LDAP_QUERY_FILTER_ALIAS=(&(mailalias=%s)(objectClass=person))
      - LDAP_QUERY_FILTER_USER=(&(mail=%s)(objectClass=person)) 
      - LDAP_QUERY_FILTER_DOMAIN=(&(|(mail=*@%s)(mailalias=*@%s)(mailGroupMember=*@%s)))
      - DOVECOT_USER_FILTER="(&(mail=%u)(objectClass=person))"
      - DOVECOT_PASS_FILTER="(&(mail=%u)(objectClass=person))"
    cap_add:
      - NET_ADMIN

volumes:
  maildata:
    driver: local
  mailstate:
    driver: local
  config:
    driver: local
  nginx_ssl:
    external:
     name: nginx_ssl
networks:
  ldap:
   external:
    name: ldap
  internet:
   external:
    name: main
  mail:
   external:
    name: mail

**Comment by mwlczk** [comment]
@TechnicLab please change your pwds. the internetz does not forget.

**Comment by TechnicLab** [comment]
dedede? this is not a real one) If you are about something else, than I'm already in process.

**Comment by mwlczk** [comment]
@TechnicLab your real pwd is 14 chars long, alphanumeric only small and capital letters and has 'pwd' as a substring 
;)

**Comment by TechnicLab** [comment]
Well, looks like changing passwords after accidentally pressing 'enter' was great time investment. Thank you.

**Comment by johansmitsnl** [comment]
Here is my config:

```yaml
mail:
    restart: always
    image: tvial/docker-mailserver:latest
    hostname: mail
    domainname: domain.net
    container_name: mail
    ports:
      - "25:25"
      - "143:143"
      - "465:465"
      - "587:587"
      - "993:993"
      - "4190:4190"
    volumes:
      - ./mail/data/mail:/var/mail
      - ./mail/data/mail-state:/var/mail-state
      - ./mail/config/:/tmp/docker-mailserver/
      - ./certs:/etc/letsencrypt/live
    environment:
      - VIRTUAL_HOST=mail.domain.net
      - LETSENCRYPT_HOST=mail.domain.net
      - LETSENCRYPT_EMAIL=support@domain.net
      - ENABLE_SPAMASSASSIN=1
      - SA_TAG2=3.0
      - SA_KILL=3.5
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=0
      - ONE_DIR=1
      - SPOOF_PROTECTION=1
      - DMS_DEBUG=0
      - ENABLE_MANAGESIEVE=1
      - SSL_TYPE=letsencrypt
      - SASLAUTHD_PASSWD=
      # >>> SASL Authentication
      - ENABLE_SASLAUTHD=1
      - SASLAUTHD_LDAP_SERVER=ldap
      - SASLAUTHD_LDAP_PROTO=
      - SASLAUTHD_LDAP_BIND_DN=cn=admin,dc=domain,dc=net
      - SASLAUTHD_LDAP_PASSWORD=haha
      - SASLAUTHD_LDAP_SEARCH_BASE=dc=domain,dc=net
      #- SASLAUTHD_LDAP_FILTER=(&(|(uniqueIdentifier=%U)(mail=%U))(mailEnabled=TRUE))
      - SASLAUTHD_LDAP_FILTER=(&(objectClass=PostfixBookMailAccount)(uniqueIdentifier=%U))
      - SASLAUTHD_MECHANISMS=ldap
      # <<< SASL Authentication
      # >>> Postfix Ldap Integration
      - ENABLE_LDAP=1
      - LDAP_SERVER_HOST=ldap
      - LDAP_SEARCH_BASE=dc=domain,dc=net
      - LDAP_BIND_DN=cn=admin,dc=domain,dc=net
      - LDAP_BIND_PW=jcf5agM5aX7Xg5Jx8cNNrWFnXayFLLvMbVfGq26mDEKN9jFCEYLTNAK24MUzNDwb
      - LDAP_QUERY_FILTER_ALIAS=(&(mailAlias=%s)(mailEnabled=TRUE))
      - LDAP_QUERY_FILTER_GROUP=(&(mailGroupMember=%s)(mailEnabled=TRUE))
      - LDAP_QUERY_FILTER_USER=(&(mail=%s)(mailEnabled=TRUE))
      - LDAP_QUERY_FILTER_DOMAIN=(&(|(mail=*@%s)(mailalias=*@%s)(mailGroupMember=*@%s))(mailEnabled=TRUE))
      # <<< Postfix Ldap Integration
      # >>> Dovecot Ldap Integration
      - DOVECOT_USER_FILTER=(&(objectClass=PostfixBookMailAccount)(|(uniqueIdentifier=%n)(mail=%u)))
      - DOVECOT_PASS_FILTER=(&(objectClass=PostfixBookMailAccount)(|(uniqueIdentifier=%n)(mail=%u)))
      # <<< Dovecot Ldap Integration
      - PERMIT_DOCKER=host
```

**Comment by 17Halbe** [comment]
Hmm.. I really don't know enough to make any guesses here. @TechnicLab do you see anything problematic on the ldap side in @johansmitsnl yaml file?
@johansmitsnl there is still a passwd: LDAP_BIND_PW. You might want to remove it.
I'm sorry, ldap is a closed book for me.

**Comment by TechnicLab** [comment]
@johansmitsnl I hope LDAP_BIND_PW is not your real password?

**Comment by TechnicLab** [comment]
@johansmitsnl Could you try to add OVERRIDE_HOSTNAME?

**Comment by johansmitsnl** [comment]
@17Halbe @TechnicLab the password was not the real password. No worries but thanks for the alert.

@TechnicLab what override should I set? the domain of the fqdn of the server?

**Comment by TechnicLab** [comment]
@johansmitsnl  The domain after @ symbol. For example test.com for example@test.com.

**Comment by johansmitsnl** [comment]
Changing it gives errors on TLS level and not able to ignore it. But with the override should fix it don't it cause issues with domains that are not the override domain?
Just tested with my setup to send email from a other domain as the mailserver. But it uses the username@mail.domain.com.

When you add a account for your domain like:
**account.name** with email: test@super.com or test@test.super.com
can you send email with spoof enabled?

**Comment by TechnicLab** [comment]
Yes, i can. Very strange problem, currently no ideas.

**Comment by 17Halbe** [comment]
Probably related: #902

**Comment by 17Halbe** [comment]
I just realized, that the test suite creates the same strangely rewritten mail addresses. But also with SPOOF_PROTECTION off.. Is that the case for you as well?

`docker logs mail | grep "@mail."`

**Comment by johansmitsnl** [comment]
Found something interesting with the grep, but don't know if this is what you mean. The email address looks normal in the log.

```
Mar 18 18:42:41 mail postfix/submission/smtpd[21092]: AFBB020682: client=83-162-149-254.ip.xs4all.nl[xxx.xxx.xxx.xxx], sasl_method=PLAIN, sasl_username=johan.smits@mail.domain.net
```

Is it using the sasl username to verify the sender email address and not the email address defined in ldap?

**Comment by johansmitsnl** [comment]
Found some information about this but I don't know the exact details how it works.
* https://wiki.zimbra.com/wiki/Enforcing_a_match_between_the_FROM_address_and_the_sasl_username
* https://warden.github.io/articles/2010-01/postfix-sasl-ldap-auth

**Comment by TechnicLab** [comment]
Most confusing part of this is that this setup is working for me.

**Comment by 17Halbe** [comment]
Ah we got something to work with! :) So @TechnicLab is your SASL username scheme user@maildomain.tld?
And @johansmitsnl is the username being user@mail.domain.net intentional? Could you have a look at how to set up a ldap lookup, which then returns the logged in sasl user instead of the mail-address(for a specified alias or valid mail address)?

**Comment by johansmitsnl** [comment]
@17Halbe here the LDIF of my ldap user entry. The username was not created by me. In my client it is just: johan.smits but it becomes johan.smits@mail.domain.net
Which command output in the container you interested in?

```yaml
# LDIF Export for uniqueIdentifier=user.name,ou=people,dc=domain,dc=net
# Server: ldap (ldap)
# Search Scope: base
# Search Filter: (objectClass=*)
# Total Entries: 1

version: 1

# Entry 1: uniqueIdentifier=user.name,ou=people,dc=domain,dc=net
dn: uniqueIdentifier=user.name,ou=people,dc=domain,dc=net
cn: Johan
gidnumber: 1000
homedirectory: /home/user.name
mail: johan@domain.net
mailalias: alias@domain.net
mailenabled: TRUE
mailgidnumber: 5000
mailgroupmember: group@domain.net
mailhomedirectory: /var/mail/domain.net/johan/
mailstoragedirectory: maildir:/var/mail/domain.net/johan/
mailuidnumber: 5000
objectclass: person
objectclass: PostfixBookMailAccount
objectclass: top
objectclass: extensibleObject
objectclass: posixAccount
sn: Smits
uid: user.name
uidnumber: 1000
uniqueidentifier: user.name
```

**Comment by 17Halbe** [comment]
@TechnicLab can you point out the differences in your setup? As I said, I have no knowledge of ldap.

**Comment by n00dl3** [comment]
/etc/postfix/main.cf:
```
smtpd_sasl_local_domain = $myhostname
```
should be :
```
smtpd_sasl_local_domain = $mydomain
```

**Comment by moqmar** [comment]
I still have this issue:
```
Dec 14 21:52:07 mail postfix/submission/smtpd[1751]: NOQUEUE: reject: RCPT from
port-1-2-3-4.dynamic.as20676.net[1.2.3.4]: 553 5.7.1 <moritz.marquardt@obelix.
example.org>: Sender address rejected: not owned by user momarqua@example.org;
from=<moritz.marquardt@obelix.example.org> to=<test@example.com> proto=ESMTP
helo=<[10.0.0.130]>
```

In the docker-compose.yml, I have the following set:
```yaml
hostname: mail
domainname: example.org # changing this to obelix.example.org doesn't have an effect
environment:
    LDAP_QUERY_FILTER_USER: (&(mail=%s)(mailEnabled=TRUE))
    LDAP_QUERY_FILTER_GROUP: (&(mailGroupMember=%s)(mailEnabled=TRUE))
    LDAP_QUERY_FILTER_ALIAS: (&(mailAlias=%s)(mailEnabled=TRUE))
    LDAP_QUERY_FILTER_DOMAIN: (&(|(mail=*@%s)(mailalias=*@%s)(mailGroupMember=*@%s))(mailEnabled=TRUE))
    DOVECOT_USER_FILTER: (&(objectClass=PostfixBookMailAccount)(|(mail=%u)(mailalias=%u)(uid=%n)))
    DOVECOT_PASS_FILTER: (&(objectClass=PostfixBookMailAccount)(|(mail=%u)(mailalias=%u)(uid=%n)))
    DOVECOT_PASS_ATTRS: uid=user,userPassword=password
    SASLAUTHD_LDAP_FILTER: (&(|(mail=%U)(mailalias=%U)(uid=%U))(mailEnabled=TRUE))
```

My `momarqua` user in OpenLDAP has the `mail` attribute set to `moritz.marquardt@obelix.example.org`, but using `momarqua@example.org` here doesn't change anything.
