### ISSUE TITLE
Can't connect through POP3

### ISSUE THREAD

**Issue by rourke** [tomav/docker-mailserver#894]
I can't seem to connect through pop3, both with or without SSL.

## Context

I can connect through SMTP with SSL, but I can't connect through POP3 at all. With or without SSL, on port 110 or 995. I have opened up both ports in my docker-compose file and also added `ENABLE_POP3=1` to it. I 
I get my SSL certificates through Let's Encrypt. It's also setup for mail.mydomain.com.

When I'm trying to connect the logs show the following error: 

    Mar 11 19:16:08 mail dovecot: pop3-login: Disconnected (no auth attempts in 0 secs): user=<>, rip=102.102.101.10, lip=172.12.0.2, TLS: Disconnected, session=<AkHN2yd45sgKfVIL>

**Edit:** Gmail (web) returns the following error when trying to connect: `SSL error: unknown CA (alert 48)`.

I ran:

    docker exec mail openssl s_client -connect 0.0.0.0:25 -starttls imap -CApath /etc/ssl/certs/

It returns `Verify return code: 0 (ok)`, but it fails on port 143, and all other ports from what I can see.

## Possible Fix

I noticed dovecot is looking for its certificates at `/etc/dovecot/ssl/dovecot.pem`. Is that based on my Let's Encrypt certificates? Is there any way to check if they are legit?
I've read people with this error didn't had their SSL certificates in order.

## Your Environment

* Amount of RAM available: N/A
* Mailserver version used: latest stable
* Docker version used: 17.09.0-ce
* Environment settings relevant to the config: 
`ENABLE_POP3=1`
`SSL_TYPE=letsencrypt`
* Any relevant stack traces ("Full trace" preferred): N/A

**Comment by akmet** [comment]
How did you setup SSL in your docker_compose?

**Comment by rourke** [comment]
I'm using the [letsencrypt container](https://github.com/linuxserver/docker-letsencrypt) from linuxserver. The `letsencrypt` folder is mounted to `/etc/letsencrypt`. Below is the docker-compose file. It is seperated from the mailserver docker-compose file since I followed the readme instructions, but I'm intending to merge them when the mailserver works.

```
  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
    environment:
      - PUID=1000
      - PGID=1000
      - EMAIL=something@tld.com
      - URL=something.com
      - SUBDOMAINS=plex,sonarr,radarr,mail
      - VALIDATION=http
      - TZ=Europe/Paris
    volumes:
      - /home/ubuntu/web:/config
```
