### ISSUE TITLE
Can't get amavis up?

### ISSUE THREAD

**Issue by marv3lls** [tomav/docker-mailserver#899]
## Context

The server won't spin up amavis, so I'm getting tons of errors looking like
`postfix/smtp[18326]: 5C39A19CC4B: to=<user@gmail.com>, relay=none, delay=0.18, delays=0.18/0/0/0, dsn=4.4.1, status=deferred (connect to 127.0.0.1[127.0.0.1]:10024: Connection refused)`
I was simply trying to semd an email to the user. `/var/log/mail/mail.err` is full of lines like:
`Mar 14 05:17:19 mail amavis[463]: (!!)TROUBLE in pre_loop_hook: db_init: BDB no dbS: BDB0002 __fop_file_setup:  Retry limit (100) exceeded, File exists. at (eval 92) line 318.`
I don't know what file it's referencing.

## Expected Behavior

Email should work?
## Actual Behavior

amavis down, only getting lots of errors, not sure of issue
## Steps to Reproduce

1.  
```
5:20:56 root@smuns.ch mail cat ./docker-compose.yml
version: '2'

services:
  mail:
    image: tvial/docker-mailserver:latest
    hostname: mail
    domainname: smuns.ch
    container_name: mail
    restart: always
    ports:
    - "25:25"
    - "143:143"
    - "587:587"
    - "993:993"
    - "110:110"
    - "995:995"
    volumes:
    - maildata:/var/mail
    - mailstate:/var/mail-state
    - ./config/:/tmp/docker-mailserver/
    - ./letsencrypt/etc/letsencrypt:/etc/letsencrypt
    environment:
    - ENABLE_SPAMASSASSIN=1
    - ENABLE_CLAMAV=1
    - ENABLE_POP3=1
    - ENABLE_FAIL2BAN=1
    - ENABLE_POSTGREY=1
    - SSL_TYPE=letsencrypt
    - ONE_DIR=1
    - DMS_DEBUG=0
    cap_add:
    - NET_ADMIN

volumes:
  maildata:
    driver: local
  mailstate:
    driver: local
```
2. 
```
5:21:57 root@marvell.cat mail ls -la
total 44
drwxr-xr-x  7 root root 4096 Mar 14 05:21 .
drwx------ 27 root root 4096 Mar 14 05:22 ..
-rw-r--r--  1 root root    0 Jan 29 00:35 cat
drwxr-xr-x  4 root root 4096 Mar 14 05:15 config
-rw-r--r--  1 root root  727 Jan 30 03:51 docker-compose.yml
drwxr-xr-x  8 root root 4096 Oct 13 20:51 etc
drwxr-xr-x  4 root root 4096 Oct 13 21:07 letsencrypt
drwxr-xr-x  2 root root 4096 Oct 13 20:51 log
-rw-r--r--  1 root root 5484 Feb 12 06:26 master
-rwxr-xr-x  1 root root 3626 Oct 13 20:43 setup.sh
drwxr-xr-x  2 root root 4096 Oct 13 20:43 ssl
```

## Your Environment

* Amount of RAM available: 512 MB
* Mailserver version used: Not sure. Did `docker-compose down --rmi all;docker-compose up -d mail` and still have the problem
* Docker version used: Docker version 17.12.1-ce, build 7390fc6
* Environment settings relevant to the config: See above
* Any relevant stack traces ("Full trace" preferred):

    How do I get this?
