### ISSUE TITLE
Logs & daily report contain lots of "warning: dnsblog_query: lookup error for DNS query"

### ISSUE THREAD

**Issue by capi** [tomav/docker-mailserver#948]
I am new to using postscreen with DNS blacklists, I never configured them before, so maybe this is a misunderstanding on my part. To my understanding, a host is on the blacklist, if the DNS query returns a positive response.

I now see a lot of entries similar like this in the log files, and they are also reported in the daily summary e-mail as warnings:
```
Apr 11 09:20:26 mail postfix/dnsblog[11746]: warning: dnsblog_query: lookup error for DNS query 165.144.196.217.list.dnswl.org: Host or domain name not found
. Name service error for name=165.144.196.217.list.dnswl.org type=A: Host not found, try again
```

To my understanding, this indicates that the IP is not on the blacklist.

## Context
Default configuration on v5.8.1

## Expected Behavior
The line above should not be added to the log, and not included in the daily summary e-mail.

## Actual Behavior
It is logged and as it is a warning, also reported in the daily summary e-mail.

**Comment by crazystick** [comment]
If you're using Google's public DNS servers (or several other public DNS servers) they don't allow querying of DNSBL. You can use the new Cloudflare DNS 1.1.1.1 or 1.0.0.1

I started working on a companion container that would run Unbound but since Cloudflare released their DNS servers, I gave up.

You can add the following to your docker-compose.yml to fix this:

```
services:
  mail:
    image: ...
    ...
    dns: 1.1.1.1
```

**Comment by capi** [comment]
Thank you. The docker host below was actually using 8.8.8.8. I updated this to my hosting provider's DNS servers (up until I checked I was quite sure I was using those). Will report back, if this fixes the issue.

**Comment by capi** [comment]
I can confirm that with my own DNS server this is working as it should. So this is a host/DNS server configuration issue and not related to `docker-mailserver`. On the contrary, it is _good_ that these lines are logged, since they show that DNS configuration is not working as intended.

I will therefore close this issue. Thanks for the help!

**Comment by theoneandonly-vector** [comment]
I added this to my local docker-compose.override.yml
```
mail:
   image: tvial/docker-mailserver:latest
   hostname: mail
   domainname: neutronix.ch
   volumes:
    - /var/lib/docker/volumes/kopano_web/_data/acme/acme-v02.api.letsencrypt.org/sites/mail.neutronix.ch:/tmp/ssl:>
    - log:/var/log
   environment:
   - ENABLE_POSTGREY=0
   - SPAMASSASSIN_SPAM_TO_INBOX=1
   - SMTP_ONLY=1
   - POSTFIX_MAILBOX_SIZE_LIMIT=
   - POSTFIX_MESSAGE_SIZE_LIMIT=20971520
   dns: 1.1.1.1
```

   - ENABLE_POSTGREY=0
and
   - SPAMASSASSIN_SPAM_TO_INBOX=1
are working correctly. but I still can't resolve a domain from inside mail-docker:
```
(Host or domain name not found. Name service error for name=mobi.ch type=MX: Host not found, try again)
```

```
(delivery temporarily suspended: Host or domain name not found. Name service error for name=mobi.ch type=MX: Host not found, try again)
```
