### ISSUE TITLE
Postfix ErrorRecipient address rejected: User unknown in local recipient table

### ISSUE THREAD

**Issue by Reldeis** [tomav/docker-mailserver#97]
Hi,

unfortunately i can't receive mails on my server from external addresses. 

- Sending from user@docker-mail.tld to user@docker-mail.tld works as expected (send and receive).
- Sending from user@docker-mail.tld to someone@example.com works as expected 
- Sending from someone@example.com to user@docker-mail.tld gets returned with the following error

```
Message-id: <yyy@xxx.com>
 Date: Fri, 04 Mar 2016 17:29:52 +0100
 From: Someone <someone@example.com>
 To: User <user@docker-mail.tld >
 Subject: testi test

Your message cannot be delivered to the following recipients:

 Recipient address: user@docker-mail.tld 
 Reason: Remote SMTP server has rejected address
 Diagnostic code: smtp;550 5.1.1 <user@docker-mail.tld >: Recipient address rejected: User unknown in local recipient table
 Remote system: dns;mx00.udag.de (TCP|17.164.101.13|38590|62.146.106.39|25) (mx00.udag.de ESMTP ready)

Original-envelope-id: 0O3I00BVOWHULS50@st14p23im-asmtp003.me.com
Reporting-MTA: dns;st14p23im-asmtp003.me.com (tcp-daemon)
Arrival-date: Fri, 04 Mar 2016 16:29:55 +0000 (GMT)

Original-recipient: rfc822;user@docker-mail.tld 
Final-recipient: rfc822;user@docker-mail.tld 
Action: failed
Status: 5.1.1 (Remote SMTP server has rejected address)
Remote-MTA: dns;mx00.udag.de (TCP|17.164.101.13|38590|62.146.106.39|25)
(mx00.udag.de ESMTP ready)
**Diagnostic-code: smtp;550 5.1.1 <user@docker-mail.tld >: Recipient address
rejected: User unknown in local recipient table
```

a als check from [http://www.checktls.com/perl/TestReceiver.pl](http://www.checktls.com/perl/TestReceiver.pl) in [pastebin](http://pastebin.com/19GTEr7u)

Last but not least my docker-compose.yml:
```
mail:
  image: tvial/docker-mailserver
  hostname: mail
  domainname: docker-mail.tld
  # your FQDN will be 'mail.domain.com'
  ports:
  - "25:25"
  - "143:143"
  - "587:587"
  - "993:993"
  volumes:
  - /opt/mail/spamassassin:/tmp/spamassassin/
  - /opt/mail/postfix:/tmp/postfix/
  - /opt/mail/mails:/var/mail/
  - /etc/letsencrypt/:/etc/letsencrypt/
  environment:
  - DMS_SSL=letsencrypt
```
