### ISSUE TITLE
Couldn't drop privileges: User is missing UID (see mail_uid setting)

### ISSUE THREAD

**Issue by ArthurAttout** [tomav/docker-mailserver#973]
After binding the mailserver with OpenLDAP, users are not able to identify using their username + password. 

`May 16 17:53:00 mail dovecot: pop3(user@domain.org): Error: Couldn't drop privileges: User is missing UID (see mail_uid setting)`

Docker-compose : 
```

mail:
    image: tvial/docker-mailserver:latest
    hostname: mail
    domainname: ${SMTP_DOMAIN}
    ports:
      - "$PORT_SMTP:25"
      - "8143:143"
      - "8110:110"
      - "8587:587"
      - "8993:993"
      - "8995:995"
    
    environment:
    - HOSTNAME=mail
    - DOMAINNAME=${SMTP_DOMAIN}
    - ENABLE_POP3=1
    - ENABLE_LDAP=1
    - LDAP_SERVER_HOST=172.20.0.20
    - LDAP_SEARCH_BASE=${LDAP_SEARCH_BASE}
    - LDAP_BIND_DN=${LDAP_BIND_DN}
    - LDAP_BIND_PW=${LDAP_ADMIN_PASSWORD}
    - LDAP_QUERY_FILTER_USER="(&(mail=%s))"
    - LDAP_QUERY_FILTER_GROUP="(&(mailGroupMember=%s))"
    - LDAP_QUERY_FILTER_ALIAS="(&(mailAlias=%s))"
    - SASLAUTHD_LDAP_FILTER="(&(uid=%U)(objectClass=posixAccount))"
    - DOVECOT_PASS_FILTER="(&(objectClass=posixAccount)(mail=%u))"
    - DOVECOT_USER_FILTER="(&(objectClass=posixAccount)(mail=%u))"
    - POSTMASTER_ADDRESS="postmaster@${SMTP_DOMAIN}.org"
    
    cap_add:
    - NET_ADMIN
    - SYS_PTRACE
    restart: always
```

When looking at the logs of OpenLDAP, the request is correctly processed, a user is returned, but the mailserver seems to handle this response incorrectly. 

I also don't see where I could fix this, since I coudln't find the file `mail_uid` nor any settings related to this. 

Any fix or help for that ? 
Thanks 👍 !
