### ISSUE TITLE
Fail2Ban ignored IP are not persistent

### ISSUE THREAD

**Issue by madmath03** [tomav/docker-mailserver#981]
The fail2ban ignored IP are not persistent.

## Context
When restarting the docker-mailserver container, the ignored IP are lost.

By default, fail2ban will ban every IP that has too many failed login attempts.
It works as expected when I am using mail client like Thunderbird or Outlook, but if I use a web mail client like RoundCube, the RoundCube IP's ends up being banned, preventing any user to use it! I thought it may be related to #523 but it's not docker's gateway that gets banned but the container itself and banning the RC IP makes sense (technically speaking).

I am setting the mail server and roundcube through docker-compose.

I am using the `fail2ban-client` to add the IP of RoundCube instance to dovecot ignoreip list:
```
docker exec mail /bin/sh -c "fail2ban-client set dovecot addignoreip $IP"
```
It works great, but when I restart the mail container, the ignore IP list is reset and I must add the IP all over again.

## Expected Behavior
The ignored IP is reloaded after restarting the container.

## Actual Behavior
IP ignore list is lost on restart.

## Possible Fix
It may be a fail2ban limitation... but if that's the case I guess we could have a function in the setup script to store and reload this.
We could have a function to add ignored IP to a file and call fail2ban-client. Then read the content of the file on startup and call fail2ban-client for each entry.

## Steps to Reproduce
1. docker-compose.yml
```yml

  mail:
    image: tvial/docker-mailserver:release-v5.8.0
    container_name: mail
    restart: always
    environment:
      - DMS_DEBUG=1
      - ONE_DIR=1
      - ENABLE_SPAMASSASSIN=1
      - ENABLE_CLAMAV=1
      - ENABLE_FAIL2BAN=1
      - ENABLE_POSTGREY=1
    cap_add:
      - NET_ADMIN
      - SYS_PTRACE
    volumes:
      - /srv/mail/data:/var/mail
      - /srv/mail/state:/var/mail-state

  roundcube:
    image: roundcube/roundcubemail
    container_name: roundcube
    restart: always
    environment:
      # System properties
      - ROUNDCUBEMAIL_UPLOAD_MAX_FILESIZE=5M
      - ROUNDCUBEMAIL_LOG_DIR=/srv/logs
      # IMAP server connection
      - ROUNDCUBEMAIL_DEFAULT_HOST=tls://mail
      - ROUNDCUBEMAIL_DEFAULT_PORT=143
      # SMTP server connection
      - ROUNDCUBEMAIL_SMTP_SERVER=tls://mail
      - ROUNDCUBEMAIL_SMTP_PORT=587
    volumes:
      - /srv/roundcube/html:/var/www/html
      - /srv/roundcube/logs:/srv/logs

```
2. Add the roundcube container IP to fail2ban ignore list and confirm:
```bash
# We add the container name (will work even when container restart and changes IP)
docker exec mail /bin/sh -c "fail2ban-client set dovecot delignoreip roundcube"
docker exec mail /bin/sh -c "fail2ban-client get dovecot ignoreip"
```
3.  Restart containers using docker-compose and check the ignore IP list:
```bash
docker-compose restart
# roundcube is not part of the ignore list anymore
docker exec mail /bin/sh -c "fail2ban-client get dovecot ignoreip"
```

## Your Environment
* Mailserver version used: 5.8.0
* Docker version used: Docker version 18.03.0-ce, build 0520e24
