### ISSUE TITLE
save failed to INBOX: open(/var/mail/...) Permission denied

### ISSUE THREAD

**Issue by sleif** [tomav/docker-mailserver#986]
## Description
The function "_fix_var_mail_permissions()" from startup script "target/start-mailserver.sh" breaks postfix and dovecot.
From LDAP the real uidNumber and gidNumber will be provided to postfix und dovecot. So both processes run into trouble as long all ownership in /var/mail belongs to uid 5000 (always set by the function above).

## Expected Behavior
permissions on directory /var/mail remain unchanged across container restart

## Actual Behavior

```
Jun 11 22:41:59 docker-mailserver dovecot: lmtp(ftp@werni.de): Error: open(/var/mail/werni.de/ftp/tmp/1528756919.M184564P1999.docker-mailserver) failed: Permission denied
Jun 11 22:41:59 docker-mailserver dovecot: lmtp(ftp@werni.de): msgid=<f7dda415-4f8d-4472-f474-f8e90c93ae7b@slf.de>: save failed to INBOX: open(/var/mail/werni.de/ftp/tmp/1528756919.M184564P1999.docker-mailserver) failed: Permission denied
```

## Possible Fix
run _fix_var_mail_permissions() only if no real user and group IDs will be used

## Steps to Reproduce
start the container

## Your Environment
* Mailserver version used: latest 2018-06-02T19:16:20.271Z
* Environment settings relevant to the config:
```
    env:
      OVERRIDE_HOSTNAME: "mail.werni.de"
      SSL_TYPE: "manual"
      SSL_CERT_PATH: "/tmp/ssl/fullchain.pem"
      SSL_KEY_PATH: "/tmp/ssl/privkey.pem"
      ENABLE_SPAMASSASSIN: 1
      ENABLE_CLAMAV: 1
      ENABLE_FAIL2BAN: 1
      ENABLE_POSTGREY: 1
      ONE_DIR: 1
      DMS_DEBUG: 1
      ENABLE_LDAP: 1
      LDAP_SERVER_HOST: "{{ LDAP_VIRTUAL_HOST }}" # your ldap container/IP/ServerName
      LDAP_SEARCH_BASE: "ou={{ LDAP_OU_USERS }},{{ LDAP_BASE_DN }}"
      LDAP_BIND_DN: "cn={{ LDAP_READONLY_USER_USERNAME }},{{ LDAP_BASE_DN }}"
      LDAP_BIND_PW: "{{ LDAP_READONLY_USER_PASSWORD }}"
      LDAP_QUERY_FILTER_USER: "(mail=%s)"
      LDAP_QUERY_FILTER_GROUP: "(&(mailGroupMember=%s)(mailenable=TRUE))"
      LDAP_QUERY_FILTER_ALIAS: "(mailalias=%s)"
      LDAP_QUERY_FILTER_DOMAIN: "(&(|(mail=*@%s)(mailalias=*@%s)(mailGroupMember=*@%s))(mailEnabled=TRUE))"
      DOVECOT_TLS: 1
      DOVECOT_PASS_FILTER: "(&(uid=%n)(objectClass=posixAccount))"
      DOVECOT_USER_FILTER: "(&(uid=%n)(objectClass=person))"
      ENABLE_SASLAUTHD: 1
      SASLAUTHD_LDAP_SSL: yes
      SASLAUTHD_MECHANISMS: ldap
      SASLAUTHD_LDAP_SERVER: "{{ LDAP_VIRTUAL_HOST }}" # your ldap container/IP/ServerName
      SASLAUTHD_LDAP_BIND_DN: "cn={{ LDAP_READONLY_USER_USERNAME }},{{ LDAP_BASE_DN }}"
      SASLAUTHD_LDAP_PASSWORD: "{{ LDAP_READONLY_USER_PASSWORD }}"
      SASLAUTHD_LDAP_SEARCH_BASE: "ou={{ LDAP_OU_USERS }},{{ LDAP_BASE_DN }}"
      SASLAUTHD_LDAP_FILTER: "(&(uid=%U)(objectClass=person))"
      POSTMASTER_ADDRESS: postmaster@localhost.localdomain
    capabilities:
      - NET_ADMIN
      - SYS_PTRACE
```
